### ISSUE TITLE
(dev server) web cannot find /graphql endpoint if redwood.toml web.apiUrl="/"

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#4352] opened 2022-02-02 22:37 UTC
The redwood.toml web.apiURl value is expected to accept any "absolute path (thats starts with `/`) or an absolute URI that starts with `http[s]://" 

However, if I set `web.apiUrl="/"` I get the following behavior:
- local api and web server start successfully
- endpoint error 

console log:
```
[Error] A server with the specified hostname could not be found.
[Error] Fetch API cannot load http://graphql/ due to access control checks.
[Error] Failed to load resource: A server with the specified hostname could not be found. (graphql, line 0)
```

http://localhost:8911:
```
{"error":"Function \"\" was not found.","availableFunctions":["graphql","healthz"]}
```

**Comment by thedavidprice** [comment] 2022-02-02 22:41
One resolved, I'd like to make a simple change to deploy setup render command. See:
- https://github.com/redwoodjs/redwood/pull/4278#discussion_r796005500

**Comment by dac09** [comment] 2022-02-03 05:20
Hi DP, blessing in disguise that it didn't work. Let's discuss this later but I'm 95% sure setting apiUrl to / is a misconfiguration.

**Comment by 0x1a4f7d58** [comment] 2022-02-21 17:02
I'm getting the same error for new projects... ```yarn create redwood-app redwood-is-awesome-app``` and navigate to http://localhost:8911/

```
{"error":"Function \"\" was not found.","availableFunctions":["graphql"]}
```

Is there a workaround or fix? Perhaps revert to an earlier version?

**Comment by dac09** [comment] 2022-02-21 17:03
I believe that's a legitimate error @0x1a4f7d58 - redwood's web server runs on localhost:8910. 

By default you get localhost:8911, and a function at localhost:8911/graphql (not at the root, by design)

**Comment by 0x1a4f7d58** [comment] 2022-02-21 17:07
Ah yes, apologies. http://localhost:8911/graphql works. Thank you 🙏

**Comment by dac09** [comment] 2022-04-11 06:12
@thedavidprice I'm going to close this issue because as we've discussed on the CTM I believe this is expected behaviour! 

You cannot set the apiUrl to /, because that's for root for the web side. The API has to be accessible from a different path or url from your webside

Feel free to reopen and we can discuss again if you need it!

**Closed by dac09** 2022-04-11 06:12 UTC
Labels: help wanted, good first issue, bug/confirmed
