### ISSUE TITLE
"Publish Canary" GH Action is failing

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#588] opened 2020-05-22 22:03 UTC
See:
https://github.com/redwoodjs/redwood/runs/700859314

Error at end of section:
```bash
lerna ERR! E403 You cannot publish over the previously published versions: 0.7.1-canary.4.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

Notes:
- GH Actions were down this morning. Maybe caused a hiccup?
- Possibly an error cause by this newly merged PR #581 ?

**Comment by thedavidprice** [comment] 2020-05-23 03:54
Update, using the regular "Release" process, I just manually released `0.7.1-canary.8`. This also updated the `package.json` files.

Not sure if this will help kickstart the GH Action again or just make things worse.

**Comment by peterp** [comment] 2020-05-23 08:57
Whoops! We should never commit or tag the canary releases.

**Comment by peterp** [comment] 2020-05-23 09:10
I think the root cause of this is that we published canary releases when we published release candidates.

**Comment by peterp** [comment] 2020-05-23 10:07
We'll release another version soon, bump the version, and then this will resolve. I think I should create another task for release candidates that doesn't tag or commit to the repo.

**Comment by thedavidprice** [comment] 2020-05-27 03:12
When I look at how "other" projects are managing this, both the `canary` and `rc` releases include `package.json` version updates and are published as `pre-releases` on GitHub. Wondering if there was a specific reason you were specifically _not_ doing that here? This might help with visibility, e.g. what's the latest canary along with related commit.

I think we should still handle rc and stable releases through the same manual process (for now). If so, two improvements to the current automation:
1. don't run the canary release GH Action in case of any other tag used, e.g. `latest` or `rc`
2. add a new task to manually 'reset' the canary publishing --> again, what happened here is that either 1) GH Actions being down or 2) the PR change to the Action ended up causing the canary publishing to "fall behind" and then started failing. The only way I knew to get a new canary published (or attempt to reset) was to follow our manual process

**Comment by peterp** [comment] 2020-07-05 07:26
Can we close this off as we now understand why the canary releases are failing - and since we no longer do release candidates it shouldn't be a problem?

**Closed** 2020-07-07 20:58 UTC
Labels: bug/2-confirmed, topic: contributor-dx
