### ISSUE TITLE
Error in Redwood Studio

### ISSUE THREAD

**Issue by arreagaelio1** [redwoodjs/redwood#9807] opened 2024-01-07 00:15 UTC
### What's not working?

When I run the yarn rw exp studio command I get this:
`Reanalysing mailer and mail templates...
Error reloading mailer:
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supporte
d by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol
 'c:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:136:11)
    at defaultLoad (node:internal/modules/esm/load:87:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
 - Analysed 1 mail templates`

### What's your environment? (If it applies)

```shell
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.2 - ~\AppData\Local\Temp\xfs-d9a8cdb3\node.CMD
    Yarn: 3.7.0 - ~\AppData\Local\Temp\xfs-d9a8cdb3\yarn.CMD
  Browsers:
    Chrome: 81.0.4044.129
    Edge: Chromium (120.0.2210.91)
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 6.6.2 => 6.6.2
    @redwoodjs/core: 6.6.2 => 6.6.2
    @redwoodjs/studio: 6.6.2 => 6.6.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment] 2024-01-07 01:39
Thanks for raising this issue @arreagaelio1! I'll take a stab at debugging this tomorrow and update this issue when I do.

**Comment by xmaxcooking** [comment] 2024-01-07 10:22
I'm encountering the same issue on windows.

**Comment by Josh-Walker-GM** [comment] 2024-01-07 21:31
Hi all. I think this issue has been fixed in #9639 but that is still waiting for our next minor release. It should be possible to use a canary version to avoid this issue until such time as our next minor is out. It might even be helpful if you could confirm that this is indeed fixed by upgrading to the latest canary and confirming the error goes away.

Just a small notice that we're in the process of swapping out studio for an upgraded version based on an ongoing rewrite. So just a little heads up that studio might undergo a bit of a change this month and will hopefully be available as a non-experimental feature. 

CC @Tobbe

**Comment by xmaxcooking** [comment] 2024-01-07 22:05
@Josh-Walker-GM sounds good. really looking forward to finally try mailer

**Comment by gvtret** [comment] 2024-01-08 06:01
on WSL2 it's work fine.
![2024-01-08 09 00 18](https://github.com/redwoodjs/redwood/assets/6426805/85f8e1fc-ec61-4400-b9a7-fc62b4560d09)

**Comment by Tobbe** [comment] 2024-01-08 07:23
Closing this as a duplicate of https://github.com/redwoodjs/redwood/issues/9545

**Closed by Tobbe** 2024-01-08 07:23 UTC
Labels: bug/needs-info, topic/studio
