### ISSUE TITLE
Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js'

### ISSUE THREAD

**Issue by Albert-Gao** [redwoodjs/redwood#3066] opened 2021-07-19 07:33 UTC
Just a brand new project, everything works great, except for this little annoying issue, happens for all my tests

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/18282328/126063679-170d9f62-ee2b-4182-b5dc-d51e2ca9a04c.png">

All the test files will have this error every 2 minutes or something, and if you click to open the file, the error is gone, then after a while, happens again

I am using `"@redwoodjs/core": "0.35.1"` and vscode `1.58.2`

It is from this plugin:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/18282328/126120616-58d6d525-57bd-487e-9dd7-cfa76bc082cf.png">

The error message is:

```
  ● Test suite failed to run

    Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js'

    Require stack:
      node_modules/@redwoodjs/testing/dist/MockProviders.js
      node_modules/@redwoodjs/testing/dist/customRender.js
      node_modules/@redwoodjs/testing/dist/index.js
      web/src/components/ToDosCell/ToDosCell.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/dist/MockProviders.js:32:5)
```

What am I missing here?

**Comment by thedavidprice** [comment] 2021-07-19 23:22
Very strange @Albert-Gao Thank you for reporting this! 

I cannot reproduce this on my end, which is MacOS. Could you reply with your system info via `yarn rw info`?

@peterp curious if this might be a part of your Jest fixes for Windows in #2938

**Comment by Albert-Gao** [comment] 2021-07-19 23:26
Sure, here you go


```
➜  redwoodToDos git:(master) ✗ yarn rw info
yarn run v1.22.10
$ /Users/albertgao/codes/temp/redwoodToDos/node_modules/.bin/rw info

  System:
    OS: macOS 11.4
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /var/folders/l8/nmmhmylj0hq3pbtt61p77p7w0000gn/T/yarn--1626737042624-0.4951676818631754/node
    Yarn: 1.22.10 - /var/folders/l8/nmmhmylj0hq3pbtt61p77p7w0000gn/T/yarn--1626737042624-0.4951676818631754/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 91.0.4472.164
    Safari: 14.1.1
  npmPackages:
    @redwoodjs/core: 0.35.1 => 0.35.1 

✨  Done in 4.70s.
```

I found a temp fix, disable the auto-run-test feature of that plugin: in VSC fixed it.

```
 "jest.autoRun": "off"
```

**Comment by thedavidprice** [comment] 2021-07-19 23:37
AH, this is not related to the issue I asked Peter about.

We have a custom Jest setup() for both Web and API. In the case of API, we need to init a test DB and also spin up Mock Service Worker (among other things). It seems that VS Code extension doesn't take our config into account correctly.

I'm not sure if this is something we'll be able to look into for a "fix".

Do you know if there's a way to add this to a project config (or to jest.config)?

**Comment by thedavidprice** [comment] 2021-07-21 22:02
FYI: we are upgrading to Jest v27 in #2893 and also switching the test runner from jasmine2 to jest-circus. 

There's an off chance this will resolve your issue. Keep a look out for v0.36.0 release and keep us posted!

**Comment by jtoar** [comment] 2022-07-19 07:27
Closing this one due to staleness and inability to reproduce. We'll be upgrading to Jest v28 soon, so if it happens to come up again then we'll be sure to address it.

**Closed by jtoar** 2022-07-19 07:27 UTC
Labels: topic/testing
