### ISSUE TITLE
[Bug?]: `web/src/auth.ts` file isn't generated after running `yarn rw generate dbAuth` in RW v7.1.3

### ISSUE THREAD

**Issue by evansibok** [redwoodjs/redwood#10290] opened 2024-03-25 07:48 UTC
### What's not working?

For a new project, when you generate dbAuth, the `auth.ts` file in the `web/src` folder isn't generated and causes import issues in places where it is used like the LoginPage for example.

### How do we reproduce the bug?

1. Run `yarn create redwood-app example`
2. Run `cd example`
3. Run `yarn install`
4. Run `yarn rw generate dbAuth`
5. Inspect project structure and peek `web/src/Pages/LoginPage/LoginPage.tsx` file and you will see the error
6. Inspect project structure and peek `web/src` and the `auth.ts` file will be missing

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 14.4
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /private/var/folders/1q/m38hblrd4ksfw85tccbsk05m0000gn/T/xfs-530c3d9f/node
    Yarn: 4.1.0 - /private/var/folders/1q/m38hblrd4ksfw85tccbsk05m0000gn/T/xfs-530c3d9f/yarn
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Safari: 17.4
  npmPackages:
    @redwoodjs/core: 7.1.3 => 7.1.3 
    @redwoodjs/project-config: 7.1.3 => 7.1.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment] 2024-03-25 14:53
Hi @evansibok! Thanks for trying out redwood and opening this issue! 

I think this is the expected behaviour as we have two separate commands when it comes to setting up dbAuth. We have the UI side of things which is `yarn rw generate dbAuth` - the one you mention here. There is another command `yarn rw setup auth dbAuth` which adds the files that you are missing. 

My understanding is that we have two in this case because we have many different `yarn rw setup auth ...` commands for the different auth providers we support.

I ran through the steps in your reproduction and saw the same list of files setup and that the `auth.ts` wasn't present yet. The text output at the end of `yarn rw generate dbAuth` does mention the need to run `yarn rw setup auth dbAuth` and we also walk through using both commands in the tutorial [chapter 4](https://redwoodjs.com/docs/tutorial/chapter4/authentication). 

<img width="1319" alt="image" src="https://github.com/redwoodjs/redwood/assets/56300765/adcbda59-a429-41e9-b04a-0e3dd1aad708">

Is this helpful?

**Comment by evansibok** [comment] 2024-03-25 16:05
Got it, thank you 🙏🏽

Guess we can close this

**Comment by dthyresson** [comment] 2024-03-25 21:06
> Got it, thank you 🙏🏽
> 
> Guess we can close this

Will do, but thanks for reporting!

I think I'll add a docs PR for https://redwoodjs.com/docs/cli-commands#generate-dbauth so that it's clear that `yarn rw setup auth dbAuth` should be done as a prerequisite to `yarn rw generate dbAuth` using the language of the Cli noted above.

**Comment by dthyresson** [comment] 2024-03-25 21:12
Am closing, but addressing in https://github.com/redwoodjs/redwood/pull/10293

**Closed by dthyresson** 2024-03-25 21:12 UTC
Labels: bug/needs-info
