### ISSUE TITLE
[Bug?]: initial deploy to Vercel not working with latest (rw 7.0.6, node 20)

### ISSUE THREAD

**Issue by jason-curtis** [redwoodjs/redwood#10100] opened 2024-03-02 22:37 UTC
### What's not working?

Initial deploy to Vercel fails. Error log: https://gist.github.com/jason-curtis/c922f9cf3b5520e9d2d418667555642b

Key section of the log appears to be:
```
[14:27:06.339] $ /vercel/path0/node_modules/.bin/rw data-migrate up
[14:27:07.038] Installing plugin "@redwoodjs/cli-data-migrate"...
[14:27:08.101] error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
[14:27:08.101] info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[14:27:08.116] Error: Command failed with exit code 1: yarn add -D @redwoodjs/cli-data-migrate@7.0.6
```

### How do we reproduce the bug?

* Create a new redwood project w/ `yarn create redwood-app whatever`
* push it to a github repo
* Start a new deploy from that project on Vercel
  * it will fail the first time until you go into project settings and set node version to 20 (expected, I guess?)
* Start a redeploy
* deploy fails with the error above.

### What's your environment? (If it applies)

```shell
(this info may not be relevant since the error is happening on vercel but I ran `yarn rw info` locally)

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - /tmp/xfs-40a4659e/node
    Yarn: 4.1.0 - /tmp/xfs-40a4659e/yarn
  Browsers:
    Chrome: 121.0.6167.139
  npmPackages:
    @redwoodjs/core: 7.0.6 => 7.0.6 
    @redwoodjs/project-config: 7.0.6 => 7.0.6
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jason-curtis** [comment] 2024-03-03 03:38
Interestingly, if I deploy manually using a Github Action with these steps it works fine:
```yaml
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --prod
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
```

But if I use this pre-built GH action, I get the `Running this command will add the dependency to the workspace root` error:
```yaml

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Include a --prod flag for Vercel CLI, but leave empty for preview deploys
          vercel-args: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

```

**Comment by Tobbe** [comment] 2024-03-03 21:48
Thanks for providing a workaround @jason-curtis

I'll have someone on the team take a look at this issue that's more familiar with both data-migrate and Vercel deploys than I am. They, or I, will get back to you as soon as we've had a chance to investigate.

**Comment by jtoar** [comment] 2024-03-05 01:32
Hey @jason-curtis I can reproduce and I'm pretty sure I know what's at play. Will circle back once I confirm.

**Comment by jtoar** [comment] 2024-03-05 01:41
@jason-curtis I think you have to enable Corepack in Vercel's build container via `ENABLE_EXPERIMENTAL_COREPACK=1`:

<img width="951" alt="image" src="https://github.com/redwoodjs/redwood/assets/32992335/4b26568a-ca00-4cc8-b776-1d23fb5ae685">

https://vercel.com/docs/deployments/configure-a-build#corepack

I should update the setup command to call this out.

**Comment by jtoar** [comment] 2024-03-12 11:29
@ahaywood not working on this go for it

**Comment by rafavalerio** [comment] 2024-03-29 10:42
When adding `ENABLE_EXPERIMENTAL_COREPACK=1` to my Vercel env, the build fails at:
```[21:36:40.516] Running build in Washington, D.C., USA (East) – iad1
[21:36:43.113] Vercel CLI 33.6.1
[21:36:43.640] Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "yarn@4.1.0" in package.json
[21:36:43.954] Installing dependencies...
[21:36:45.525] ➤ YN0000: · Yarn 4.1.0
[21:36:45.559] ➤ YN0000: ┌ Resolution step
[21:37:24.391] ➤ YN0085: │ + @redwoodjs/api@npm:7.1.3, @redwoodjs/core@npm:7.1.3, @redwoodjs/forms@npm:7.1.3, @redwoodjs/graphql-server@npm:7.1.3, and 2099 more.
[21:37:24.453] ➤ YN0000: └ Completed in 38s 894ms
[21:37:24.587] ➤ YN0000: ┌ Post-resolution validation
[21:37:24.588] ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
[21:37:24.588] ➤ YN0000: └ Completed
[21:37:24.588] ➤ YN0000: · Failed with errors in 39s 62ms
[21:37:24.668] Error: Command "yarn install" exited with 1
[21:37:24.862] ```

Any ideas on how to solve this?

**Comment by thedavidprice** [comment] 2024-03-29 15:43
@rafavalerio just to make sure, when you run `yarn` on your project locally, are there any changes to your `yarn.lock` that need to be checked in to git? If not, we'll need to dig a bit deeper here.

**Comment by rafavalerio** [comment] 2024-03-30 00:28
> @rafavalerio just to make sure, when you run `yarn` on your project locally, are there any changes to your `yarn.lock` that need to be checked in to git? If not, we'll need to dig a bit deeper here.

Hi @thedavidprice, the reason was locally I was using Yarn 1.x and having Yarn 4.x on Vercel! All solved now!

**Comment by thedavidprice** [comment] 2024-04-24 01:29
fixed by https://github.com/redwoodjs/redwood/pull/10355

**Closed by thedavidprice** 2024-04-24 01:29 UTC
Labels: bug/needs-info, topic/deployment
