### ISSUE TITLE
[FAQ] `yarn rw link` tracking issues and common problems for contributing

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#2215] opened 2021-04-05 12:46 UTC
Creating this issue to highlight commonly faced issues, and suggested solutions, when trying to to contribute using `yarn rwt link`

If you find an issue, please comment here - and please include if you found a way around the problem as well. The purpose of this issue being a reference, so you can get on with contributing 🚀

**Comment by dac09** [comment] 2021-04-05 12:48
After running link
:
```bash
Redwood folder already in gitignore
$ rimraf ./packages/**/dist
$ lerna run 'build:link' --parallel --dest /Users/dac09/Projects/tape-web/redwood
ERR! lerna Unknown argument: dest
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rwt link [RW_PATH]
```

**Solution**
Make sure your branch, in the redwood repo, is up-to-date with the latest code from main.

**Cause**
The rwt link command has changed slightly in between 0.29.x canary versions

**Comment by dac09** [comment] 2021-04-05 12:50
After running link:
```
error An unexpected error occurred: "expected workspace package to exist for \"XXX"".
```
Where `XXX` is some module.

**Solution**
Remove your `yarn.lock` file, and run `yarn install --force`

**Cause**
This happens when you've upgraded your redwood project using `yarn rw upgrade`, but the installation process didn't quite work properly, and your yarn.lock gets into a weird state.

**Comment by dac09** [comment] 2021-04-05 12:56
**How do I know if `rwt link` has succesfully linked my local redwood packages?**

#### Answer:
The way I check is if `node_modules/@redwoodjs` has symlinked packages

**Option 1: CLI** 
```
ls -la node_modules/@redwoodjs | grep "\->"
```
This will list all the packages that have been linked

**Option 2: macOS finder**
Navigate to `your_project/node_modules/@redwoodjs`

All the symlinked packages have little arrows next to the folder icon. In this example, core hasn't been linked (happens when your project is in canary)
![image](https://user-images.githubusercontent.com/1521877/113575960-95b44b80-9616-11eb-9a1d-c8c669d07042.png)

**Comment by dac09** [comment] 2021-04-05 19:05
### How do I link @redwoodjs/core in a canary project?

**Issue**
Only when running `rwt link` on Canary projects, the core package isn't linked and it continues to use the version specified in the package.json.

**Analysis**
This happens because yarn seems to ignore resolutions for packages under devDependencies. (Resolutions are added by rwt link).

**Solution**
We'll have to manually set the version of `@redwoodjs/core` in package.json e.g.

```diff
-  "@redwoodjs/core": "^0.28.5-canary.34",
+  "@redwoodjs/core": "^0.28.4",
```

The version we downgraded to is the same version as specified in the resolutions automatically added by rwt link.

Then re-run `yarn rwt link`. This isn't ideal, an alternative would be to use `yarn rwt copy` if you're mainly interested in changes to the core package, and your project has to be on canary.

**Comment by dthyresson** [comment] 2021-04-11 10:51
My main issue is that because my projects are in a Dropbox folder for instant backup and unfortunately they renamed my folder to be "Dropbox (Personal)" because a few years ago I liked my account with a business account because that's what they do even thought they note in the docs that this can break apps, I have issue with `rwt link` finding the path ... sometimes. 

It sometimes works and sometimes does but when it doesn't the project is left in a bad state.

```terminal
error An unexpected error occurred: "EINVAL: invalid argument, mkdir '/Users/dthyresson/Dropbox (Personal)/projects/app/node_modules/@redwoodjs/dev-server/node_modules'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dthyresson/Dropbox (Personal)/projects/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/Users/dthyresson/Dropbox (Personal)/projects/app/node_modules/execa/index.js:203
```

or I get

```
node_modules/.bin/rwt: No such file or directory
```

I could be that this fix https://github.com/redwoodjs/redwood/pull/1903 was rolled back in refactoring `rwt link`?

**Comment by dac09** [comment] 2021-04-23 19:40
## Issue
Yarn install fails during rwt link with the error:

```shell
error An unexpected error occurred: "expected workspace package to exist for \"xxxx"".
```

`xxx` could be a handful of modules - but commonly `@babel/cli`. 

This does not happen in _all_ projects, but can happen, typically after an upgrade.

## Solution
This is a very painful bug within yarn, and something to do wth yarn's resolution strategy. See here: https://github.com/yarnpkg/yarn/issues/7807

**Step 1: Remove all node_modules**
```
rm -rf node_modules api/node_modules web/node_modules
```

** Step 2: Set yarn policy**
```
yarn policies set-version 1.18.0
```

**Step 3: Reinstall node_modules**
```
yarn install
```

**Step 4: Re run link**
```
yarn rwt link [RW_PATH]
```

**Comment by jtoar** [comment] 2021-05-24 20:00
I just came across this (`node-gyp-build`, `yarn install --pure-lockfile --check-files` failed), and fixed it by installing node-gyp-build globally (`npm install -g node-gyp-build`):

```
[5/5] 🔨  Building fresh packages...
[1/21] ⠂ @prisma/engines
[2/21] ⠂ browser-tabs-lock
[3/21] ⠂ core-js
[4/21] ⠂ bufferutil
error /Users/dominicsaadi/projects/redwood/_sandbox/2609.callingmedic911:wrap-routes-with-set-in-scaffold/node_modules/bufferutil: Command failed.
Exit code: 127
Command: node-gyp-build
Arguments:




rwt link [RW_PATH]

Run your local version of redwood in this project

Options:
      --help     Show help                                             [boolean]
      --version  Show version number                                   [boolean]
  -c, --clean    Clean the redwood dist folders first. [boolean] [default: true]
  -w, --watch    Build and watch the supplied redwood repo
                                                       [boolean] [default: true]

Error: Command failed with exit code 127: yarn install --pure-lockfile --check-files
    at makeError (/Users/dominicsaadi/projects/redwood/_sandbox/2609.callingmedic911:wrap-routes-with-set-in-scaffold/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/dominicsaadi/projects/redwood/_sandbox/2609.callingmedic911:wrap-routes-with-set-in-scaffold/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.rwtLink [as handler] (/Users/dominicsaadi/projects/redwood/_sandbox/2609.callingmedic911:wrap-routes-with-set-in-scaffold/node_modules/@redwoodjs/cli/dist/redwood-tools.js:239:3) {
  shortMessage: 'Command failed with exit code 127: yarn install --pure-lockfile --check-files',
  command: 'yarn install --pure-lockfile --check-files',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
fish: Job 1, 'yarn rwt link &' has ended
```

**Comment by jacebenson** [comment] 2021-05-26 18:53
## Issue

When I run `yarn rwt link ~/Documents/GitHub/redwood-local/` I get this error.
```
'.\tasks\build-link' is not recognized as an internal or external command,
operable program or batch file.
```
I don't have a solution yet.

**Comment by LBrian** [comment] 2021-06-16 11:10
I got this error after upgraded to `0.33.3`, it was working perfectly before

![image](https://user-images.githubusercontent.com/3888780/122208956-4e381e80-cee7-11eb-839c-518d36d7b498.png)

**Comment by dac09** [comment] 2021-06-16 12:53
Hey @LBrian, this is likely due to the structural changes we're making to redwood at the moment. Steps to try and fix:

Assuming you've pulled main, and done a yarn install in the redwood folder:
- Make sure you don't have the `eslint-redwood-plugin` folder in your packages/ folder
- Change the dev dependency in your project from `redwoodjs/core` to `redwoodjs/cli` (this will be in the release notes)

**Comment by LBrian** [comment] 2021-06-17 03:45
> Hey @LBrian, this is likely due to the structural changes we're making to redwood at the moment. Steps to try and fix:
> 
> Assuming you've pulled main, and done a yarn install in the redwood folder:
> 
> * Make sure you don't have the `eslint-redwood-plugin` folder in your packages/ folder (in the framework repo)

The issue is resolved by running in both `redwoodjs/redwood` and `my-rr-app` folders then `yarn` again
```terminal
git clean -dfx -e .env
```

**Comment by LBrian** [comment] 2021-06-17 07:39
Following up 👆, `yarn rwt unlink` doesn't seem to clean up properly, `redwood/` `yarn.lock` and `package.json` are retained,  👇 result after unlink

<img width="1248" alt="Screen Shot 2021-06-17 at 5 32 09 pm" src="https://user-images.githubusercontent.com/3888780/122352792-c7d91680-cf92-11eb-9a61-c4a8b9a3940a.png">

**Comment by thedavidprice** [comment] 2021-06-17 15:46
@dac09 @peterp Since the behavior of link was changed to no longer use Yarn Workspace, is it possible that `rwt unlink` is no longer working correctly?

**Comment by dac09** [comment] 2021-06-17 15:47
It's just that the paths we link to has changed. It won't be an issue if your project is v0.34 or higher

**Comment by dac09** [comment] 2021-06-18 11:57
`rwt link` fails due to type issue
```
packages/api/src/logger/index.ts:353:30 - error TS7053: Element implicitly has an 'any' type because expression of type '"_clientVersion"' can't be used to index type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>'.
      Property '_clientVersion' does not exist on type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>'.

353     prisma: { clientVersion: config.db['_clientVersion'] },
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/api/src/logger/index.ts:358:21 - error TS2345: Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.

358       config.db.$on(level, (queryEvent: QueryEvent) => {
                        ~~~~~

packages/api/src/logger/index.ts:372:21 - error TS2345: Argument of type '"info" | "warn" | "error"' is not assignable to parameter of type '"beforeExit"'.
  Type '"info"' is not assignable to type '"beforeExit"'.

372       config.db.$on(level, (logEvent: LogEvent) => {
                        ~~~~~
```

### Solution
This happens when the prisma types go out of sync for some reason. 

Steps to resolve:
1. Make sure you've pulled the latest code for the framework `git pull origin main`
2. In your framework repo run 
```
git clean -dfx -e .env
```
3. Reinstall node_modules
```
yarn install
```

**Comment by thedavidprice** [comment] 2021-10-18 22:26
We have replaced `rw link` with `rwfw`. Closing this out.

**Closed by thedavidprice** 2021-10-18 22:26 UTC
Labels: good first issue, topic/ops-&-contributing-dx, hacktoberfest
