### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1829] opened 2021-02-21 23:18 UTC
Running the line `yarn rw prisma migrate dev`  (see [Tutorial Migrations](https://redwoodjs.com/tutorial/getting-dynamic#migrations)) on the most current version of RedwoodJS (0.25.1) on Windows, I got 

![image](https://user-images.githubusercontent.com/2712405/108641931-16a4f280-7470-11eb-9622-54b1d4b8ba42.png)

The same error appears for AboutPage, HomePage, BlogLayout
```
`  ● Test suite failed to run

    Cannot find module '~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js'

    Require stack:
      node_modules/@redwoodjs/testing/dist/MockProviders.js
      node_modules/@redwoodjs/testing/dist/customRender.js
      node_modules/@redwoodjs/testing/dist/index.js
      web/src/layouts/BlogLayout/BlogLayout.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/dist/MockProviders.js:32:5)
```

In addition, I also get
```
'scenario' is defined but never used. Allowed unused args must match /^_/u.
```

Windows 10, node v12.19.0, yarn 1.22.5, RedwoodJS 0.25.1

Sorry for not feeling up to debug this and provide PR (very weak on testing 😢 )

**Comment by jvanbaarsen** [comment] 2021-02-22 08:06
@adriatic Hi there 👋,

No problem on not debugging this, submitting the issue is already super helpful! Without it we wouldn't be aware of the problem existing.

Would it be possible to show the code of the `posts.test.js`? Looking at the errors it says "Test suite failed to run", but the command you showed is about migrating. Can it be that the output is from running tests? And if so, what is the command you're using to run the tests?

**Comment by adriatic** [comment] 2021-02-22 15:07
Hello, @jvanbaarsen 

I was not near running any tests - these errors appeared as a consequence of running the command `yarn rw prisma migrate dev` (see the first sentence in my [original report](https://github.com/redwoodjs/redwood/issues/1829#issue-812978271)). 

Here is the code you asked for
```
import { posts, post, createPost, updatePost, deletePost } from './posts'

describe('posts', () => {
  scenario('returns all posts', async (scenario) => {
    const result = await posts()

    expect(result.length).toEqual(Object.keys(scenario.post).length)
  })

  scenario('returns a single post', async (scenario) => {
    const result = await post({ id: scenario.post.one.id })

    expect(result).toEqual(scenario.post.one)
  })

  scenario('creates a post', async (scenario) => {
    const result = await createPost({
      input: { title: 'String', body: 'String' },
    })

    expect(result.title).toEqual('String')
    expect(result.body).toEqual('String')
  })

  scenario('updates a post', async (scenario) => {
    const original = await post({ id: scenario.post.one.id })
    const result = await updatePost({
      id: original.id,
      input: { title: 'String2' },
    })

    expect(result.title).toEqual('String2')
  })

  scenario('deletes a post', async (scenario) => {
    const original = await deletePost({ id: scenario.post.one.id })
    const result = await post({ id: original.id })

    expect(result).toEqual(null)
  })
})
```
My sense is that this is a Windows-specific issue as it is very unlikely that such problem would not be caught by someone already.

**Comment by tctrautman** [comment] 2021-02-24 20:22
Unfortunately I'm unfamiliar with MockProviders and I develop on a macbook, so I can't be of much help with your main question 😞 

But I believe that this error...:
```
'scenario' is defined but never used. Allowed unused args must match /^_/u.
```
...is being caused by 'creates a post' in your tests above, and should be fix-able by either removing the `scenario` argument in your test callback, or by renaming it to `_`.

**Comment by adriatic** [comment] 2021-02-24 20:33
I respectfully disagree Tim (@tctrautman), because my original [issue report](https://github.com/redwoodjs/redwood/issues/1829#issue-812978271) describes the failure taking place in the context of running a tutorial **setting** the first migration (`yarn rw prisma migrate dev`) **up**, and that used to work before last redwood update

**Comment by thedavidprice** [comment] 2021-03-03 18:03
Hi @adriatic this is a strange one. Unfortunately, I'm not quite following the chain of events.

**To Confirm:**
You ran `yarn rw prisma migrate dev`. 
  - This Prisma CLI command will 1) generate the Prisma Client, 2) create a new Prisma Migration (if applicable), and 3) apply the Migration to your local DB and/or confirm it's up-to-date
  - This has no interaction with Jest

In your terminal console, I'm assuming you saw a "success" message, correct?

**Jest Problems**
  - When and where did you first notice the Jest warnings/error in the "Problems" tab from your screenshot above?
  - Related, had you previously run `yarn rw test`? (This is the Redwood CLI command that runs Jest (along with other tooling) under the hood.)

If you had not run the Test command, `yarn rw test`, I'm very curious as to what would happen when/if you did.

> Note: if you run `yarn jest` standalone, you'll get all kinds of errors. Jest configuration is, well, SuperHard™ and took us about 6 months to get working across API <> Web accounting for test DB, mocks, routing, etc. Just painful. My naive hunch here is that you might have something in the background or debugging that's not integrated correctly.

> If you're interested, here's the soon-to-be-launched Redwood Doc on testing. Head up! It's 8,000+ words... 😬
> https://github.com/redwoodjs/redwoodjs.com/pull/530

**Comment by adriatic** [comment] 2021-03-04 16:48
@thedavidprice there are several red herrings (of my creation) in this issue [Test suite failed to run #1829](https://github.com/redwoodjs/redwood/issues/1829). Since the [issue 1887](https://github.com/redwoodjs/redwood/issues/1887) is late discovered replica of **1829**, and still contains the history of subsequent discoveries, I created the **[summary](https://github.com/redwoodjs/redwood/issues/1887#issuecomment-790755216)** of all that is still relevant and needs to be fixed

**Comment by adriatic** [comment] 2021-04-12 15:40
@thedavidprice 

I understand **[my report on various tests failing](https://github.com/redwoodjs/redwood/issues/1829)** better now, so I am responding to your **[comments above](https://github.com/redwoodjs/redwood/issues/1829#issuecomment-789941185)** providing more details:

Let's use the error message:

`~__REDWOOD__USER_ROUTES_FOR_MOCK' from 'node_modules/@redwoodjs/testing/dist/MockProviders.js` 

as a representative of the whole class of errors describing failed tests like `Scenario is not defined` etc.)

I should have mentioned that  I am using VSCode for  all of my work on writing docs and samples. Consequently all my problem reports regarding failed Jest testing  are caused by not providing the required settings to VSCode (see **[Jest Orta](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest)**

I am writing the detailed instructions on how to use Jest running under VSCode supervision on [here](https://github.com/redwoodjs/redwoodjs.com/wiki/Testing)

**Comment by thedavidprice** [comment] 2021-04-12 22:50
> Consequently all my problem reports regarding failed Jest testing are caused by not providing the required settings to VSCode

^^ ah, very interesting indeed. And 100% solvable! (Correct?)

> I am writing the detailed instructions on how to use Jest running under VSCode supervision on here.

^^ Nice! This seems like a very good idea. Frankly, we haven't explored this area much at all, so I don't have visibility into both 1) what users are trying and need to do and 2) if, given current codebase + config, they are able to do so.

## Some background
Integrating Jest (and the other test libraries) across the front-to-back end, with a test DB, with Cells, and with the Redwood Router was no small undertaking. This code (for the command `yarn rw test`) reveals how things are wired together under the hood:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/test.js

Although this makes it possible to initiate a setup process and pass necessary config, in its current form, it also makes some assumptions about use-case and blocks using other available Jest options or targeting a specific test file or directory (for example). We know improvements need to be made, but we have yet to define the use-case(s) and requirements.

Here's related an open Issue about being able to target a specific file:
https://github.com/redwoodjs/redwood/issues/1812

I think Peter is closest to the ultimate desired behavior in [this comment](https://github.com/redwoodjs/redwood/issues/1812#issuecomment-781845845). It's more complex than `rw test ...` being a simple wrapper that passes config. But it's conceivable to accept Jest options and target tests other than the web or api directories.

**Comment by adriatic** [comment] 2021-04-12 23:50
Hello, @thedavidprice 

I am very relieved after making the discovery that all the issues reported by VSCode are extremely simple to address by providing some additional settings to the set created (by the `redwood_app` utility)

![image](https://user-images.githubusercontent.com/2712405/114476220-d76d6500-9bc7-11eb-832f-63a954b9493a.png)

These settings will ensure the VSCode default behavior to start **running the tests** as soon as the application is "opened" in VSCode - even before the `node_modules` folder is created.

**Comment by thedavidprice** [comment] 2021-04-13 01:36
That's great to hear! Do you know what those setting should be? Or are you still confirming? Either way, let's get it updated!

Here's the current installation template settings file:
https://github.com/redwoodjs/redwood/blob/0dd5ff3f5f8a5645c434b359da00cda07759ed28/packages/create-redwood-app/template/.vscode/settings.json#L1-L11

**Comment by adriatic** [comment] 2021-04-13 01:45
> Here's the current installation template settings file:

Did you notice that the settings you just cited are the same as shown on **[the screenshot above](https://github.com/redwoodjs/redwood/issues/1829#issuecomment-818316023)**?

Ah, I know - you copied them to show me where these templates are kept, so I can create a PR, right? I will do that once I verify that all tests in a large sample work correctly.

**Comment by thedavidprice** [comment] 2021-04-13 02:30
> Ah, I know - you copied them to show me where these templates are kept, so I can create a PR, right? I will do that once I verify that all tests in a large sample work correctly.

Yes, just for reference. And I can help either way. Keep me posted as/if needed.

**Comment by adriatic** [comment] 2021-04-13 20:14
@thedavidprice I need a good advice from you: how to handle the discussion on VSCode settings that would result with responses by anyone using VSCode on either of the three supported OSes?.

My inclination would be to use [Discussions and Questions](https://community.redwoodjs.com/c/discussions-questions/1) despite my pretty slim set ot response to most of my posts. This would be my first plea for answers that affect everyone - as VSCode should be used ahead of any other tools (this is just my opinion and I will not make such claim in that post - people are very protective of their own choices for development tools.

**Comment by thedavidprice** [comment] 2021-04-14 00:21
@adriatic Thank you for this question. Visibility and feedback are important (and hard) as this project picks up speed and there's continual incoming. One individual I'd suggest you watch and ask for advice is @dthyresson He's done a great, patient, sustained job working from RFC to Forum Post to Draft PR to escalating to Core Team several times now (and on repeat).

If you want to experiment and iterate, here are some patterns you can try (if not try all):
1. Start with an RFC Issue: in brief, outline the problem and proposed solution. Also outline the questions you have and areas where you need some help. Don't expect comments or replies. Just keep moving!
2. Next, create a Draft PR. This community responds very well to working examples. And a draft PR branch can be "checked-out" and iterated on by others. Think of it as a way to collaboratively sketch. The point isn't necessarily getting it merged as much as it is communicating and iterating.
3. Then create a simple Forum post with a request for help. Ask people in the community to help out by testing the PR code (link back to the PR). Also ok to post the link in Discourse

Each step of the way, here are some tips:
- Titles matter: keep them specific and focused on keyword. If there's an "action" involved, like "Help wanted", include that as well
- Target an audience: you might need to say "I'm looking for Windows devs using VS Code". Or, "requesting help from people who are using VS Code debugging". 
- Leave a breadcrumb -- link between the posts across platforms to create connections people can follow
- Know your context: GitHub needs to be more Problem/Solution precise, The Forum is better for long-form, etc.
- Nudge people: give it some time, but do nudge a person or two who would be "lead" on the topic. The best way to nudge is via a PR

Any other thoughts, @dthyresson?

**Comment by adriatic** [comment] 2021-04-14 02:17
Great workflow @thedavidprice. While I would be less formal in my "native" mode, I really like your introduction into Redwood culture and expected communications. I particularly like two sentences:

> One individual I'd suggest you watch and ask for advice is @dthyresson He's done a great, patient, sustained job working from RFC to Forum Post to Draft PR to escalating to Core Team several times now (and on repeat)

@dthyresson would be my choice had you not proposed him, so let's hope that he would not mind being my RW communications protocol adviser

**Closed** 2021-12-17 18:44 UTC
Labels: bug/needs-info, topic/windows, topic/testing, v1/for-consideration

**Comment by jtoar** [comment] 2021-12-17 20:44
@adriatic I'm trying to clean up some of the long-standing issues in the repo. There's been several updates to scenarios, testing, and mocks since this issue was opened in February, so I feel like this has been addressed. But please do feel free to re-open this if you feel like it's still a problem and we'll prioritize sorting it out before v1.

**Comment by adriatic** [comment] 2021-12-18 22:30
@jtoar My memory is very vague (this thread seems like a few centuries old), but my affection for Redwood is not diminished. I appreciate that you did not sweep this under the carpet, so I will switch all my work to this immediately.

I will reopen this if in my current testing this issue I find this problem being still present. Stay tuned please.

**Comment by adriatic** [comment] 2021-12-19 02:48
Before I dive in, I would like to understand the relevance of this issue, and mode globally, the relevance of my participation. Is this just a last cleanup before release, or do you care about all of my findings? A year ago, I gradually drifted away from Redwood, as I felt that my comments were largely irrelevant my this team's opinion

I just freshly installed all the "things" needed to build and run the the [basic tutorial])(https://learn.redwoodjs.com/docs/tutorial/prerequisites) and just in the process of compiling and building the very first page of this blog, found many instances of using  E6 version without declaring it like

![image](https://user-images.githubusercontent.com/2712405/146661763-f09a0c1c-6e4a-43bb-bf21-7517105105c2.png)
 
many syntactical errors, resulting in the prompt to install jshint (it should be on the list of recommended extensions), many lines without semicolon as the terminator etc.

Here I am using my MacBook Pro (the last version with Intel processor), as I was hoping that OSX environment would be closer to the environment used by most of the Redwood folks. So, I expected less of such trivial errors, and would rather not chase them all if that is not expected from me in this case.

**Comment by adriatic** [comment] 2021-12-20 00:33
# Conclusion of my investigation

## It is safe to ignore this [whole thread](https://github.com/redwoodjs/redwood/issues/1829). 

I did run the actions that are presented there using the current Redwood and VSCode Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:37:28.172Z (4 days ago).

The problems indicated on the [initial image on that report](https://user-images.githubusercontent.com/2712405/108641931-16a4f280-7470-11eb-9622-54b1d4b8ba42.png) are caused by VSCode intent to run multiple tasks in parallel - so it tried to run at least a portion of the testing structure (note four test pages shown on that image).

Either the testing setups at the time of my running the tutorial 2 were incomplete, or VSCode got less ambitious with running parallel tasks - the tutorial sample up to and include [this section](https://learn.redwoodjs.com/docs/tutorial/getting-dynamic#migrations) behaves correctly

**Comment by thedavidprice** [comment] 2021-12-21 00:10
Thank you for taking the time to dust off this Issue and dive in @adriatic It is very helpful. Welcome back!

> Before I dive in, I would like to understand the relevance of this issue, and mode globally, the relevance of my participation. Is this just a last cleanup before release, or do you care about all of my findings?

We are (finally) triaging all outstanding Issues and assigning prioritizing for final 1.0.0 release. Had you found that some of these items were still relevant (i.e. not working), we would have definitely added to the priorities for v1.

We've just begun the process of triage. Here's the current working project board:
- [v1 Help Wanted](https://github.com/orgs/redwoodjs/projects/4)

Lastly, we are aware that VS Code isn't always working great with Redwood when it comes to things like debugging. The long-promised (and long silent) Redwood Extension is going to include full project debugging support. It's just not going to be available until well into 2022.

Anything else I missed?

**Comment by thedavidprice** [comment] 2021-12-21 00:13
Ah, just recalled two more things:
- there is currently a project in the works to re-write the Tutorial
- we have a PR with documentation for a recommended setup for Windows projects over here, which may be of interest to you: https://github.com/redwoodjs/redwoodjs.com/pull/922

**Comment by adriatic** [comment] 2021-12-21 03:32
Several comments to @thedavidprice  [writeup above](https://github.com/redwoodjs/redwood/issues/1829#issuecomment-998362160)

1. If the user has not installed jshint (I do not believe that Redwood VScode projects require that specifically) most of my "discoveries" like those shown on [this image](https://user-images.githubusercontent.com/2712405/146661763-f09a0c1c-6e4a-43bb-bf21-7517105105c2.png) will not appear. I would suggest to take this path as some of jshint complaints are quite difficult to address.
2. At this point, MacOS and Windows support [zsh](https://dev.to/zinox9/installing-zsh-on-windows-37em). With this in mind, the preferred development tools (VSCode and zsh shell) present the OS independent view of Redwood development environment.
3. I am still not sure that I know what is VSCode based Redwood debugging (the initial code is in Github, but it is not kept current and is difficult to understand. Until that gets done properly, I believe that the current set (VSCode, Chrome, React extension) are quite well integrated and works well together. Creating a complete Redwood VSCode extension will be better and more difficult to do.
4. Rewriting the Tutorial (textual version is quite nice) may be a difficult task as the current author is pretty resistant to changes.

**Comment by thedavidprice** [comment] 2021-12-23 15:14
Thanks (again) @adriatic! My replies to each are below. Also, I'm unplugging today for the Holidays; back January 3rd and in touch again after that time. Happy holidays to you and yours! 

1. Agreed 💯 We've had some challenges all along with VS Code and editors because we broke some of the editor rules in favor of developer experience design choices. You'd identified the tension points with this example (i.e. Jshint complaints). Long-term our solution would be to resolve via extension or the like. Just going to take time, but we'll get there!
2. Yes, it's been nice to see how the tooling across OS's is becoming consistent. Not sure if you've explored them yet, but VS Code plus virtual IDEs like [GitHub CodeSpaces](https://github.com/features/codespaces) and [GitPod](https://www.gitpod.io/) are going to be a boon for us to help people get started without any local setup required 🤯
3. You nailed it. People trying to debug in VS Code are running into all kinds of challenges. But browser + console + extensions are working good enough (for now). On the VS Code extension front, Aldo did demo an early version of debugging that worked for both Redwood projects _and_ the framework development! I just don't think we'll see this released until mid 2022.
4. Ha! Well, the good news is that the project is well under way over here (https://github.com/redwoodjs/learn.redwoodjs.com/pull/173). One of the previous challenges we had was effectively breaking the tutorial with major changes each time we released. Now that we're at the v1-rc stage, we're feature complete (for v1) and holding any potential breaking changes.

**Comment by adriatic** [comment] 2021-12-25 17:09
Hello, @thedavidprice! a few comments to your comments [above](https://github.com/redwoodjs/redwood/issues/1829#issuecomment-1000368027):

1. On `jshint`:  the list of complaints is a couple of pages long and most of them if not all are the violations of the rule "state that you are intentionally using E6 and E7 features. In other words, you need to add jshint in addition to eslint to the list of required modules.
2. Thanks for the GitPod references; regardless of how hard I am trying to stay current, just this small segment of JavaScript is expanding faster than I can follow.3
3. I am pretty close to the point where I can do everything needs using only VSCode (including its internal terminals), with the exception of debugging, where I am using Chrome / Firefox Developer Tools. That exception is (I believe so) the area Aldo is/was working on and I could be interested in doing that - if my interest in Remix does not prevail
4. The tutorials development is another interest of mine, that I am flirting with, as it needs another breakthrough - the mapping between the spoken words and the repository with the actual text of the code.
