### ISSUE TITLE
[Bug?]: Scenarios broken with redwood 7

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#10068] opened 2024-02-27 09:00 UTC
### What's not working?

We have some tests that fail after the update to redwood 7.

It seems, like "sub objects" in scenarios only get created some times and not every time as expected.

### How do we reproduce the bug?

- Checkout https://github.com/razzeee/my-redwood-scenario-repro
- Run `yarn`
- Run `yarn rw test api`

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - /tmp/xfs-e5f62a34/node
    Yarn: 4.1.0 - /tmp/xfs-e5f62a34/yarn
  Databases:
    SQLite: 3.42.0 - /usr/bin/sqlite3
  npmPackages:
    @redwoodjs/core: 7.0.3 => 7.0.3 
    @redwoodjs/project-config: 7.0.3 => 7.0.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by ahaywood** [comment] 2024-02-27 17:30
@razzeee Thanks for taking the time to submit the bug. Our team will take a look and get back with you ASAP.

**Comment by cjreimer** [comment] 2024-02-28 18:49
I am running into some similar issues with api side testing as well.  When I get the error, it looks like:

```
 PrismaClientKnownRequestError:
    Invalid `getProjectDb()[model].create()` invocation in
    D:\CENGYS\Dev\cengys-r\node_modules\@redwoodjs\testing\config\jest\api\jest.setup.js:193:64

      190 scenarios[model] = {}
      191 for (const [name, createArgs] of Object.entries(namedFixtures)) {
      192   if (typeof createArgs === 'function') {
    → 193     scenarios[model][name] = await getProjectDb()[model].create(
    Unique constraint failed on the fields: (`code`)

      at ai.handleRequestError (node_modules/@prisma/client/runtime/library.js:126:6775)
      at ai.handleAndLogRequestError (node_modules/@prisma/client/runtime/library.js:126:6109)
      at ai.request (node_modules/@prisma/client/runtime/library.js:126:5817)
      at l (node_modules/@prisma/client/runtime/library.js:131:9709)
      at seedScenario (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:193:36)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:106:28)
```

Note that `code` is a field in the model that is typically created in each scenario, both for test files that run and test files that fail.  

The situations that seem to generate the incorrect teardown are related to a test failing.  After a test fails, all subsequent `scenario` tests fail with the above error.  I'm thinking, but have not proven, that a failing test doesn't teardown correctly.

@razzeee Does your experience match mine, that failing tests initiate this, or is your experience different?

I guess the fix for me is to not allow any test to fail 😄 !

**Comment by cjreimer** [comment] 2024-02-28 18:54
I'll add that I could be somewhat to blame for this bug as I tested #9866 before it was merged.  If this is due to that PR, then obviously I missed something!

**Comment by cdubz** [comment] 2024-02-28 21:00
We have also been experiencing this and it does seem to stem from #9866 -- _using_ the new `describeScenario` function seems to resolve the issue. And it also affects some tests but so far I haven't been able to tell exactly what it is that triggers it.

**Comment by cdubz** [comment] 2024-02-28 21:06
Here's an example of a change I made on a recent commit for what was mostly the basic generated tests on the model --

```diff
diff --git a/api/src/services/pbsShows/pbsShows.test.ts b/api/src/services/pbsShows/pbsShows.test.ts
index 494be58d..5e6bcbdf 100644
--- a/api/src/services/pbsShows/pbsShows.test.ts
+++ b/api/src/services/pbsShows/pbsShows.test.ts
@@ -15,20 +15,26 @@ import type { StandardScenario } from './pbsShows.scenarios'
 //       https://redwoodjs.com/docs/testing#testing-services
 // https://redwoodjs.com/docs/testing#jest-expect-type-considerations
 
-describe('pbsShows', () => {
-  scenario('returns all pbsShows', async (scenario: StandardScenario) => {
+describeScenario<StandardScenario>('pbsShows', (getScenario) => {
+  let scenario: StandardScenario
+
+  beforeEach(() => {
+    scenario = getScenario()
+  })
+
+  it('returns all pbsShows', async () => {
     const result = await pbsShows()
 
     expect(result.length).toEqual(Object.keys(scenario.pbsShow).length)
   })
 
-  scenario('returns a single pbsShow', async (scenario: StandardScenario) => {
+  it('returns a single pbsShow', async () => {
     const result = await pbsShow({ id: scenario.pbsShow.one.id })
 
     expect(result).toEqual(scenario.pbsShow.one)
   })
 
-  scenario('creates a pbsShow', async () => {
+  it('creates a pbsShow', async () => {
     const result = await createPbsShow({
       input: {
         pbsId: 'e9b2bb97-4d38-46f5-a229-6b79b04fd45f',
@@ -53,7 +59,7 @@ describe('pbsShows', () => {
     expect(result.fetchedAt).toEqual(new Date('2023-11-15T23:14:49.140Z'))
   })
 
-  scenario('updates a pbsShow', async (scenario: StandardScenario) => {
+  it('updates a pbsShow', async () => {
     const original = (await pbsShow({ id: scenario.pbsShow.one.id })) as PbsShow
     const result = await updatePbsShow({
       id: original.id,
@@ -67,7 +73,7 @@ describe('pbsShows', () => {
     expect(result.pbsId).toEqual('30b3f373-027b-4acb-acd6-9c81b951d54c')
   })
 
-  scenario('deletes a pbsShow', async (scenario: StandardScenario) => {
+  it('deletes a pbsShow', async () => {
     const original = (await deletePbsShow({
       id: scenario.pbsShow.one.id,
     })) as PbsShow
```

It seems like something about the scenario configuration triggers the issue? Here's what the scenarios look like for that test (in case this is reproducible) --

```ts
import type { Prisma, PbsVideo } from '@prisma/client'
import { VideoType } from '@prisma/client'

import type { ScenarioData } from '@redwoodjs/testing/api'

export const standard = defineScenario<Prisma.PbsVideoCreateArgs>({
  pbsVideo: {
    one: {
      data: {
        pbsId: '497feb71-70c1-490f-b499-fe34ab76c226',
        slug: 'String8872097',
        videoType: VideoType.EPISODE,
        title: 'String',
        shortDescription: 'String',
        longDescription: 'String',
        duration: 3249892,
        pbsUpdatedAt: '2023-11-15T23:14:38.190Z',
        fetchedAt: '2023-11-15T23:14:38.190Z',
        pbsShow: {
          create: {
            pbsId: 'eabe93d9-08b2-48e8-9a64-2686cc7b23e4',
            slug: 'String7036656',
            title: 'String',
            descriptionShort: 'String',
            descriptionLong: 'String',
            pbsUpdatedAt: '2023-11-15T23:14:38.190Z',
            fetchedAt: '2023-11-15T23:14:38.190Z',
            show: { create: {} },
          },
        },
        video: {
          create: {
            show: { create: {} },
          },
        },
      },
    },
    two: {
      data: {
        pbsId: 'e3fbdeb3-3887-4b92-ab49-76ee093cb674',
        slug: 'String5427265',
        videoType: VideoType.EPISODE,
        title: 'String',
        shortDescription: 'String',
        longDescription: 'String',
        duration: 7666188,
        pbsUpdatedAt: '2023-11-15T23:14:38.190Z',
        fetchedAt: '2023-11-15T23:14:38.190Z',
        pbsShow: {
          create: {
            pbsId: 'c585e262-2a1c-4095-9a92-45d8059c376e',
            slug: 'String9235462',
            title: 'String',
            descriptionShort: 'String',
            descriptionLong: 'String',
            pbsUpdatedAt: '2023-11-15T23:14:38.190Z',
            fetchedAt: '2023-11-15T23:14:38.190Z',
            show: { create: {} },
          },
        },
        video: {
          create: {
            show: { create: {} },
          },
        },
      },
    },
  },
})

export type StandardScenario = ScenarioData<PbsVideo, 'pbsVideo'>
```

**Comment by razzeee** [comment] 2024-02-28 23:04
> @razzeee Does your experience match mine, that failing tests initiate this, or is your experience different?

No, our tests were running just fine on v6 (or still are, as we haven't updated due to this yet)
But they fail with v7

**Comment by peraltafederico** [comment] 2024-02-29 01:15
I also noticed that if any test fails, the data in the database is not deleted or recreated, but only an attempt is made to create it again. This leads to a failure if your entity has a unique field like a `name` column. See my case

```
defineScenario({
  organization: {
    one: {
      data: {
        name: 'abc',
      },
    })
```
When a single test fails, subsequent tests will also fail with this error:

```

    PrismaClientKnownRequestError: 
    Invalid `getProjectDb()[model].create()` invocation in
    /home/federico/Documents/projects/platform/node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:197:64

      194     createArgs(scenarios)
      195   )
      196 } else {
    → 197   scenarios[model][name] = await getProjectDb()[model].create(
    Unique constraint failed on the fields: (`name`)

      at ai.handleRequestError (node_modules/@prisma/client/runtime/library.js:126:6775)
      at ai.handleAndLogRequestError (node_modules/@prisma/client/runtime/library.js:126:6109)
      at ai.request (node_modules/@prisma/client/runtime/library.js:126:5817)
      at l (node_modules/@prisma/client/runtime/library.js:131:9709)
      at seedScenario (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:197:36)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:106:28)

```

This, as I said, is because `name` is a `unique` SQL column.

**Comment by dac09** [comment] 2024-03-02 11:04
Thanks all for the info, very likely related to the `describeScenario` change. Will dig into this shortly! :)

**Comment by dac09** [comment] 2024-03-05 06:03
Hey all, looking into this issue, but @razzeee your repro doesn't seem to pass tests on 6.6.4 either unfortunately! 

```
    Received promise rejected instead of resolved
    Rejected to value: [PrismaClientKnownRequestError:·
    Invalid `db.seat.delete()` invocation in
    /Users/dac09/Experiments/my-redwood-scenario-repro/api/src/services/seats/seats.ts:50:24·
      47   throw new Error("Seat can't be deleted as it has history")
      48 }
```

Any chance you could update the reproduction please? I'm looking to isolate whtat the problem is here first.

--- 

@cdubz, @cjreimer - wouldn't mind testing against your models either. I'll try and re-create the simple one here https://github.com/redwoodjs/redwood/issues/10068#issuecomment-1969916767

**Comment by razzeee** [comment] 2024-03-05 14:36
@dac09 Will need to downgrade that solution then, it's still working fine with that code in our production repo.

You can make the test faliing test `seats › deleteSeat - still active - do not delete` pass, when you comment out the other scenarios in that file, which seems pretty telling

**Comment by dac09** [comment] 2024-03-05 14:52
Yep yep, did downgrade to 6.6.4! 

The failing test use case is in PR - just wondering if there's something else too.

**Comment by razzeee** [comment] 2024-03-05 15:09
I do see that too, when downgrading the repro repo. I even tried copying yarn.lock and all package.json then installing with a frozen lockfile. Still no dice, still failing. So unsure, what's different.

I had another issue with v6, where it broke all of a sudden seemingly due to changes to v7, so I'm a bit cautious, if there is some dependency locking problem going on.

**Closed** 2024-03-06 06:40 UTC
Labels: bug/confirmed, topic/testing

**Comment by dac09** [comment] 2024-03-06 06:45
Thank you all for the input, and the reproduction! 

PR merged, will be released in a patch soon - hope this resolves the issue for you guys. If not feel free to re-open the issue.

**What does it solve?** Best described above by Curtis
> The situations that seem to generate the incorrect teardown are related to a test failing. After a test fails, all subsequent scenario tests fail with the above error. I'm thinking, but have not proven, that a failing test doesn't teardown correctly.

Note @razzeee looking more carefully at your code, I think maybe in the reproduction you have some logic with seat history that makes your tests fail. I believe this is not really related - just application logic, or copy pasted wrong :) - regardless hopefully the above fix will let you upgrade your real app.

**Comment by razzeee** [comment] 2024-03-11 13:28
I'm still seeing this problem, this did not solve anything for us.

> Note @razzeee looking more carefully at your code, I think maybe in the reproduction you have some logic with seat history that makes your tests fail. I believe this is not really related - just application logic, or copy pasted wrong :) - regardless hopefully the above fix will let you upgrade your real app.

Could be copied wrong. Fact is, it worked with v6 and it stopped working in our (unmerged) PR of v7. (I even think it worked with the RC first, but probably not helpful)

And I also don't think it's related to a timeout, gut feeling is, that it's due to the exceptions being thrown and us testing that.
