### ISSUE TITLE
v34.1 UnhandledPromiseRejectionWarning on generating types

### ISSUE THREAD

**Issue by cjreimer** [redwoodjs/redwood#2964] opened 2021-07-05 02:17 UTC
After upgrading to v34.1, I started getting the following console error upon generating types:

```
(node:33336) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "}" (13:28)      
    at Object._raise (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:776:17)
    at Object.raiseWithData (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:769:17)     
    at Object.raise (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:737:17)
    at Object.unexpected (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:9735:16)       
    at Object.expect (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:9721:28)
    at Object.jsxParseExpressionContainer (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:5028:10)
    at Object.jsxParseElementAt (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:5119:36)    at Object.jsxParseElement (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:5162:17)  
    at Object.parseExprAtom (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:5169:19)    
    at Object.parseExprSubscripts (D:\CENGYS\Dev\cengys-r\node_modules\@babel\parser\lib\index.js:10708:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
```

I checked, and this is specific to my project, and a simple test project would not generate this error. Unfortunately, no clues were provided in the above log as to which file in my code generated the error, so I added a bunch of console.log statements into the redwood framework until I tracked it down to the following lines of redwoodjs code, which calls babel traverse.
```
export const hasDefaultExport = (code: string): boolean => {
  let exported = false
  const ast = parse(code) as types.Node
    traverse(ast, {
      ExportDefaultDeclaration() {
        exported = true
        return
      },
    })
  return exported
}
```

The offending code in my project was:

```
  const from = await user({ id: <number>submittal.fromId })
  const to = await user({ id: <number>submittal.toId })
```
Note that this code worked in all other respects.  Changing the code to the following resolved the problem.

```
 const from = await user({ id: submittal.fromId as number })
 const to = await user({ id: submittal.toId as number })
```

So, this appears to be a babel traverse issue and not super-critical, as once found, it can easily be fixed.  
However, how could we make things easier for someone to find the offending code that causes babel to puke?  In my case, I had to edit the framework to find the error.  As this appears to be related to asynchronous code in babel, a simple try-catch block in the function does not appear to work.   

The only idea I have is to add a verbose flag to the generate types command so that it spits out filenames to the console as they are processed.

@peterp, any thoughts or suggestions?

**Comment by thedavidprice** [comment] 2021-07-06 23:30
@dac09 any thoughts about this? And or suggestions about how to prioritize for triage?

Thanks, all!

**Comment by dac09** [comment] 2021-07-06 23:41
Certainly worth looking into - I'd have to look into it further before I could make any suggestions 🙊

I think definitely pre-v1 have a fix for this, if nothing else to atleast have the better error message that @cjreimer is suggesting. 

Happy to pick this up as soon as I can.

**Comment by dac09** [comment] 2021-07-28 15:42
@cjreimer - any chance I could get more details on how to recreate this error please? i.e. could you give me a snippet and what file you have it in (I assume a Cell?)

**Comment by cjreimer** [comment] 2021-07-28 15:53
@dac09 - here's the entire `submittalMail.ts` file.  It is a service on the api side and calls the user service to get a specific user.  I checked and the code still generates the same error in redwood v0.35.2.  Easily fixed once found, but the error, as indicated in the previous post, doesn't give any clues as to which file it is in.

```
import { sendMail } from 'src/lib/sendmail'
import { user } from 'src/services/users/users'
import { BeforeResolverSpecType } from '@redwoodjs/api'

export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.skip()
}

export const submittalNewMail = async (submittal: Record<string, unknown>) => {
  const from = await user({ id: <number>submittal.fromId })
  const to = await user({ id: <number>submittal.toId })
  const toEmail = to.email as string

  const message = `<h1>New submittal: ${submittal.id}</h1><span>from ${from.nameFirst} ${from.nameLast}</span>
  View this submittal at http://localhost:8910/submittal/${submittal.reqId}`
  const msg = {
    to: toEmail, // Change to your recipient
    subject: 'WTP PLC Upgrades: New Submittal',
    html: message,
  }
  sendMail(msg)
}

```

**Comment by Tobbe** [comment] 2021-08-04 14:18
@dac09 I was going through my emails and found this one. So just a gentle nudge to not forget about it 🙂

**Comment by peterp** [comment] 2021-08-10 18:40
Hey there, sorry about the delay in response here.

The issue here is that your syntax is incorrect. 

`.ts` files can use the `<AngleBracket>` type assertions, but it conflicts with the JSX grammar. So TypeScript added the `.tsx` extension and `varName as Type` syntax. (Here's a more detailed answer: https://stackoverflow.com/a/54614279/200516)

I'm not sure why VSCode isn't giving you an error here!

_@Tobbe @dac09 Please double check me on this, I discovered this piece of TypeScript trivia when I was reading about what the TypeScript team was considering doing with the new `.mjs` | `.mts` extension._

**Comment by dac09** [comment] 2021-08-10 19:03
I think the casting syntax is valid @peterp - the example is a service file, not a component.

**Comment by cjreimer** [comment] 2021-08-10 19:04
Hey @peterp !  Thanks for the comments and typescript trivia!  I appreciated it! 

Just a note, my concern is not with the typescript code, but that `yarn rw gen types` threw an error without a file reference.  Can redwood spit out the filename upon such an error?

Thanks!

**Comment by peterp** [comment] 2021-08-10 20:05
@cjreimer Ah! I see that I didn't read the entire thread properly! I just assumed it was a file that contained JSX. @dac09 has created a PR that spits out the filename!

@dac09:
I still think the reason why it's failing is because of the type cast/ grammar issue... I can't think of any other logical reason why this syntax would be invalid. My hunch is that we're not giving our parsing code enough information to figure out which syntax should be supported. 

https://github.com/redwoodjs/redwood/blob/c7823480e5313348c0372b355af7c69779656585/packages/internal/src/ast.ts#L5-L6

The options part of babelParse allows you to specify the `sourceFilename`, which may kick the mechanism in the right direction. I'll create a reproduction of this issue in a test as a reference point.

**Comment by cjreimer** [comment] 2021-08-10 20:22
Thanks, @peterp, and @dac09 !  You guys are awesome!

**Comment by peterp** [comment] 2021-08-10 20:31
I've created #3226 with the failing test case - I tried a few things to make it comply - none were helpful:

```ts
parse(code, {
      sourceFilename: 'test.ts',
      createParenthesizedExpressions: true,
      errorRecovery: true,
    })
```

I think we should create an issue on the babel repo, and we should catch the `SyntaxError` errors in the `generate.ts` file and surface those to the users in a nice way.

@cjreimer the `as number` syntax works fine in the meantime, but we'll surface more information to users in the next few releases.

**Closed** 2021-09-15 12:14 UTC
Labels: topic/typescript, v1/priority
