### ISSUE TITLE
FormError causes warning 'Cannot update a component from inside the function body of a different component'

### ISSUE THREAD

**Issue by colinscape** [redwoodjs/redwood#250] opened 2020-03-14 19:24 UTC
When following the tutorial at the section about server-side email validation, when introducing `FormError`, the console reports the error:

```
Warning: Cannot update a component from inside the function body of a different component.
```

This looks to be coming from https://github.com/redwoodjs/redwood/blob/master/packages/web/src/form/form.js#L27

**Comment by thedavidprice** [comment] 2020-03-31 20:57
@colinscape checking in here. Are you still experiencing this issue? Curious if it is a bug on our end or something specific to your code as you were working through the Tutorial.

Thanks!

**Comment by dominicchapman** [comment] 2020-04-08 23:37
Hey @thedavidprice I’m also seeing this warning when following the tutorial.

[It seems](https://github.com/facebook/react/issues/18178) React `16.3.0` may have been over-firing these warnings and has since [been fixed](https://github.com/facebook/react/issues/18178#issuecomment-601425520) in `16.3.1`, but looks like `react-hook-form` would be using `16.3.1` anyway.

Curious, if this could be linked to #162 ? If so, the fix might be as simple as using PascalCase on [`inputTagProps`](https://github.com/redwoodjs/redwood/blob/master/packages/web/src/form/form.js#L17) (i.e. `InputTagProps`) as described [here](https://dev.to/ranewallin/js-bites-react-hook-is-called-in-a-function-which-is-neither-a-react-function-or-sic-a-custom-react-hook-1g2c). Hope this helps.

**Comment by colinscape** [comment] 2020-04-09 08:19
@thedavidprice Just to confirm - I was following the tutorial step by step and saw this in my console, so there was no custom code from my side involved - either some tweak to the tutorial or Redwood itself was my feeling. From a quick search about it seems to have been regularly encountered with React 16.3 as @dominicchapman mentioned.

**Comment by thedavidprice** [comment] 2020-04-09 18:08
Thanks, gents! Looping in @cannikin here. I've reproduced the issue by simply entering an invalid email using the final state of the tutorial contact form.

Probably not the highest priority for us given some things in progress right now. But on our list. (And would welcome community help!)

Here's a [link to React Hook Form](https://react-hook-form.com/). And a link to [Redwood Forms](https://github.com/redwoodjs/redwood/tree/master/packages/web/src/form) implementation in our "web/" package.

Lastly, I have a personal, up-to-date repo of the final Redwood Blog Tutorial, which I use for testing. It's [thedavidprice/redwood-tutorial-test](https://github.com/thedavidprice/redwood-tutorial-test)  if anyone else wants to make use of it. (Note: the latest Redwood version is 'master' and I create a version-specific branch each time we release.)

```shell
react_devtools_backend.js:6 Warning: Cannot update a component (`ContactPage`) while rendering a different component (`Label`). To locate the bad setState() call inside `Label`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Label (created by ContactPage)
    in FormContext (created by Form)
    in form (created by Form)
    in Form (created by ContactPage)
    in main (created by BlogLayout)
    in BlogLayout (created by ContactPage)
    in ContactPage (created by PageLoader)
    in PageLoader (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Router)
    in Router (created by Routes)
    in Routes
    in ApolloProvider (created by GraphQLProvider)
    in GraphQLProvider (created by RedwoodProvider)
    in RedwoodProvider
    in FatalErrorBoundary
```

**Comment by brianespinosa** [comment] 2020-05-12 02:53
It appears this issue has a corresponding PR that has been merged. Can this now be closed?

**Comment by thedavidprice** [comment] 2020-05-12 16:14
Indeed! Closing now.

**Closed by thedavidprice** 2020-05-12 16:14 UTC
Labels: bug/2-confirmed, good first issue, help wanted, kind/bug, topic: forms
