### ISSUE TITLE
[Bug?]: Supabase Auth `data` parameter not supported during signUp

### ISSUE THREAD

**Issue by shivghai** [redwoodjs/redwood#6321] opened 2022-08-29 17:27 UTC
### What's not working?

Supabase's `data` parameter is not supported during `signUp`.

Supabase uses an extra `{data: {}}` object for user metadata https://supabase.com/docs/reference/javascript/auth-signup#sign-up-with-additional-user-meta-data, and the RedwoodJS `signUp` doesn't support this field. 

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment] 2022-09-04 03:46
Confirming that based on our code and the docs you linked to there's no way of passing `data`: 

https://github.com/redwoodjs/redwood/blob/abaaf5d6810859400cc3116f3b00356a4e246548/packages/auth/src/authClients/supabase.ts#L109-L114

@shivghai as a workaround, did you try destructuring `client` from `useAuth`? That should give you direct access to the supabase client.

@Tobbe you don't have to fix this but wanted it on your radar since it's about auth. Seems like we could fix this relatively easily right now, but maybe it should be done in tandem with your work?

**Comment by jtoar** [comment] 2022-09-04 10:24
Actually seems like this may be a dupe of https://github.com/redwoodjs/redwood/issues/6146 so I'm going to close this one just so that we don't have two conversations going about the same thing. Let me know if you feel this is different though and I'm happy to reopen.

**Closed by jtoar** 2022-09-04 10:24 UTC
Labels: bug/repro-available, topic/auth

**Comment by Tobbe** [comment] 2022-09-04 16:33
> @shivghai as a workaround, did you try destructuring client from useAuth? That should give you direct access to the supabase client.

For signup, login and logout using the client methods directly usually doesn't work. It often causes RW and the auth client library to get out of sync in regards to auth state. So I'm afraid the only way forward here is a fix on our end. And, as I said in the linked issue, I rather wait with auth updates until my auth decoupling PR has landed.
