### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-jest-dom".

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#2018] opened 2021-03-17 07:50 UTC
`yarn lint` in the RW framework repo doesn't work. I get this error message

```
$ yarn lint
yarn run v1.22.4
$ eslint -c .eslintrc.js packages

Oops! Something went wrong! :(

ESLint: 7.19.0

ESLint couldn't find the plugin "eslint-plugin-jest-dom".

(The package "eslint-plugin-jest-dom" was not found when loaded as a Node module from the directory "C:\Users\tobbe\dev\redwood\redwood\packages\create-redwood-app\template".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-jest-dom@latest --save-dev

The plugin "eslint-plugin-jest-dom" was referenced from the config file in "packages\create-redwood-app\template\package.json » @redwoodjs/eslint-config".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jtoar** [comment] 2021-05-20 22:28
I'm also seeing something similar:

![image](https://user-images.githubusercontent.com/32992335/119056749-138ea500-b980-11eb-97b2-c5f960fbdbbc.png)

**Comment by thedavidprice** [comment] 2021-05-21 21:53
Did you both run `yarn build` before you ran lint?

Did a big upgrade on ESlint last week and can confirm at that time there were no problems.

**Comment by jtoar** [comment] 2021-06-10 20:43
@thedavidprice running `yarn build` before `yarn lint` worked. @Tobbe does that also work for you?

**Comment by Tobbe** [comment] 2021-06-10 22:05
This is right after running `yarn build`

```
tobbe@XPS9550 MINGW64 ~/dev/redwood/redwood (tobbe-newpos)
$ yarn lint
yarn run v1.22.4
$ cross-env __REDWOOD__CONFIG_PATH=packages/create-redwood-app/template eslint -c .eslintrc.js packages

Oops! Something went wrong! :(

ESLint: 7.27.0

ESLint couldn't find the plugin "eslint-plugin-jest-dom".

(The package "eslint-plugin-jest-dom" was not found when loaded as a Node module from the directory "C:\Users\tobbe\dev\redwood\redwood\packages\create-redwood-app\template".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-jest-dom@latest --save-dev

The plugin "eslint-plugin-jest-dom" was referenced from the config file in "packages\create-redwood-app\template\package.json » @redwoodjs/eslint-config".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by thedavidprice** [comment] 2021-06-10 22:45
@Tobbe I have no problems locally on Mac with a clean `main` branch that's current as of 5 minutes ago. Also confirming the `eslint-plugin-jest-dom` is at latest version and was updated 2 weeks ago.

Because this is loading config from the template/ directory, do you think it's possibly a path issue on Windows?

**Comment by jtoar** [comment] 2021-12-13 04:29
I haven't been able to reproduce this one; I'll close it since it's been a while and hasn't seen activity. Feel free to re-open if it comes up again!

**Closed by jtoar** 2021-12-13 04:29 UTC
Labels: help wanted, bug/needs-info, topic/config, v1/priority
