### ISSUE TITLE
Cannot generate CRUD SDL for a Model that uses a compound unique id

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1420] opened 2020-10-30 13:34 UTC
Consider this model:

```
model Tag {
  uri     String
  rdfType String
  label   String

  @@id([uri, rdfType, label])
  @@index([rdfType])
  @@index([uri])
}
```

Its unique `id` is a compound one made up of all three fields:

`  @@id([uri, rdfType, label])`

and in Postgres is:

![image](https://user-images.githubusercontent.com/1051633/97710722-8131bd00-1a92-11eb-84d9-7f3f9666d809.png)

However, when attempting to generate a SDL and service for this

> yarn rw g sdl tag --crud  

```
  ✖ Generating SDL files...
    → Cannot generate CRUD SDL without an `id` database column
Cannot generate CRUD SDL without an `id` database column
```

I think because of:

```
const updateInputSDL = (model, types = {}) => {
  return inputSDL(model, false, types)
}

const idType = (model, crud) => {
  if (!crud) {
    return undefined
  }

  const idField = model.fields.find((field) => field.isId)
  if (!idField) {
    throw new Error('Cannot generate CRUD SDL without an `id` database column')
  }
  return idField.type
}
```

in the sdl.js generator.

**Comment by jtoar** [comment] 2021-12-13 03:27
This seems like a duplicate of https://github.com/redwoodjs/redwood/issues/1420. Closing in favor of that one.

**Closed by jtoar** 2021-12-13 03:27 UTC
Labels: duplicate, topic/generators-&-scaffolds, hopper
