### ISSUE TITLE
[CLI]: No warning shows up if an unknown command is supplied

### ISSUE THREAD

**Issue by jamesgeorge007** [redwoodjs/redwood#377] opened 2020-04-01 07:29 UTC
Leverage the `strict()` method as part of `yargs` API to handle unknown commands.

**Comment by thedavidprice** [comment] 2020-04-01 16:34
Hi @jamesgeorge007 Thanks for jumping in on this. Our Yargs handling needs a lot of TLC. Would you be able to spend a bit more time with me to 1) outline our desired constraints and error handling and 2) implement from there?

This is effectively a duplicate of PR #136 Please read that thread for background context. Also, Ben Coe is a friend and core contributor on Yargs who’s offered to help answer questions and give direction. Anytime!

In?

**Comment by jamesgeorge007** [comment] 2020-04-01 16:42
Yeah sure 👍

**Comment by thedavidprice** [comment] 2020-04-13 19:40
@jamesgeorge007 Apologies for dropping the ball on communication here. At the time of this discussion, Peter had attempted to add .strict() to our commands — we thought it was working but then realized it broke a few commands (e.g. `yarn rw g …`) where we have multiple options.

All previous and current work + history is here: https://github.com/redwoodjs/redwood/pull/136

I’m going to cc you know so you’ll be included on the thread. Also, I’m writing up a comment to Ben Coe with the current issues. If you have any yargs implementation experience, please feel free to dive in!

Closing this out to move over to the PR.

**Closed by thedavidprice** 2020-04-13 19:40 UTC
Labels: kind/discussion, kind/improvement, topic: cli

**Comment by jamesgeorge007** [comment] 2020-04-25 17:33
@thedavidprice I'm heavily caught up at the moment, regardless I would love to lend a helping hand as I find time.

**Comment by thedavidprice** [comment] 2020-04-25 18:12
@jamesgeorge007 All good an understood! We'll be here when you're time frees up -- and looking forward to it.
