### ISSUE TITLE
Error generating the Prisma client

### ISSUE THREAD

**Issue by AndrewSverdrup** [redwoodjs/redwood#404] opened 2020-04-08 05:22 UTC
I am following the tutorial here https://redwoodjs.com/tutorial/installation-starting-development, and am running into an error. Here are my project files (just the generated starter files minus the node_modules folder) and the commands I've run:

Project zip: [redwoodblog.zip](https://github.com/redwoodjs/redwood/files/4448342/redwoodblog.zip)

```bash
$ node -v
v13.12.0
```

```bash
$ yarn -v
1.22.4
```

```bash
$ yarn create redwood-app ./redwoodblog

yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-redwood-app@0.4.0" with binaries:
      - create-redwood-app
  ✔ Creating Redwood app
    ✔ Creating directory '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog'
    ✔ Downloading latest release
    ✔ Extracting latest release
    ✔ Clean up
  ✔ Installing packages
    ✔ Checking node and yarn compatibility
    ✔ Running `yarn install`... (This could take a while)

Thanks for trying out Redwood! We've created your app in '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog'

Inside that directory you can run `yarn rw dev` to start the development server.
✨  Done in 119.41s.
```

### Error Output: `yarn rw dev`
Click details below to view.
<details>
```bash
$ cd redwoodblog
$ yarn rw dev

yarn run v1.22.4
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/rw' dev
  ✖ Generating the Prisma client...
    → info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed with exit code 1: yarn prisma2 generate
Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/prisma2' generate
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/dev-server'
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/webpack-dev-server' --config ../node_modules/@redwoodjs/core/config/webpack.development.js
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/prisma2' generate --watch
21:39:28  db | Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:28  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch exited with code 1
21:39:28  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch restarted
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/prisma2' generate --watch
21:39:30  db | Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:30  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch exited with code 1
21:39:30  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch restarted
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/prisma2' generate --watch
21:39:30 web | ℹ ｢wds｣: Project is running at http://localhost:8910/
21:39:30 web | ℹ ｢wds｣: webpack output is served from /
21:39:30 web | ℹ ｢wds｣: Content not from webpack is served from /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/web
21:39:30 web | ℹ ｢wds｣: 404s will fallback to /index.html
21:39:33  db | Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:33  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch exited with code 1
21:39:33  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch restarted
21:39:33 api | /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3
21:39:33 api |     throw new Error(
21:39:33 api |     ^
21:39:33 api | 
21:39:33 api | Error: @prisma/client did not initialize yet. Please run "prisma2 generate" and try to import it again.
21:39:33 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
21:39:33 api |     at new PrismaClient (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3:11)
21:39:33 api |     at Object.<anonymous> (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api/src/lib/db.js:6:19)
21:39:33 api |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
21:39:33 api |     at Module._compile (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
21:39:33 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
21:39:33 api |     at Object.newLoader [as .js] (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
21:39:33 api |     at Module.load (internal/modules/cjs/loader.js:996:32)
21:39:33 api |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
21:39:33 api |     at Module.require (internal/modules/cjs/loader.js:1036:19)
21:39:33 api |     at require (internal/modules/cjs/helpers.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:33 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server exited with code 1
21:39:33 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server restarted
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/prisma2' generate --watch
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/dev-server'
21:39:35  db | Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:35  db | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn prisma2 generate --watch exited with code 1
21:39:37 api | /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3
21:39:37 api |     throw new Error(
21:39:37 api |     ^
21:39:37 api | 
21:39:37 api | Error: @prisma/client did not initialize yet. Please run "prisma2 generate" and try to import it again.
21:39:37 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
21:39:37 api |     at new PrismaClient (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3:11)
21:39:37 api |     at Object.<anonymous> (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api/src/lib/db.js:6:19)
21:39:37 api |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
21:39:37 api |     at Module._compile (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
21:39:37 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
21:39:37 api |     at Object.newLoader [as .js] (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
21:39:37 api |     at Module.load (internal/modules/cjs/loader.js:996:32)
21:39:37 api |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
21:39:37 api |     at Module.require (internal/modules/cjs/loader.js:1036:19)
21:39:37 api |     at require (internal/modules/cjs/helpers.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:38 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server exited with code 1
21:39:38 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server restarted
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/dev-server'
21:39:43 api | /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3
21:39:43 api |     throw new Error(
21:39:43 api |     ^
21:39:43 api | 
21:39:43 api | Error: @prisma/client did not initialize yet. Please run "prisma2 generate" and try to import it again.
21:39:43 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
21:39:43 api |     at new PrismaClient (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3:11)
21:39:43 api |     at Object.<anonymous> (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api/src/lib/db.js:6:19)
21:39:43 api |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
21:39:43 api |     at Module._compile (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
21:39:43 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.newLoader [as .js] (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
21:39:43 api |     at Module.load (internal/modules/cjs/loader.js:996:32)
21:39:43 api |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
21:39:43 api |     at Module.require (internal/modules/cjs/loader.js:1036:19)
21:39:43 api |     at require (internal/modules/cjs/helpers.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:43 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server exited with code 1
21:39:43 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server restarted
$ '/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/.bin/dev-server'
21:39:49 api | /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3
21:39:49 api |     throw new Error(
21:39:49 api |     ^
21:39:49 api | 
21:39:49 api | Error: @prisma/client did not initialize yet. Please run "prisma2 generate" and try to import it again.
21:39:49 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
21:39:49 api |     at new PrismaClient (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/@prisma/client/index.js:3:11)
21:39:49 api |     at Object.<anonymous> (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api/src/lib/db.js:6:19)
21:39:49 api |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
21:39:49 api |     at Module._compile (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:99:24)
21:39:49 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
21:39:49 api |     at Object.newLoader [as .js] (/Users/Andrew/RedwoodJS_Tutorial/redwoodblog/node_modules/pirates/lib/index.js:104:7)
21:39:49 api |     at Module.load (internal/modules/cjs/loader.js:996:32)
21:39:49 api |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
21:39:49 api |     at Module.require (internal/modules/cjs/loader.js:1036:19)
21:39:49 api |     at require (internal/modules/cjs/helpers.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:39:49 api | cd /Users/Andrew/RedwoodJS_Tutorial/redwoodblog/api && yarn dev-server exited with code 1
```
</details>

**Comment by thedavidprice** [comment] 2020-04-10 05:28
@AndrewSverdrup thank you for reporting this. And sorry you ran into issues right out of the gate.

I used the .zip you included to test locally. I was unable to reproduce the error (yay/boo).

If you are still experiencing this, could you try the following:
> Note: this will destroy any uncommitted work you have done
- Remove all git-ignored files and uncommitted changes: `git clean -fxd`
- Remove prisma cache: `rm -rf ~/.cache/prisma`
- Re-install packages: `yarn install`
- Do over! `yarn rw dev`

🤞😬

**Comment by TurboTobias** [comment] 2020-04-10 06:35
Followed your steps and got the same result @thedavidprice 

Removed global prisma CLI just to be sure.

Also, now created an entirely new project with instructions form https://redwoodjs.com/tutorial/installation-starting-development
1. `yarn create redwood-app ./redwoodblog`
2. `cd redwoodblog`
3. `yarn redwood dev`

Same error as printed above :/

Let me know what I can do, glad to help

**Comment by thedavidprice** [comment] 2020-04-10 15:26
@TurboTobias Thank you for this and I’ll dig in. The current Redwood release uses Prisma preview.025. We have Prisma beta.2 working in our ‘master’ but yet to be released — my current working theory is that the fix is in there. 

**re: Global Prisma install:** Ah, this could definitely be part of the issue. Did you install globally prior to trying out Redwood? Or in attempt to get things working with Redwood?

**Comment by TurboTobias** [comment] 2020-04-10 23:45
Looking forward to the release :)

Yes, most likely I had the Prisma2 CLI (alpha version) installed prior to trying out Redwood the first time. But same result after uninstalling `npm uninstall -g @prisma/cli --save`, but not sure if that cleans everything? I did clear the `rm -rf ~/.cache/prisma` also with same results.

**Comment by AndrewSverdrup** [comment] 2020-04-11 02:52
@thedavidprice I can also still reproduce the issue following the steps you listed. I also had the Prisma2 CLI installed globally before trying out Redwood, so it sounds like that may be the issue. I tried uninstalling the CLI, but it doesn't fix the issue. Also I'm on a Mac, not sure if that makes a difference.

> Looking forward to the release :)

Me too!

**Comment by peterp** [comment] 2020-04-11 06:25
Could you run the following and let us know if it generates the client, and migrates the database?

```terminal
cd <myproject>/api
yarn prisma2 migrate up --experimental --create-db
yarn prisma2 generate
```

This is equivalent to what is run when you type `yarn rw db up`

**Comment by TurboTobias** [comment] 2020-04-11 06:30
1. Running`$ yarn prisma2 migrate up --experimental --create-db` (from /api) errors the following

```
yarn run v1.21.1
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/prisma2' migrate up --experimental --create-db
Error: Get config {"is_panic":false,"message":"error: Environment variable not found: BINARY_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-client-js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Environment variable not found: BINARY_TARGET.\n  -->  schema.prisma:8\n   | \n 7 |   provider      = \"prisma-client-js\"\n 8 |   binaryTargets = env(\"BINARY_TARGET\")\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by TurboTobias** [comment] 2020-04-11 06:36
Same error for `yarn prisma2 generate` 👆

Tried `yarn rw db up` for funsies and it migrates the database but fails to set up client, "cannot call write after stream was destroyed".

Output
```
tobias@Tobiass-MacBook-Pro api % yarn rw db up
yarn run v1.21.1
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/rw' db up
Migrate database up... [started]
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/prisma2' migrate up --experimental --create-db
🏋️‍  migrate up

All migrations are already applied
Migrate database up... [completed]
Generating the Prisma client... [started]
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/prisma2' generate
Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Generating the Prisma client... [failed]
→ Command failed with exit code 1: yarn prisma2 generate
Command failed with exit code 1: yarn prisma2 generate
✨  Done in 3.65s.
```

**Comment by peterp** [comment] 2020-04-11 07:47
@TurboTobias Crazy, could you check that your `.env.defaults` has the `BINARY_TARGETS` line:

https://github.com/redwoodjs/create-redwood-app/blob/master/.env.defaults#L7

**Comment by TurboTobias** [comment] 2020-04-11 07:49
Yup, file matches exactly

```
# These environment variables will be used by default if you do not create any
# yourself in .env. This file should be safe to check into your version control
# system. Any custom values should go in .env and .env should *not* be checked
# into version control.

DATABASE_URL=file:./dev.db
BINARY_TARGET=native
```

**Comment by peterp** [comment] 2020-04-11 07:51
Thanks, this gives me an idea! I'll get back to you soon

**Comment by TurboTobias** [comment] 2020-04-11 07:57
Just out of curiosity, how is `yarn prisma2 ...` supposed to work without any prisma2 command? I can't seem to find it in any of the package.json's or in the `@redwoodjs` repo

**Comment by peterp** [comment] 2020-04-11 08:50
Check `node_modules/.bin`

~/Downloads/redwoodblog
➜ ls node_modules/.bin/prisma2
node_modules/.bin/prisma2

The package is installed here:
https://github.com/redwoodjs/redwood/blob/607e481626c9516ff07c18a57a66a6b424d89c52/packages/core/package.json#L20

**Comment by peterp** [comment] 2020-04-11 09:02
@TurboTobias So I actually forgot how the `yarn rw db generate` command works 🤦‍♂️. It loads in the environmental variables defined in `.env:
https://github.com/redwoodjs/redwood/blob/db1dbbe41100de8edbadf434ae6cc2ed20f637f6/packages/cli/src/index.js#L8-L12

and then passes them in scope to the executed CLI:
https://github.com/redwoodjs/redwood/blob/8d510dbfb3c4c88c0d6448a9d58771a8eef547d7/packages/cli/src/lib/index.js#L196

Could you just run `yarn rw db generate`?

**Comment by TurboTobias** [comment] 2020-04-11 10:28
Yes, `yarn rw db generate` produces

```
tobias@Tobiass-MacBook-Pro redwoodblog % yarn rw db generate
yarn run v1.21.1
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/rw' db generate
Generating the Prisma client... [started]
$ '/Users/tobias/Library/Mobile Documents/com~apple~CloudDocs/Web/redwoodblog/node_modules/.bin/prisma2' generate
Error: Cannot call write after a stream was destroyed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Generating the Prisma client... [failed]
→ Command failed with exit code 1: yarn prisma2 generate
Command failed with exit code 1: yarn prisma2 generate
✨  Done in 3.28s.
```

**Comment by Rosenberg96** [comment] 2020-04-11 11:19
Hi @TurboTobias,

See this issue: https://github.com/prisma/prisma/issues/1973
From your console output here it seems that the path `Mobile Documents` includes space. I suggest trying from a new system path

**Comment by thedavidprice** [comment] 2020-04-11 19:16
The “space in path” issue above is _very_ helpful. But this doesn’t seem to be the case for the OP @AndrewSverdrup (make sure to click the details hide/reveal): https://github.com/redwoodjs/redwood/issues/404#issue-596316604

There are a couple other data points for diagnosing:
- In the 3 reported case, ALL previously installed prisma cli globally
- In this case, Carter Rabasa experienced errors using Redwood v0.4.0 (i.e. Prisma preview025). But he successfully ran local tests using the Prisma start app with prisma-2.0.0-beta.2. See: https://community.redwoodjs.com/t/m-n-relationships-are-not-working-with-migrations/338/4?u=thedavid

We have a `yarn rw info` command, which uses envinfo package. Potentially we could add a check here for globally installed packages. However, since we use `yarn` it won’t pick up `npm` installed global packages. (Based on my local tests.)

As of now, I think 2/3 of the reported errors will resolve once we release new Redwood packages that include the latest Prisma beta. (Hopefully this Monday 🤞 )

**Comment by TurboTobias** [comment] 2020-04-11 21:50
> Hi @TurboTobias,
> 
> See this issue: [prisma/prisma#1973](https://github.com/prisma/prisma/issues/1973)
> From your console output here it seems that the path `Mobile Documents` includes space. I suggest trying from a new system path

Early on I looked at that issue and though "I don't have space in my paths"... 🤦 But totally forgot that Mac OS 10.15.* update raped my filesystem. It put common folders like Documents and similar undeneath this "Mobile Documents" which is iCloud. So possible that others on recent Mac OS versions may experience the same.

Anyways, now the client is generated and everything is working ✅ 
Thanks! 🙏

**Comment by AndrewSverdrup** [comment] 2020-04-11 23:03
The space in the path was my issue too. I didn't realize that could be the cause of the issue and I sort of "sanitized" the path in the output logs I posted since the path to my project was fairly long. Never thought that'd be the issue 🤦.  Thanks for the fix and I've learned not to modify the output log at all (seems obvious now 😅).

**Comment by TurboTobias** [comment] 2020-04-11 23:05
> The space in the path was my issue too. I didn't realize that could be the cause of the issue and I sort of "sanitized" the path in the output logs I posted since the path to my project was fairly long. Never thought that'd be the issue 🤦. Thanks for the fix and I've learned not to modify the output log at all (seems obvious now 😅).

That is so funny that you made the path pretty. I did _exactly_ the same in my first log reply, thankfully I added more without modifying. Never again!

**Comment by thedavidprice** [comment] 2020-04-16 03:50
Looks like a fix is now merged into prisma/cli@alpha and will be in next Beta release:
https://github.com/prisma/prisma/issues/1973

**Comment by thedavidprice** [comment] 2020-04-16 04:55
This was reported earlier on Windows. Linking to test as well once next Prisma release is out and in RWJS: https://github.com/redwoodjs/redwood/issues/409

**Closed** 2020-04-21 22:15 UTC
Labels: bug/2-confirmed, kind/bug, topic: prisma

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 16:49
Hi - As per the documentation, we need yarn > 1.15 and node > 12.x  to bootstrap your RW app. I have **yarn 1.22.10** and node **12.18.4** but I am getting the following error when I am trying to exec  < yarn create redwood app {appname} > 
Could anyone confirm if I need **_Node v > 14_** ?
![image](https://user-images.githubusercontent.com/85705446/121815721-69abeb00-cc95-11eb-91a7-91f93db82202.png)

**Comment by Tobbe** [comment] 2021-06-13 17:18
@InquisitiveAboutReact We fairly recently decided to tighten up our node requirement. We only run tests on node 14.x, so we decided that was the only version we wanted to officially support. If our docs still say >= 12 somewhere, they need to be updated. Do you by chance still remember where you read node 12?

If you want to continue using RW on node 12 you have to manually change the "engines" config in the root `package.json` file. But, again, since we're not testing on node 12 any more, there are no guarantees that it'll work, so you have to test yourself.

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 17:42
Hi @Tobbe - Thanks for your reply. To answer your question 'Do you by chance still remember where you read node 12? ' -- Today is my first day exploring RW and went through the below URL. In Video 1 , it says Yarn > 1.15.x and Node > 12.x 
_https://learn.redwoodjs.com/docs/tutorial/welcome-to-redwood/ 

Last but not the least, while creating the RW app , using   **yarn create redwood-app ./<appname>** ,  I am getting the below message .. The app folder gets created and while I was trying to run  **yarn redwood dev** or **yarn rw dev** it says it couldn't find the package.json file. Sorry for too many questions, I must be missing something I guess :) 
![image](https://user-images.githubusercontent.com/85705446/121817014-7e3fb180-cc9c-11eb-8a3d-778fb611a102.png)

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 18:54
Hi @Tobbe - Somehow able to fix the issue. Below are the steps I did
1. Manually fix the node version in root package.json
2. after creating RW app, I triggered the command  **' yarn install '**  ( not mentioned in the doc I believe. It should be added ) 
3. Ran the command  **yarn rw dev** to bootstrap my app.
However there are some errors I got related to Prisma , will try to fix it. 
Cheers !!

**Comment by Tobbe** [comment] 2021-06-13 18:57
> 2\. after creating RW app, I triggered the command  **' yarn install '**  ( not mentioned in the doc I believe. It should be added )

You only had to do that because it failed in the first step. For someone who already had the required version of node RW will be installed automatically

**Comment by Tobbe** [comment] 2021-06-13 18:59
> Today is my first day exploring RW and went through the below URL. In Video 1 , it says Yarn > 1.15.x and Node > 12.x

Ahh, I see.
The videos are pretty old by now. A lot has changed since they were recorded 🙂  Until new videos are produced (which is a lot of work!) I'd recommend you follow the written tutorial instead. It's much more up to date

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 19:05
I will do the same. Thanks for your reply @Tobbe . One more query though. Getting the below error, any suggestion for a quick fix for the same? It's related to Prisma. 
![image](https://user-images.githubusercontent.com/85705446/121818982-46d70200-cca8-11eb-9a91-5c3656bf7bf5.png)

**Comment by dthyresson** [comment] 2021-06-13 19:07
> If our docs still say >= 12 somewhere, they need to be updated. Do you by chance still remember where you read node 12?

@Tobbe I think is is in the Quick Start https://redwoodjs.com/docs/quick-start

![image](https://user-images.githubusercontent.com/1051633/121818991-af968e00-cc58-11eb-99a5-51f64867a68d.png)

Had added a documentation issue: https://github.com/redwoodjs/redwoodjs.com/issues/717

**Comment by Tobbe** [comment] 2021-06-13 19:59
> One more query though. Getting the below error, any suggestion for a quick fix for the same? It's related to Prisma.

I'm afraid I haven't seen that one before 🙁 

Could you please try upgrading to node 14 if you haven't already? See if that helps

BTW, what shell and terminal are you using?

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 20:08
Hi @Tobbe  - I am using command prompt and Node js command prompt. There's one solution provided in the below Github link but looks like it's old. I tried to search ../node_modules/prisma2 folder but didn't get it. 
https://github.com/redwoodjs/redwood/issues/215

Oh, the system currently I am working on, it's a bit old so don't support N v 14. Thought I'd try with N v 13.x but haven't started yet.  If you somehow managed to find the solution, please do let me know.

**Comment by Tobbe** [comment] 2021-06-13 21:00
Can you please post the output from `yarn rw info`? Thanks!

**Comment by InquisitiveAboutReact** [comment] 2021-06-13 21:16
@Tobbe 
![image](https://user-images.githubusercontent.com/85705446/121822065-a5a57700-ccba-11eb-93dd-8594bbd4e850.png)

**Comment by Tobbe** [comment] 2021-06-13 23:53
I was hoping to get the full output, to see your Windows version as well

Here's mine
```
$ yarn rw info
yarn run v1.22.4
$ C:\Users\tobbe\dev\redwood\performance-management\node_modules\.bin\rw info

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 16.3.0 - ~\AppData\Local\Temp\yarn--1623628382025-0.26088926523178935\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1623628382025-0.26088926523178935\yarn.CMD
  Browsers:
    Chrome: 91.0.4472.101
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @redwoodjs/core: ^0.33.3 => 0.33.3

Done in 9.41s.
```

**Comment by InquisitiveAboutReact** [comment] 2021-06-14 05:39
Hi @Tobbe  - Here's the full log. This system of mine is kinda old where I am trying to work on RW. It's Win 7. 
![image](https://user-images.githubusercontent.com/85705446/121844050-f63fc300-cd00-11eb-806a-935d9fa2ce81.png)

**Comment by Tobbe** [comment] 2021-06-14 08:54
Yeah, sorry, if things works on something that old it's more of a happy coincidence than something we have the resources to actively support.

But, if there's some easy change we can do to make it work for you, we're happy to fix it 🙂 Just let us know 👍

**Comment by InquisitiveAboutReact** [comment] 2021-06-14 16:38
Hi @Tobbe - Thanks a lot for your help till now. Really appreciate :) 
I have tried , well have been in different ways but still getting the Prisma error. Tried installing **prisma cli** and **client** separately inside .**./api** but didn't work out. Also getting error whenever I am running **yarn rw prisma migrate dev**
Not sure is this as I am working on Win 7 or not but my guess is may be this is due to the OS version. Unfortunately this issue makes me stall for moving forward :(

**Comment by Tobbe** [comment] 2021-06-14 17:57
@InquisitiveAboutReact Is it 32 or 64 bit Win7? I just found this https://github.com/prisma/prisma/issues/6771

**Comment by InquisitiveAboutReact** [comment] 2021-06-14 18:52
@Tobbe -Thanks, went through the thread. It's for query-engine and Microsoft has ended the support for W7. When I try to install prisma/cli , prisma/client locally / globally, I am not having any issues. When redwood is trying to run prisma client, I am getting error, so I believe it might be something related to configuration related to Redwood + Prisma for Win7. Don't think it's an isolated incident only related to prisma. What's your take on this? I think, I should post this issue in prisma github forum as well.

**Comment by Tobbe** [comment] 2021-06-14 19:00
> It's for query-engine and Microsoft has ended the support for W7

Exactly! I remembered seeing query-engine-windows.exe in your screenshot. And since you're on Win7 I thought it might be relevant to you :)  

![image](https://user-images.githubusercontent.com/30793/121944719-40ea2b00-cd53-11eb-9d22-95f7b5814d6f.png)

You can ask the Prisma people, but I think they're just going to tell you the same thing as the dude in that issue I linked - Win7 is not supported.

**Comment by InquisitiveAboutReact** [comment] 2021-06-14 19:16
Yes I saw that and you did catch it perfectly @Tobbe  :) Posted that issue in Prisma forum. Let's see. Doing manual configuration for Win 7 will be hectic still will try once if needed. Let's hope for the best !

**Comment by InquisitiveAboutReact** [comment] 2021-06-14 20:11
They have requested to log this as a bug . Below is the link 
https://github.com/prisma/prisma/issues/7660
