### ISSUE TITLE
[Scenario Testing] Foreign Key constraint errors when trying to cleanup after scenario run

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3680] opened 2021-11-01 17:27 UTC
Right now, when cleaning up scenarios, we always delete table data in the table order that Prisma's `getDMMF()` function gives them to us in: https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/jest/api/jest.setup.js#L33-L41

This can lead to foreign key constraint errors where you try to delete a parent record before the child (the child has a foreign key relationship to the parent and unless `CASCADE DELETE` is configured, will throw an error).

```
   Invalid `prisma.executeRaw()` invocation:

      Raw query failed. Code: `1811`. Message: `FOREIGN KEY constraint failed`

      at cb (../node_modules/@prisma/client/runtime/index.js:38537:17)
      at teardown (../node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:46:5)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:118:3)
```

I can't find a way in Jest to override an `afterEach` invocation: they just stack up and all run no matter what. But, I think I came up with a fix: in your test you can set a `global` in which you define what order to delete models in. As long as this appears before your first test the `afterEach` that's [defined](https://github.com/redwoodjs/redwood/blob/main/packages/testing/config/jest/api/jest.setup.js#L110-L112) in Jest setup will use this list of models instead of fetching them from `getDMMF()` each time.

**Comment by thedavidprice** [comment] 2021-11-02 22:00
Duplicate of #3655 Let's move conversation to that PR.

Leaving open to close when #3655 is fixed.

**Closed** 2021-11-11 19:58 UTC
Labels: bug/confirmed, topic/testing
