### ISSUE TITLE
[Bug?]: TS error in `preview.tsx` & `main.ts` when using absolute (`src/`-prefixed) and/or component directory imports [storybook-vite]

### ISSUE THREAD

**Issue by Philzen** [redwoodjs/redwood#11741] opened 2024-12-03 18:58 UTC
### What's not working?

As reported [in the forum](https://community.redwoodjs.com/t/storybook-in-redwood-is-moving-to-vite/7212/21?u=philzen) during the storybook migration from webpack to vite:

![screenshot](https://rwjs-discourse.nyc3.cdn.digitaloceanspaces.com/original/2X/7/72b4d4d9ef6660d978b110bda60acf5a0b28fc09.png)

Above squiggles amount to `Cannot find module '{import path}' or its corresponding type declarations.`. Storybook compiles fine though with not complaints whatsoever.

@arimendelow 

### Current workaround

Use relative imports and specify the full component path (i.e. `../src/components/ConfirmDialog/ConfirmDialog` works for the above example).

### How do we reproduce the bug?

1. Utilize cli-storybook-vite and edit `main.ts` or `preview.tsx` in `web/.storybook`
2. Try adding an absolute path to any component starting with `src/` *or* any path to a component that only refers to the component directory (i.e. `../src/components/MyComponent` instead of `../src/components/MyComponent/MyComponent`)

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.12 Manjaro Linux
    Shell: 5.2.37 - /bin/bash
  Binaries:
    Node: 20.16.0 - /tmp/xfs-88cf9d03/node
    Yarn: 4.4.0 - /tmp/xfs-88cf9d03/yarn
  Databases:
    SQLite: 3.46.1 - /usr/bin/sqlite3
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 8.4.1 => 8.4.1 
    @redwoodjs/cli-storybook-vite: 8.4.1 => 8.4.1 
    @redwoodjs/core: 8.4.1 => 8.4.1 
    @redwoodjs/project-config: 8.4.1 => 8.4.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by arimendelow** [comment] 2024-12-03 19:29
This is an issue that touches codegen that I am not familiar with — there's a bunch of magic that happens when you eg run `yarn rw g types` to make the component directory import work. Issue is, it only applies to things within the `src` directory. There's also things going on with `tsconfig`, which TBH is also something I'm not so knowledgable of 🙃

Is this breaking anything? The syntactic sugar of being able to use an absolute import is certainly nice, but enabling it here may not be worth the investment.

@Tobbe, can you weigh in here?

**Comment by irg1008** [comment] 2024-12-05 01:02
You can add .storybook folder to .tsconfig like:
```json
  "include": [
    "src",
    "config",
    "./.storybook/**/*",
    "../.redwood/types/includes/all-*",
    "../.redwood/types/includes/web-*",
    "./types"
  ]
  ```
  
  This allows to use relative imports

**Comment by irg1008** [comment] 2024-12-05 01:03
My problem with storybook it's that mockCurrentUser just doesn't work, even with the provider as decorator

**Comment by irg1008** [comment] 2024-12-05 01:04
Also, eslint does not work for this files with current eslint config

**Comment by Tobbe** [comment] 2024-12-05 07:11
> This is an issue that touches codegen that I am not familiar with — there's a bunch of magic that happens when you eg run `yarn rw g types` to make the component directory import work. Issue is, it only applies to things within the `src` directory. There's also things going on with `tsconfig`, which TBH is also something I'm not so knowledgable of 🙃
> 
> Is this breaking anything? The syntactic sugar of being able to use an absolute import is certainly nice, but enabling it here may not be worth the investment.
> 
> @Tobbe, can you weigh in here?

I've never actually worked with Storybook, so I feel a bit outside of my comfort zone with this one 😬
But I can certainly take a look if get more detailed reproduction steps than what is provided in the original post. Like, if I start with `yarn create redwood-app --yes rw-sb-ts-error` what do I do next?

**Comment by Philzen** [comment] 2024-12-05 09:07
> what do I do next?

Generate a component, then open up `web/.storybook/preview.tsx` and then try to import that component. You should find that only relative imports using the full path work, so it's like:

- :heavy_check_mark: `import MyComponent from `../src/components/MyComponent/MyComponent`

vs. what you would expect to work (as it does everywhere else in the RW stack)

- :x: `import MyComponent from `../src/components/MyComponent`
- :x: `import MyComponent from `src/components/MyComponent`
- :x: `import MyComponent from `src/components/MyComponent/MyComponent`

**Comment by Philzen** [comment] 2024-12-05 10:22
> You can add .storybook folder to .tsconfig like:
> 
> ```json
>   "include": [
>     "src",
>     "config",
>     "./.storybook/**/*",
>     "../.redwood/types/includes/all-*",
>     "../.redwood/types/includes/web-*",
>     "./types"
>   ]
> ```
> 
> This allows to use relative imports

@irg1008 i think this nails it, cheers

I guess during the move from from `web/config` to `web/.storybook` this was simply forgotten to be updated.

Solves all the issues above except the `import * from 'react'` necessity, however that's not a big nuisance i believe.

**Comment by irg1008** [comment] 2024-12-05 10:48
https://github.com/redwoodjs/redwood/blob/c367143b23a11a852bbfdd914970f6982fc4b6c2/packages/testing/src/web/mockAuth.tsx#L23

Is this mocked useAuth being used in storybook right now?

**Comment by irg1008** [comment] 2024-12-05 11:35
## useAuth not being mocked up when inside storybook

About this. I fixed it. I think I need to point out how and what I did wrong.

For storybook auth mock we use:
https://github.com/redwoodjs/redwood/blob/c367143b23a11a852bbfdd914970f6982fc4b6c2/packages/storybook/src/plugins/mock-auth.ts

In the script we can see the path detected for transformation is
https://github.com/redwoodjs/redwood/blob/c367143b23a11a852bbfdd914970f6982fc4b6c2/packages/storybook/src/plugins/mock-auth.ts#L8

When moving our auth.ts file from root folder to let's say "lib" folder, storybook is not able to find the file and therefore replace it with the mock.

* web/src/auth.ts => OK
* web/src/lib/auth.ts => Not Ok

It's an issue with me since I change the file location but could we provide a way to set auth file location or maybe add some common paths like 'lib/auth' or similar?

**Comment by Philzen** [comment] 2024-12-05 11:40
> https://github.com/redwoodjs/redwood/blob/c367143b23a11a852bbfdd914970f6982fc4b6c2/packages/testing/src/web/mockAuth.tsx#L23
> 
> Is this mocked useAuth being used in storybook right now?

@irg1008 Apart from this being slightly off-topic in this issue here – i'm not sure what you mean. Shouldn't we simply use [`mockCurrentUser` in Storybook](https://docs.redwoodjs.com/docs/canary/tutorial/chapter7/rbac/#mocking-currentuser-for-storybook)?

**Comment by irg1008** [comment] 2024-12-05 11:42
Yeah sorry about that, I meant that the location of auth.ts file on the web side it's mandatory to be on the root folder. Otherwise the storybook plugin won't pick it up and mock it, making mockCurrentUser function to use the original unmocked function

**Comment by Philzen** [comment] 2024-12-05 11:54
> Yeah sorry about that, I meant that the location of auth.ts file on the web side it's mandatory to be on the root folder. Otherwise the storybook plugin won't pick it up and mock it, making mockCurrentUser function to use the original unmocked function

Ah i see, thanks for the explanation. I guess that would be defined somewhere in the `@redwoodjs/cli-storybook-vite` package's code. But i believe it's best to open up a separate issue (could propably be an RFC) to discuss this.

**Comment by Philzen** [comment] 2024-12-05 13:06
> Also, eslint does not work for this files with current eslint config

Ah yeah that's another gotcha. I solved it by adding `"ignorePatterns": ["!.storybook/"]` to my local extended eslint config. However i believe that should be fixed in "@redwoodjs/eslint-config" as well.

**Comment by Tobbe** [comment] 2024-12-05 13:10
> When moving our auth.ts file from root folder to let's say "lib" folder, storybook is not able to find the file and therefore replace it with the mock.
> 
> * web/src/auth.ts => OK
> * web/src/lib/auth.ts => Not Ok
> 
> It's an issue with me since I change the file location but could we provide a way to set auth file location or maybe add some common paths like 'lib/auth' or similar?

I wouldn't be surprised if this also breaks other things. We probably assume the location of your auth file is at `web/src/auth.ts` in more places (But maybe we're lucky and we don't!)

Anyway, if we can make this configurable for Storybook I'm all for that 🙂

**Comment by arimendelow** [comment] 2024-12-08 02:35
> > You can add .storybook folder to .tsconfig like:
> > ```json
> >   "include": [
> >     "src",
> >     "config",
> >     "./.storybook/**/*",
> >     "../.redwood/types/includes/all-*",
> >     "../.redwood/types/includes/web-*",
> >     "./types"
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This allows to use relative imports
> 
> @irg1008 i think this nails it, cheers
> 
> I guess during the move from from `web/config` to `web/.storybook` this was simply forgotten to be updated.
> 
> This solves all issues above 🥳

Oh yay!!!! Yup, that's my mistake :) I'm still more comfortable _using_ the framework and still a little newer to _building_ the framework.

**Comment by arimendelow** [comment] 2024-12-08 02:36
> > When moving our auth.ts file from root folder to let's say "lib" folder, storybook is not able to find the file and therefore replace it with the mock.
> > 
> > * web/src/auth.ts => OK
> > * web/src/lib/auth.ts => Not Ok
> > 
> > It's an issue with me since I change the file location but could we provide a way to set auth file location or maybe add some common paths like 'lib/auth' or similar?
> 
> I wouldn't be surprised if this also breaks other things. We probably assume the location of your auth file is at `web/src/auth.ts` in more places (But maybe we're lucky and we don't!)
> 
> Anyway, if we can make this configurable for Storybook I'm all for that 🙂

Ditto on this :) Didn't even occur to me that anyone would want to move that. @irg1008 what was your reason for moving it? And have you run into any other issues related to it?

**Closed** 2024-12-08 06:47 UTC
Labels: bug/needs-info

**Comment by irg1008** [comment] 2024-12-08 07:07
> > > When moving our auth.ts file from root folder to let's say "lib" folder, storybook is not able to find the file and therefore replace it with the mock.
> 
> > > 
> 
> > > * web/src/auth.ts => OK
> 
> > > * web/src/lib/auth.ts => Not Ok
> 
> > > 
> 
> > > It's an issue with me since I change the file location but could we provide a way to set auth file location or maybe add some common paths like 'lib/auth' or similar?
> 
> > 
> 
> > I wouldn't be surprised if this also breaks other things. We probably assume the location of your auth file is at `web/src/auth.ts` in more places (But maybe we're lucky and we don't!)
> 
> > 
> 
> > Anyway, if we can make this configurable for Storybook I'm all for that 🙂
> 
> 
> 
> Ditto on this :) Didn't even occur to me that anyone would want to move that. @irg1008 what was your reason for moving it? And have you run into any other issues related to it?
> 
> 
None, I thought moving this file didn't mean anything, so I moved it to lib to match the api folder structure somehow.

I think that if we don't have file based routing, we shouldn't have to have this constraint for specific file locations

Or maybe some sort of way to customize the paths.

Anyway it's not big deal, just moved it back to the root folder
