### ISSUE TITLE
[Bug?]: The `TData` and `TVariables` types on `useMutation` cannot be inferred properly when using `TypedDocumentNode`

### ISSUE THREAD

**Issue by jerelmiller** [redwoodjs/redwood#9232] opened 2023-09-21 21:59 UTC
### What's not working?

Hello 👋  I'm an Apollo Client maintainer and spotted a TypeScript bug while putting together the workshop for RedwoodJS Conf. When working with the `useMutation` hook exported by `@redwoodjs/web`, the generic argument types seem to be lost when the GraphQL documented is typed with a `TypedDocumentNode`. If I use `useMutation` directly from `@apollo/client`, type inference works as expected. This is especially noticeable on the `data` property passed to the `update` function on the `useMutation` hook. The type should be `TData`, but is instead set to `any`.

### How do we reproduce the bug?

You can reproduce this issue by creating a document node and setting it to a `TypedDocumentNode` type.

```ts
import { TypedDocumentNode } from '@apollo/client';
import { useMutation } from '@redwoodjs/web';

const MUTATION: TypedDocumentNode<MyQuery, MyQueryVariables> = gql`
  query MyQuery($myVar: String) {
    someField(var: $myVar)
  }
`

const [execute] = useMutation(MUTATION);
//                ^? useMutation<any, GraphQLOperationVariables>(...)
```

Here, `TData` and `TVariables` on `useMutation` should be set to `MyQuery` and `MyQueryVariables` respectively via the type inference from `TypedDocumentNode`. Unfortunately it looks like these types are set to `any` and `GraphQLOperationVariables`, which I assume are the defaults for those generic parameters. 

Switching the `useMutation` import from `@redwoodjs/web` to `@apollo/client` makes this work correctly and `TData` and `TVariables` are set correctly.

```ts
const [execute] = useMutation(MUTATION);
//                ^? useMutation<MyQuery, MyQueryVariables>(...)
```

I can workaround the issue by explicitly providing the generic parameters, though I'd love for this to work with type inference as well 🙂.

```ts
const [execute] = useMutation<MyQuery, MyQueryVariables>(MUTATION)
//                ^? useMutation<MyQuery, MyQueryVariables>(...)
```

It would also be super nice if you exported the `TypedDocumentNode` type from this library so that you can type the document itself and rely on type inference when passing that around to hooks.

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.5.2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /private/var/folders/95/0ztcsp7509l18k_0csk2nys00000gn/T/xfs-5f819fea/node
    Yarn: 3.6.1 - /private/var/folders/95/0ztcsp7509l18k_0csk2nys00000gn/T/xfs-5f819fea/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @redwoodjs/auth-custom-setup: 6.3.1 => 6.3.1 
    @redwoodjs/core: 6.3.1 => 6.3.1
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment] 2023-11-27 10:03
@dthyresson trusted document issue - assigning to you here! Afraid I don't really have anymore insight beyond Jerel's description

**Comment by dthyresson** [comment] 2023-11-27 17:01
Hi @jerelmiller I think these come from: https://github.com/redwoodjs/redwood/blob/36eb1d3796f8db6aa64026bebf9607ad57693064/packages/web/src/components/GraphQLHooksProvider.tsx#L26

I'll have to do some exploring to see why it was implemented as any and what can be done to improve.

**Comment by jerelmiller** [comment] 2023-11-27 17:08
@dthyresson awesome! I _think_ this might work if you update that [`mutation` arg](https://github.com/redwoodjs/redwood/blob/36eb1d3796f8db6aa64026bebf9607ad57693064/packages/web/src/components/GraphQLHooksProvider.tsx#L30) to allow for a `TypedDocumentNode` as well:

```ts
type DefaultUseMutationType = <
  TData = any,
  TVariables = GraphQLOperationVariables
>(
  mutation: DocumentNode | TypedDocumentNode<TData, TVariables>,
  options?: GraphQLMutationHookOptions<TData, TVariables>
) => MutationOperationResult<TData, TVariables>
```

This way it can infer those generic params when you don't provide `options` as I did in the example shown above.

**Comment by dthyresson** [comment] 2023-11-27 17:16
Thanks @jerelmiller ... if this works, would you also recommend changing the other hooks (query, subscription, etc) to be the similar?

**Comment by dthyresson** [comment] 2023-11-27 17:18
I also assume that

https://github.com/redwoodjs/redwood/blob/36eb1d3796f8db6aa64026bebf9607ad57693064/packages/web/src/components/GraphQLHooksProvider.tsx#L168

would change as well to be `DocumentNode | TypedDocumentNode<TData, TVariables>,`

**Comment by dthyresson** [comment] 2023-12-02 13:29
See https://the-guild.dev/blog/typed-document-node 

> TypedDocumentNode is a development tool for creating fully typed DocumentNode objects. It means that just by passing the GraphQL query/mutation/subscription/fragment to a supporting GraphQL client library, you'll get fully-typed result and variables objects.

> This is made possible by [TypeScript type inference](https://typescriptlang.org/docs/handbook/type-inference.html).

TypedDocumentNode is a development tool that allows you to create fully typed DocumentNode objects. This means that by simply passing your GraphQL query, mutation, subscription, or fragment to a supporting GraphQL client library, you'll get fully-typed result and variables objects. This is made possible by TypeScript type inference.

Here's how it works:

You write your GraphQL operations (query, mutation, subscription, fragment) in any way you prefer (for example - in a .graphql file).

GraphQL Code Generator will generate a TypedDocumentNode for your operations. This is a bundle of pre-compiled DocumentNode with the operation result type and variables type.

Instead of using your .graphql file, you import the generated TypedDocumentNode and use it with your GraphQL client framework.

The result is automatic type inference, auto-complete, and type checking based on your GraphQL operation.

**Comment by dthyresson** [comment] 2023-12-02 13:32
@jerelmiller I noticed that now with the latest updated codegen, I use client-present and when generating:

```
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
```

I think I'll use https://github.com/dotansimha/graphql-typed-document-node and re-export as well.

Note: I am still exploring and getting a reproduction case going to try out changes.

**Comment by dthyresson** [comment] 2023-12-02 14:04
Think I have it working 

<img width="716" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/21899cad-f660-4515-b87a-7f505acd0fda">

<img width="1003" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/6d884f77-43d3-42fa-9c1d-0eceff32afae">

I have to see exactly where it's best to snort the types as there is (now with new codegen) in /web:

* types/types
* types/graphql
* graphql/graphql

The last is a bit different as `CreatePostMutation` is `CreatePostMutationMutation` and `CreatePostMutationMutationVariables` and codegen seems to append the operation type to the `CreatePostMutation` op name

But seems to be working to infer the types now.

**Closed** 2023-12-28 15:42 UTC
Labels: bug/needs-info
