### ISSUE TITLE
Scaffold CLI breaks when import is null

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#2913] opened 2021-06-30 07:50 UTC
There is an extra comma when there is no import on this line, which prevents `rw scaffold` from running.
 
https://github.com/redwoodjs/redwood/blob/ad7ade7e1ad06c35fa06e54486f0ac3575dbf83b/packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template#L6

A temporary solution is to remove this line within your project's `node_modules`

**Comment by Tobbe** [comment] 2021-06-30 09:19
Related: https://github.com/redwoodjs/redwood/issues/1435

Hopefully this is fixed by https://github.com/redwoodjs/redwood/pull/2829

@pi0neerpat Can you try with latest canary and see if it's fixed?

**Comment by dthyresson** [comment] 2021-06-30 11:10
@pi0neerpat As @Tobbe said, there is a check now that 

It's likely the `fieldsToImport` is empty and it now (in canary) will error if empty.

```js
  const fieldsToImport = Object.keys(
    editableColumns.reduce((accumulator, column) => {
      accumulator[column.component] = true
      return accumulator
    }, {})
  )

  if (!fieldsToImport.length) {
    throw new Error(`There are no editable fields in the ${name} model`)
  }
```

To confirm, can you share the schema for the model you tried to scaffold? 

Did it have any fields ... other than an id, perhaps?

**Comment by Tobbe** [comment] 2021-06-30 14:36
It's not just `id` that's uneditable. It's also `createdAt` and `updatedAt`. And relation fields for implicit relations also don't count. So you can actually have a model that looks like it has a few fields, but it's still 0 "fieldsToImport".

Especially the relations caught me a bit off guard last time. And they are also the reason I think it could be worthwhile to have a `--force` flag. Because maybe you want to add some dropdown or something manually to update the relations. But I digress.

**Comment by pi0neerpat** [comment] 2021-06-30 22:24
I just tried with`^0.34.2-canary.35` with and without `--force`

```graphql
model Treasure {
  id    Int     @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

The above fails with `There are no editable fields in the Treasure model`, but if I add `name String` then it runs successfully.

---

This is another topic completely, but this is another example of why scaffold should be able to include properties beyond whats in `schema.prisma`. For example, here, all the Treasure properties are fetched from a 3rd party API, but I want Cells, SDL, Services, etc.

**Comment by dthyresson** [comment] 2021-06-30 22:38
> This is another topic completely, but this is another example of why scaffold should be able to include properties beyond whats in `schema.prisma`. For example, here, all the Treasure properties are fetched from a 3rd party API, but I want Cells, SDL, Services, etc.

I definitely understand the niceties of the generate scaffold codegen, but scaffolding here is for Prisma CRUD -- or any CRUD. I makes new, edit, delete pages and cells.

When you have a thuird party api:

* where are the model properties defined? If shoudn't make a table
* what client/sdk does it use to fetch, add, edit, deelte (if it can) from the third party api

I typically:

* write SDL based on the properties I need from the third party api
* generate the service
* generate a cell or two list view and single view if i am just fetching)
* generate a page
* add cell

And I know some may say - well can I generate that?

And maybe.

What I would suggest to try is the

`rw generate script` https://redwoodjs.com/docs/cli-commands#generate-script

and then write a script to take in some config or arguments that can:

* define the sdl and create the sdl file
* run the generators as needed
* update pages ...

Or ... hmmm ... could scaffold use SDL instead of schema for 

`const model = await getSchema(pascalcase(pluralize.singular(name)))`

and look at SDL for the fields? and well, still it cannot use db in the services.

There's definitely something to it -- it just maybe isn't "scaffold" per se (ie, scaffold CRUD from schema) but instead generate services, page, cells from SDL with some stubbed out mocked client that can be swapped in for whatver is doing the fetch.

**Comment by dthyresson** [comment] 2021-06-30 22:40
But, I think we can close this out when the new release is in?

Perhaps add an issue for the "new scaffolding codegen" as a ferature request?

**Comment by Tobbe** [comment] 2021-06-30 23:02
> The above fails with `There are no editable fields in the Treasure model`, but if I add a property eg. `name String` then it runs successfully.

Perfect, so it works as intended! OK if we close this issue?

**Comment by pi0neerpat** [comment] 2021-06-30 23:20
Yes ok to close!

> There's definitely something to it -- it just maybe isn't "scaffold" per se (ie, scaffold CRUD from schema) but instead generate services, page, cells from SDL with some stubbed out mocked client that can be swapped in for whatver is doing the fetch.

Agreed, this should probably be outside of scaffold, as a separate tool

**Closed** 2021-06-30 23:21 UTC
Labels: bug/needs-info, topic/generators-&-scaffolds, v1/for-consideration
