### ISSUE TITLE
[Bug?]: @redwoodjs/cli-data-migrate missing babel plugin

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#9323] opened 2023-10-20 12:29 UTC
### What's not working?

Running a data migration doesn't seem to work, with the new options.

I'm trying to switch to the new usage schema of the data migrate command, basically by changing this

![image](https://github.com/redwoodjs/redwood/assets/5943908/11932f23-2a38-438d-ab41-a478298d45d5)

and also cutting down on our docker container.

![image](https://github.com/redwoodjs/redwood/assets/5943908/8adbb373-7973-4a8a-8de5-19e844cb1677)

```
npm WARN exec The following package was not found and will be installed: @redwoodjs/cli-data-migrate@6.3.2

2023/10/20 01:02PM 30 Starting a postgresql pool with 1 connections. | pid=88 hostname=e6caafab1499 prisma={"clientVersion":"5.3.1"} timestamp=2023-10-20T11:02:33.785Z target=quaint::pooled msg=Starting a postgresql pool with 1 connections.

[STARTED] 20231020100844-test-migration.ts

Error in data migration: Cannot find module '@babel/plugin-transform-class-properties'

Require stack:
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/core/lib/config/files/plugins.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/core/lib/config/files/index.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/core/lib/index.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/worker/babel-core.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/worker/handle-message.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/worker-client.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/node.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/nodeWrapper.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@babel/register/lib/index.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@redwoodjs/babel-config/dist/common.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@redwoodjs/babel-config/dist/api.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@redwoodjs/babel-config/dist/index.js
- /root/.npm/_npx/6d664c08aad25283/node_modules/@redwoodjs/cli-data-migrate/dist/bin.js

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

[COMPLETED] 20231020100844-test-migration.ts

1 data migration(s) exited with errors.
```

### How do we reproduce the bug?

I guess you might be able to try running the command via npx and with those paths, but I think a migration actually running is needed to trigger the failure.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by razzeee** [comment] 2023-10-20 13:37
I might have reported this too early.

The `script` runner also fails with this error and it seems like `rw serve` also doesn't work with what I'm copying. Will have to investigate. I thought this was the same things we copied, before we started using data migrate, and it did work fine initially.

**Comment by jtoar** [comment] 2023-10-26 14:49
Hey @razzeee, thanks for reporting, and sorry I was out last week—any new finds on this one? I'll try reproducing with a migration and in an image again in the meantime

**Comment by razzeee** [comment] 2023-10-26 14:54
I'm on vacation this week, will be back on Wednesday

**Comment by Tobbe** [comment] 2023-11-21 13:44
@jtoar Did you have any luck reproducing this?
@razzeee Is this still an issue for you, or can we close it?

**Comment by msteen** [comment] 2023-11-21 14:28
I ran into this issue too, but on an unrelated project and just wanted to share what I learned in case others stumble upon this issue too. As far as I know Babel will look into `node_modules` for the plugins (my test seems to indicate at least as much), so when you use `esbuild`, even if it contains the plugins, Babel will be unable to find them and throw this error. The workaround I found is to update my Babel configuration to contain not just list the plugin package names, but the actual imported plugins. Here is an example of what I did in my test project:

```js
{
  plugins: [
    [require("@babel/plugin-syntax-typescript").default, { isTSX: true }],
    require("@babel/plugin-proposal-do-expressions").default,
    require("@babel/plugin-proposal-async-do-expressions").default,
    require("@babel/plugin-proposal-throw-expressions").default,
  ];
}
```

This way Babel won't search `node_modules` anymore and will just use the `esbuild` bundled Babel plugins as intended.

**Comment by Tobbe** [comment] 2023-11-22 12:08
@msteen Did you also run into for data migrate? Or was it on some other command?

**Comment by msteen** [comment] 2023-11-22 14:05
@Tobbe Unrelated to this project (Redwood) altogether. I just found this issue while Googling for the same issue I had with Babel not finding plugins after using `esbuild`. And I'd hoped maybe the solution I found might help solve this issue too.

**Comment by razzeee** [comment] 2023-11-22 14:50
so I've tried that branch again, rebased it and it's still happening.

I'm currently not sure, what if anything I'm doing wrong and dissecting it, would need me to build the containers each time and deploy, which I currently don't have any time for.

**Comment by Tobbe** [comment] 2023-11-23 09:15
@msteen Alright, thanks for clarifying 🙂 

@razzeee Understood. 

I'll close this issue for now since we can't really reproduce it. But happy to reopen if more people keep having this issue and we figure out a way to reproduce

**Closed by Tobbe** 2023-11-23 09:15 UTC
Labels: bug/needs-info
