### ISSUE TITLE
Windows `yarn create redwood app` fails when username has a space in it

### ISSUE THREAD

**Issue by axtscz** [redwoodjs/redwood#296] opened 2020-03-19 04:38 UTC
I ran the `yarn create redwood-app ./redwoodblog` from the tutorial and it failed with this error:

```
success Installed "create-redwood-app@0.2.5" with binaries:
      - create-redwood-app
'C:\Users\Fake' is not recognized as an internal or external command,
operable program or batch file.
error Command failed.
Exit code: 1
Command: C:\Users\Fake User\AppData\Local\Yarn\bin\create-redwood-app
Arguments: ./redwoodblog
Directory: D:\Projects\Redwood
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this 
command.
```

I'm on Windows 10 and i believe the issue is due to the fact that C:\Users\ folder has a space in it due to my username.

**Comment by peterp** [comment] 2020-03-19 10:34
Thanks for reporting this. I'll try and get a reproduction going.

**Comment by axtscz** [comment] 2020-03-19 13:46
The more I look into this it kind of seems to be a Yarn issue

**Comment by thedavidprice** [comment] 2020-03-19 18:39
Just in case, could you reply with your installed Yarn and Node versions

**Comment by axtscz** [comment] 2020-03-19 18:41
```
node -v
v12.13.0

yarn -v
1.22.4
```

**Comment by peterp** [comment] 2020-03-21 22:39
Closing this because it's a known issue with yarn on Windows.

**Closed by peterp** 2020-03-21 22:39 UTC
Labels: bug/1-repro-available, topic: windows
