### ISSUE TITLE
[Bug?]: yarn create redwood-app fails on node 16.17.0 LTS

### ISSUE THREAD

**Issue by lidermanrony** [redwoodjs/redwood#6338] opened 2022-09-03 22:02 UTC
### What's not working?

After testing multiple node versions, the latest version it _does_ work on is 16.4.0

Following the tutorial:
yarn create redwood-app ./redwoodblog

```
➜  node --version
v16.7.0
➜  yarn --version
1.22.19
```

getting the following output:

```
➜  yarn create redwood-app ./redwoodblog

yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.3.2" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-graphql-tag@3.3.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/depth-limit@1.6.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/disable-introspection@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/filter-operation-type@3.4.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/parser-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/validation-cache@4.5.0" has unmet peer dependency "@envelop/core@^2.4.0".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@4.0.0" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > cosmiconfig-typescript-loader@4.0.0" has unmet peer dependency "typescript@>=3".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
[4/4] 🔨  Building fresh packages...
success Installed "create-redwood-app@2.2.3" with binaries:
      - create-redwood-app
[##########################################################################################################################################################################################################################################] 853/853
  ✔ Creating Redwood app
    ✔ Checking node and yarn compatibility
    ✔ Creating directory '/Users/rony/code/redwoodblog'
  ✔ Installing packages
    ✔ Running 'yarn install'... (This could take a while)
  ✖ Convert TypeScript files to JavaScript
    →     at Module._compile (node:internal/modules/cjs/loader:1101:14)
    Generating types

Error: Command failed with exit code 1: yarn rw ts-to-js
/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163
      class Request extends OriginalRequest {
                            ^

TypeError: Class extends value undefined is not a constructor or null
    at createNodePonyfill (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163:29)
    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/node-ponyfill.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/cjs/server.js:10:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at makeError (/Users/rony/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/rony/.config/yarn/global/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn rw ts-to-js',
  command: 'yarn rw ts-to-js',
  escapedCommand: '"yarn rw ts-to-js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163\n' +
    '      class Request extends OriginalRequest {\n' +
    '                            ^\n' +
    '\n' +
    'TypeError: Class extends value undefined is not a constructor or null\n' +
    '    at createNodePonyfill (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163:29)\n' +
    '    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/node-ponyfill.js:3:19)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:94:18)\n' +
    '    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/cjs/server.js:10:47)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}

Warning: Directory '/Users/rony/code/redwoodblog' was created. However, the installation could not complete due to an error.

error Command failed.
Exit code: 1
Command: /opt/homebrew/bin/create-redwood-app
Arguments: ./redwoodblog
Directory: /Users/rony/code
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

### What's your environment? (If it applies)

```shell
seems like the same issue causes `yarn rw info` to fail

➜  redwoodblog yarn rw info
/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163
      class Request extends OriginalRequest {
                            ^

TypeError: Class extends value undefined is not a constructor or null
    at createNodePonyfill (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163:29)
    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/node_modules/@whatwg-node/fetch/dist/node-ponyfill.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/rony/code/redwoodblog/node_modules/@graphql-yoga/common/cjs/server.js:10:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

```

When downgrading to 16.4.0 I'm successfully getting the following:
```
  System:
    OS: macOS 12.5.1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /private/var/folders/h6/nvt3qzsj1sn9m_klq3t_45hh0000gn/T/xfs-aa3045ab/node
    Yarn: 3.2.1 - /private/var/folders/h6/nvt3qzsj1sn9m_klq3t_45hh0000gn/T/xfs-aa3045ab/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 105.0.5195.52
    Safari: 15.6.1
  npmPackages:
    @redwoodjs/core: 2.2.3 => 2.2.3
```
```


### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment] 2022-09-04 03:39
Hey @lidermanrony, I was able to reproduce this using Node.js v16.7.0. Thanks for the detailed issue! We got another report of the same error in a different context on the [forums](https://community.redwoodjs.com/t/help-no-longer-needed-with-baremetal-deploy/3874).

It looks like in Node.js 16.7.0, the `Request` object from `undici` is `undefined` for some reason. But it works fine for me on the latest version of Node.js 16. Are you able to upgrade your Node version as a workaround?

**Comment by jtoar** [comment] 2022-09-04 16:15
@lidermanrony rereading your issue, I see you've already tried Node.js 16.4.0 and got it working. But it doesn't work for you on later Node.js 16 versions that are actually LTS? Only versions after v16.13.0 are actually LTS: https://nodejs.org/ru/blog/release/v16.13.0/. But I just tried it on v16.8.0 and it worked. Still looking for a Node.js/undici issue as to why it'd fail on v16.7.0

**Comment by chathuraa** [comment] 2022-09-08 10:14
Hi @jtoar ,

I'm getting the following error.

`error create-strapi-app@3.3.2: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.17.0"`

thanks,
Chat.

**Comment by ajoslin103** [comment] 2022-09-09 01:07
I've seen a few interesting notes out there, hunting for an answer

https://github.com/aws/aws-sdk-js-v3/issues/3389 -- say's multiple versions of dependencies

https://github.com/mike-marcacci/fs-capacitor/issues/16 -- talks about `npm force resolutions` which we would use as: Selective dependency resolutions https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

I can also confim 16.8.0 works

**Comment by ajoslin103** [comment] 2022-09-12 00:39
fwiw 16.16.0 works

**Comment by ajoslin103** [comment] 2022-09-15 02:54
I just got hit again...  

yesterday things worked & today I have a fastify version complaint - I only trashed my node_modules and yarn.lock

should I _never_ trash my yarn lock again?  

I remember when freezing your packages.json became a thing -- we're repeating ourselves !!  

(please pretend I posted this at 12:01 :)

**Comment by jtoar** [comment] 2022-10-04 21:01
Sorry for the late response all! @chathuraa could you give more context? Not sure what `create-strapi-app` is. But the error is basically saying that your version of node is too high.

@ajoslin103 you don't want to rebuild your project's `yarn.lock` file unless you're just really stuck debugging something and you think it's because of a dependency. Not an expert, but I'm pretty sure `yarn.lock` is a security mechanism to ensure you get the exact same version of a package every time.

Lastly, leaning towards closing this one. It's definitely broken on the version indicated, but it's quite an odd bug so fixing it seems like it'd take some time, and there's an easy, almost obligatory workaround: use any of the other Node.js v16 versions. Thoughts?

**Comment by jtoar** [comment] 2022-10-05 20:05
Will close this one, but @ajoslin103 mind pointing me to the docker container promise? I just spent some time today on one for a fly deploy. There's definitely work to do but in many cases it's possible to get working, albeit the image is still too big.

**Closed by jtoar** 2022-10-05 20:05 UTC
Labels: bug/confirmed
