### ISSUE TITLE
React hook unmounting in whileLoadingAuth

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#5691] opened 2022-06-04 04:20 UTC
The `whileLoadingAuth` feature is great https://redwoodjs.com/docs/router#loader-while-auth-details-are-being-retrieved. However it fails when the loading component uses any hooks eg `React.useState` or `react-spring` to create an animation

![Peek 2022-06-03 23-20](https://user-images.githubusercontent.com/35622595/171982496-c32986ec-64c7-4952-871f-47e3b5bc7ffa.gif)

Is there some way to unmount the `whileLoadingAuth` component cleanly to avoid this error?

> Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

Reproduced here https://github.com/pi0neerpat/redwood-devops-example/blob/loader-hooks-example/web/src/components/Loader/Loader.js

**Comment by jtoar** [comment] 2022-06-11 07:45
Thanks for the detailed writeup and reproduction @pi0neerpat, was able to confirm this using the component from the repo you linked. I think I have a fix for it. It seems to work locally for me but would you be able to test it out? https://github.com/redwoodjs/redwood/pull/5739

**Comment by Tobbe** [comment] 2022-06-11 08:11
This our test for `whileLoadingAuth`

```js
test('can display a loading screen whilst waiting for auth', async () => {
  const TestRouter = () => (
    <Router useAuth={mockUseAuth({ isAuthenticated: false, loading: true })}>
      <Route path="/" page={HomePage} name="home" />
      <Private
        unauthenticated="home"
        whileLoadingAuth={() => <>Authenticating...</>}
      >
        <Route path="/private" page={PrivatePage} name="private" />
      </Private>
    </Router>
  )
  const screen = render(<TestRouter />)

  // starts on home page
  await waitFor(() => screen.getByText(/Home Page/i))

  // navigate to private page
  // should not redirect
  act(() => navigate(routes.private()))
  await waitFor(() => {
    expect(screen.getByText(/Authenticating.../)).toBeInTheDocument()
    expect(screen.queryByText(/Home Page/)).not.toBeInTheDocument()
  })
})
```

@pi0neerpat Could you try `<Private whileLoadingAuth={() => <Loader />}>`?

**Comment by pi0neerpat** [comment] 2022-06-12 17:46
Tried using `duration: 1` and using the `cancel` prop, but no luck https://github.com/pi0neerpat/redwood-devops-example/commit/0f3b202b9718990c5f4678c6c58bcaaeab13f2e4

`<Set whileLoadingAuth={() => <Loader />}>` Fixes it! Thanks yall!

**Comment by Tobbe** [comment] 2023-04-11 06:48
Looks like this has been resolved, so I'm closing it

**Closed by Tobbe** 2023-04-11 06:48 UTC
Labels: topic/router, bug/confirmed
