### ISSUE TITLE
[Bug?]: (Custom) GraphQL error raised from service takes down the whole app

### ISSUE THREAD

**Issue by vanam** [redwoodjs/redwood#8410] opened 2023-05-24 12:47 UTC
### What's not working?

I was trying to add some [backend validation](https://redwoodjs.com/docs/graphql#error-masking) to a service.

```typescript
// /api/src/services/somethings/somethings.ts
export const updateSomething: MutationResolvers['updateSomething'] = ({
  id,
  input,
}) => {
  validateWithSync(async () => {
    throw new MyCustomError('Cannot update something.') // <-- it might be different type of error such as built-in UserInputError
  })

  return db.something.update({
    data: input,
    where: { id },
  })
}

export class MyCustomError extends RedwoodError {
  constructor(message: string, extensions?: Record<string, any>) {
    super(message, extensions)
  }
}
```

I get _The RedwoodJS API server is not available or is currently reloading. Please refresh._ and when I refresh nothing (eg. currentUser) is working.

```
api | /home/martin/Programming/javascript/rw-auth-error/api/src/services/somethings/somethings.ts:30
api |     throw new MyCustomError('Cannot update something.')
api |           ^
api | 
api | 
api | MyCustomError [RedwoodError]: Cannot update something.
api |     at <anonymous> (/home/martin/Programming/javascript/rw-auth-error/api/src/services/somethings/somethings.ts:30:11)
api |     at validateWithSync (/home/martin/Programming/javascript/rw-auth-error/node_modules/@redwoodjs/api/dist/validations/validations.js:309:5)
api |     at updateSomething (/home/martin/Programming/javascript/rw-auth-error/api/src/services/somethings/somethings.ts:29:3)
api |     at Object.updateSomething (/home/martin/Programming/javascript/rw-auth-error/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema/makeMergedSchema.js:80:32)
api |     at useRedwoodDirectiveValidatorResolver (/home/martin/Programming/javascript/rw-auth-error/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodDirective.js:108:22)
api |     at executeField (/home/martin/Programming/javascript/rw-auth-error/node_modules/@graphql-tools/executor/cjs/execution/execute.js:301:24)
api |     at value_or_promise_1.ValueOrPromise.then.results.<computed> (/home/martin/Programming/javascript/rw-auth-error/node_modules/@graphql-tools/executor/cjs/execution/execute.js:227:60)
api |     at ValueOrPromise (/home/martin/Programming/javascript/rw-auth-error/node_modules/value-or-promise/src/ValueOrPromise.ts:35:15)
api |     at /home/martin/Programming/javascript/rw-auth-error/node_modules/@graphql-tools/executor/cjs/execution/execute.js:227:16
api |     at promiseReduce (/home/martin/Programming/javascript/rw-auth-error/node_modules/@graphql-tools/utils/cjs/jsutils.js:21:15) {
api |   extensions: { code: 'REDWOODJS_ERROR' }
api | }
api | 
api | Node.js v18.14.2
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://localhost:8911/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/auth?method=getToken to http://localhost:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://localhost:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://localhost:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://localhost:8911/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

```

### How do we reproduce the bug?

I created an [example app](https://github.com/vanam/rw-service-error-example) where you can experience this behaviour.

Log in as _test@example.com_ with password _test_ and click the button.

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - /tmp/xfs-db00fd9f/node
    Yarn: 3.5.1 - /tmp/xfs-db00fd9f/yarn
  Browsers:
    Firefox: 113.0.1
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 5.2.2 => 5.2.2 
    @redwoodjs/core: 5.2.2 => 5.2.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment] 2023-05-24 22:06
Thanks for the reproduction @vanam! Looking into this now

**Comment by jtoar** [comment] 2023-05-24 23:25
@vanam I think the problem is that you're passing an async function a synchronous validator:

```js
  // this is validate with a synchronous function, but it's passed an async one
  validateWithSync(async () => {
    throw new MyCustomError('Cannot update something.') // <-- it might be different type of error such as built-in UserInputError
  })
```

I got it to work by removing `async` from the function definition above.

It took me a while to catch this. For some reason, there's no type error, even though `validateWithSync` seems correctly typed to me:

https://github.com/redwoodjs/redwood/blob/b627156e840a56b1bfe7f33dced60d91e667b949/packages/api/src/validations/validations.ts#L620-L627

**Comment by vanam** [comment] 2023-05-25 06:31
My bad. I put `async` there because in my code I have something like this:

```typescript
export const updateSomething: MutationResolvers['updateSomething'] = ({
  id,
  input,
}) => {
  validateWithSync(async () => {
    const sth = await db.something.findUnique({
      where: { id },
    })

    if (sth.name !== 'can update') {
      throw new MyCustomError('Cannot update something.')
    }
  })

  return db.something.update({
    data: input,
    where: { id },
  })
}
```
I needed to interact with DB before I can throw an error. Is there a way how to do that?

**Comment by jtoar** [comment] 2023-05-25 16:54
@vanam there's a complimentary function to `validateWithSync` for async functions called `validateWith`. This may work:

```diff
export const updateSomething: MutationResolvers['updateSomething'] = ({
  id,
  input,
}) => {
-  validateWithSync(async () => {
+  await validateWith(async () => {
    const sth = await db.something.findUnique({
      where: { id },
    })

    if (sth.name !== 'can update') {
      throw new MyCustomError('Cannot update something.')
    }
  })

  return db.something.update({
    data: input,
    where: { id },
  })
}
```

**Comment by vanam** [comment] 2023-05-25 17:14
```diff
- export const updateSomething: MutationResolvers['updateSomething'] = ({
+ export const updateSomething: MutationResolvers['updateSomething'] = async ({
  id,
  input,
}) => {
-  validateWithSync(async () => {
+  await validateWith(async () => {
    const sth = await db.something.findUnique({
      where: { id },
    })

    if (sth.name !== 'can update') {
      throw new MyCustomError('Cannot update something.')
    }
  })

  return db.something.update({
    data: input,
    where: { id },
  })
}
```
With one more async it works. Thank you very much.

**Comment by jtoar** [comment] 2023-05-25 17:55
Ah missed that one; hard without an IDE 😅. Great, going to close this one but lemme know if I'm doing so too early

**Closed by jtoar** 2023-05-25 17:55 UTC
Labels: bug/confirmed
