### ISSUE TITLE
v0.28 esbuild feedback

### ISSUE THREAD

**Issue by semagraph** [redwoodjs/redwood#2126] opened 2021-03-26 22:23 UTC
Just gave the new `yarn rw dev --esbuild` feature a try after upgrading from v0.27 to v0.28, and I'm getting this error in the chrome console:

```
Uncaught Error: Unexpected token E in JSON at position 0
    at new ApolloError (index.js:26)
    at QueryManager.js:535
    at both (asyncMap.js:16)
    at asyncMap.js:9
    at new Promise (<anonymous>)
    at Object.then (asyncMap.js:9)
    at Object.error (asyncMap.js:17)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at iteration.js:4
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.js:4)
    at Object.error (Concast.js:36)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at createHttpLink.js:110
index.js:1 The above error occurred in the <Query> component:

    at Query (http://localhost:8910/static/js/app.chunk.js:13761:3)
    at http://localhost:8910/static/js/app.chunk.js:13842:7
    at div
    at div
    at div
    at List (http://localhost:8910/static/js/0.chunk.js:171512:19)
    at div
    at MapView (http://localhost:8910/static/js/0.chunk.js:170063:19)
    at main
    at BaseLayout (http://localhost:8910/static/js/0.chunk.js:173311:23)
    at HomePage (http://localhost:8910/static/js/0.chunk.js:173883:75)
    at PageLoader (http://localhost:8910/static/js/app.chunk.js:12243:5)
    at InternalRoute (http://localhost:8910/static/js/app.chunk.js:12704:3)
    at Route
    at RouteScanner (http://localhost:8910/static/js/app.chunk.js:12852:3)
    at ParamsProvider (http://localhost:8910/static/js/app.chunk.js:12422:3)
    at LocationProvider (http://localhost:8910/static/js/app.chunk.js:12130:5)
    at RouterContextProvider (http://localhost:8910/static/js/app.chunk.js:12607:12)
    at Router (http://localhost:8910/static/js/app.chunk.js:12813:3)
    at Routes
    at GraphQLHooksProvider (http://localhost:8910/static/js/app.chunk.js:13706:3)
    at ApolloProvider (http://localhost:8910/static/js/app.chunk.js:6372:21)
    at ApolloProviderWithFetchConfig (http://localhost:8910/static/js/app.chunk.js:13428:3)
    at FetchConfigProvider (http://localhost:8910/static/js/app.chunk.js:13617:3)
    at RedwoodApolloProvider (http://localhost:8910/static/js/app.chunk.js:13484:3)
    at AuthProvider (http://localhost:8910/static/js/app.chunk.js:10622:5)
    at RecoilRoot (http://localhost:8910/static/js/app.chunk.js:80432:3)
    at FatalErrorBoundary (http://localhost:8910/static/js/app.chunk.js:13550:5)
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, FatalErrorBoundary.
```

and from the rw logs:
```
web esbuild | [HPM] Error occurred while trying to proxy request /graphql from localhost:8910 to http://[::1]:8911 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

Redwood Version:
```
$ yarn rw info
yarn run v1.22.5

  System:
    OS: Linux 5.8 Pop!_OS 20.10
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.14.0 - /tmp/yarn--1616798599356-0.18979586747403276/node
    Yarn: 1.22.5 - /tmp/yarn--1616798599356-0.18979586747403276/yarn
  Databases:
    SQLite: 3.33.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 86.0.1
  npmPackages:
    @redwoodjs/core: ^0.28.0 => 0.28.0
```

**Comment by thedavidprice** [comment] 2021-03-26 23:19
Thanks for reporting this @semagraph Looping in @peterp 

Might be a duplicate of https://github.com/redwoodjs/redwood/issues/2120

**Comment by peterp** [comment] 2021-03-27 10:29
Thanks, I've updated the instructions on community: You need to install the api-server:

`yarn workspace api add -D @redwoodjs/api`

But, to make sure the process is seamless I'll include it as a development dependency.

**Comment by semagraph** [comment] 2021-03-27 11:07
That resolved the issue, thanks guys

**Closed** 2021-03-27 11:07 UTC
