### ISSUE TITLE
Rename `api/prisma` to `api/db`

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#620] opened 2020-05-29 07:05 UTC
It now looks like it's possible to specify the path to the prisma schema: https://github.com/prisma/prisma/issues/1412

TODO:
- [ ] Verify that the schema argument works.
- [ ] Add a configuration option in `redwood.toml` for setting the path to the prisma schema.
```toml
[api]
    prismaSchema = 'api/prisma/schema.prisma`
```
- [ ] Add functionality to `@redwoodjs/internal/src/config.ts` that allows us to grab the schemaPath.
- [ ] Add a function to `@redwoodjs/api` that creates adds this as an argument to "db" commands.
- [ ] Update default schema.prisma location in netlify.toml plugin config https://github.com/redwoodjs/create-redwood-app/issues/59

**Comment by thedavidprice** [comment] 2020-09-24 05:15
Ready to go with main now at 2.7.1 https://github.com/redwoodjs/redwood/pull/1206

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#prisma-schema-file-location

**Comment by dhausser** [comment] 2020-10-25 22:17
Renaming process is started with https://github.com/redwoodjs/create-redwood-app/pull/112 which should fix https://github.com/redwoodjs/create-redwood-app/issues/59.

I can work on the remaining points, please assign.

**Comment by thedavidprice** [comment] 2020-10-28 03:59
Hi @dhausser Thanks for jumping in here! Would be great to have your help.

There's a lot of nuance to this Issue — we use the directory `prisma` throughout the packages (and especially CLI) for structure checks and command options. Also, when I tried to experiment with this a few months ago, there were some unexpected challenges due to our directory structure combined with setting the working directory for running the Redwood CLI commands that wrap the Prisma CLI commands (oh, and I vaguely recall something about not finding the `.env` file). Anyway, the point being it sure was messy. So definitely worth taking a step at a time and looping in both @peterp and me anytime as needed.

## Suggested next steps
1. Verify that the schema argument works.
I'd manually make changes and see if I can get Prisma CLI to run, eg. `yarn prisma generate ...`. Most of the Prisma commands we use are wrapped with the [Redwood DB commands](https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/commands/dbCommands). Would be a good source of things to check.

> Note: it's hinted at in the OP list above, but the last step will be for all these commands to work using the new config and helpers

2. Add a configuration option in redwood.toml for setting the path to the prisma schema
You can set the default config in [config.ts](https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/config.ts) and then allow for an override via redwood.toml. Personally, I don't think this needs to be exposed in the redwood.toml by default. The [docs](https://redwoodjs.com/docs/app-configuration-redwood-toml) should be updated, however, which doesn't necessarily need to be included in your work but should at least be on a list (or in an Issue) for follow up steps.

Keep us posted. And let us know as you have questions along the way.

Thanks again!

**Comment by dhausser** [comment] 2020-10-31 14:20
- [x] Verify that the schema argument works.

Confirmed working according to the spec:
https://github.com/prisma/specs/blob/master/cli/README.md#arguments-1

![schema-argument](https://user-images.githubusercontent.com/24432220/97781558-9b4fc600-1b8c-11eb-9472-6662adc38e84.png)

**Comment by dhausser** [comment] 2020-10-31 19:00
- [x] Add functionality to @redwoodjs/internal/src/config.ts that allows us to grab the schemaPath.
[@redwoodjs/internal/src/config.ts](https://github.com/dhausser/redwood/blob/add-schema-path/packages/internal/src/config.ts) updated with a schemaPath property.

- [x]  Add a function to @redwoodjs/api that creates adds this as an argument to "db" commands.
Updated the paths according to the configuration in [packages/internal/src/paths.ts](https://github.com/dhausser/redwood/blob/add-schema-path/packages/internal/src/paths.ts)
`
      dataMigrations: path.join(BASE_DIR, schemaPath, 'dataMigrations'),
      db: path.join(BASE_DIR, schemaPath),
      dbSchema: path.join(BASE_DIR, schemaPath, 'schema.prisma'),
`

All db commands are updated with the schema path:
- [packages/cli/src/commands/dbCommands/introspect.js](https://github.com/dhausser/redwood/blob/add-schema-path/packages/cli/src/commands/dbCommands/generate.js)
- [packages/cli/src/commands/dbCommands/introspect.js](https://github.com/dhausser/redwood/blob/add-schema-path/packages/cli/src/commands/dbCommands/generate.js)
- [packages/cli/src/commands/dbCommands/save.js](https://github.com/dhausser/redwood/blob/add-schema-path/packages/cli/src/commands/dbCommands/save.js)
- [packages/cli/src/commands/dbCommands/studio.js](https://github.com/dhausser/redwood/blob/add-schema-path/packages/cli/src/commands/dbCommands/studio.js)
- [packages/cli/src/commands/dbCommands/up.js](https://github.com/dhausser/redwood/blob/add-schema-path/packages/cli/src/commands/dbCommands/up.js)

**Comment by Tobbe** [comment] 2020-10-31 22:50
> The issue is that running one of these command reverts to previous one. Meaning that I was able to unit test my changes in cli and in internal separately, though I was unable to integrate and test them both together. I have followed the [Local Package Registry Emulation](yarn rwt install @redwoodjs/dev-server) guidelines.

It's a bummer that they revert each other!
If you wanted to test them both together you could try the `rwt copy` workflow instead of the registry emulation. Then you'd just build a complete new RW version and copy it over to your test project

**Comment by dhausser** [comment] 2020-11-02 22:08
@Tobbe The testing pass using the "Copy and Watch" method is complete and confirmed working 🎉 

Screenshots attached below:

### yarn rw db generate
![generate](https://user-images.githubusercontent.com/24432220/97924561-2634ea00-1d60-11eb-8b4d-162e48dca91e.png)

### yarn rw db introspect
![introspect](https://user-images.githubusercontent.com/24432220/97924574-2a610780-1d60-11eb-9695-bff4ee51e1fd.png)

### yarn rw db save
![save](https://user-images.githubusercontent.com/24432220/97924585-2f25bb80-1d60-11eb-8d14-037b54a9ac37.png)

### yarn rw db up
![up](https://user-images.githubusercontent.com/24432220/97924601-33ea6f80-1d60-11eb-9397-5fc3917a4b5f.png)

### yarn rw db down
![down](https://user-images.githubusercontent.com/24432220/97924634-41075e80-1d60-11eb-816a-6e5df0bc7b35.png)

**Comment by Tobbe** [comment] 2020-11-02 22:54
I'll let @peterp decide, but personally this solution is not 100% what I expected. But it's really close 👍 
1. Right now (IIUC) it's still not possible to configure the file name, only the file path
2. With a name like `schemaPath` I'd expect it to point to the actual schema, not to the dir with the schema in it

My suggestion would be to keep the `schemaPath` name, but include the actual schema file name as well. So `schemaPath: './api/db/prisma.schema',`. Then for `db` and `dataMigrations` paths you could just strip the file name from the path.

But, again, I'll let @peterp decide, so don't go changing anything just yet 🙂

**Comment by dhausser** [comment] 2020-11-03 08:32
Sure, thanks for the feedback. This is fixed by [parsing schemaPath to schemaDir](https://github.com/redwoodjs/redwood/pull/1424/commits/164e9cbf1552ffa784c3de35de6e4f82719efb98).

**Closed** 2020-11-11 22:05 UTC
Labels: kind/improvement, topic: prisma
