### ISSUE TITLE
Graphql logger options not working 

### ISSUE THREAD

**Issue by pi0neerpat** [redwoodjs/redwood#5120] opened 2022-04-11 22:52 UTC
Following the docs for GraphQL logger does not produce the desired results. https://redwoodjs.com/docs/graphql#configure-the-graphql-logger

```js
export const handler = createGraphQLHandler({
  loggerConfig: {
    logger,
    options: {
      tracing: false,
      operationName: true,
      query: false,
      data: false,
    },
  },
```

However, the `query`, `data`, etc. still come through the logs. See repo example here: https://github.com/pi0neerpat/redwood-release-devops-example/blob/graphql-server-logger-troubleshooting/api/src/functions/graphql.js#L10

**Comment by jtoar** [comment] 2022-04-16 03:23
@pi0neerpat Was able to confirm this one as well. Still investigating, but it seems like we don't actually pass the options from `loggerConfig` to the logger:

https://github.com/redwoodjs/redwood/blob/ab786f5aa3e66845211f8edda398f4183191c837/packages/graphql-server/src/functions/graphql.ts#L99

Does that seem like what's going on @dthyresson? If so, this may be an easy fix since we'd just need to pass options along too

**Comment by dthyresson** [comment] 2022-04-19 12:19
I'll want to test the undefined vs false:

```
export const handler = createGraphQLHandler({
  loggerConfig: {
    logger,
    options: {
      operationName: true,
    },
  },
```

And see if query, etc is still logged.

**Comment by dthyresson** [comment] 2022-05-09 15:39
@Tobbe saw that these options were behaving correctly, but I will write tests with a mocked GraphQL handler to test these log options and if still presents then will re-assign to @pi0neerpat to reproduce. @dac09 @Tobbe and I o pair.

**Comment by pi0neerpat** [comment] 2022-05-09 22:38
![image](https://user-images.githubusercontent.com/35622595/167507640-7fa7e06e-c4af-44f4-b92d-ad683bc78b60.png)
I've recreated it here https://github.com/pi0neerpat/redwood-devops-example/tree/graphql-server-logger-troubleshooting

**Comment by dthyresson** [comment] 2022-06-07 15:45
@realStandal If you'd like, definitely. I think it works fine, just could use some tests.

**Comment by dthyresson** [comment] 2022-06-14 23:12
As part of the making rework, have confirmed that options are working as expected.

**Closed by dthyresson** 2022-06-14 23:12 UTC
Labels: bug/confirmed, topic/logging

**Comment by pi0neerpat** [comment] 2022-06-17 00:32
Are all these types of logs intended to come through? Our logs are extremely cluttered, I added a video below. 

```
api | 17:29:05 🐛 Extracting GraphQL Parameters
api | 17:29:05 🐛 Processing GraphQL Parameters
api | 17:29:05 🐛 Execution start
api | 17:29:05 🐛 
api | Received GraphQL operation:
api | 
api | 17:29:05 🐛 	 operationName:
api | 17:29:05 🐛 	 variables:
```

https://user-images.githubusercontent.com/35622595/174199339-ba7a5888-9b7c-4365-9e11-623f544cda6a.mp4

**Comment by dthyresson** [comment] 2022-06-17 01:21
These debug level logs come from within GraphQL Yoga itself. I was looking into a PR to modify it to be less chatty but hadn’t found a solution yet.

**Comment by dthyresson** [comment] 2022-06-17 01:22
To reduce clutter you can set the log level in dev to “warn”

**Comment by pi0neerpat** [comment] 2022-06-17 03:47
Ok thank you!
