### ISSUE TITLE
deleting a page doesnt delete files

### ISSUE THREAD

**Issue by wbrijesh** [redwoodjs/redwood#2506] opened 2021-05-13 10:08 UTC
after running 
`yarn rw d page pagename`

the page files are still there

**Comment by thedavidprice** [comment] 2021-05-14 16:39
Thanks for reporting this @wbrijesh This is a duplicate of https://github.com/redwoodjs/redwood/issues/2006 I'm closing this out. But would you be interested in helping with the fix? If so, please comment in #2006 and we'll help out as best we can! Also, the community chat and forums are a great place to get help as a new contributor.

- https://community.redwoodjs.com/
- https://discord.gg/jjSYEQd

**Closed by thedavidprice** 2021-05-14 16:39 UTC
Labels: bug/2-confirmed, good first issue, help wanted
