### ISSUE TITLE
[Bug?]: Existing (passing) tests against services using jest's `expect` are now failing trying to match `Date {}`

### ISSUE THREAD

**Issue by rmzg-ll** [redwoodjs/redwood#6429] opened 2022-09-19 20:18 UTC
### What's not working?

Existing (passing) tests against services using jest's `expect` are now failing trying to match `Date {}` objects:

Example output from one of the tests:
```
  ● dealTradeIns › returns a single dealTradeIn

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

    @@ -5,11 +5,11 @@
            2040,
          ],
          "e": 3,
          "s": 1,
        },
    -   "createdAt": Date {},
    +   "createdAt": 2022-09-19T20:03:33.676Z,
        "customerDealId": 42,
        "id": 17,
        "lienAmount": Decimal {
          "constructor": [Function Decimal],
          "d": Array [
    @@ -19,10 +19,10 @@
          "s": 1,
        },
        "lienHolder": "something",
        "make": "String",
        "model": "String",
    -   "updatedAt": Date {},
    +   "updatedAt": 2022-09-19T20:03:33.677Z,
        "valueOverride": null,
        "vin": "aasdfsdfsafsadf",
        "year": 2000,
      }

      21 |       const result = await dealTradeIn({ id: scenario.dealTradeIn.one.id })
      22 |
    > 23 |       expect(result).toEqual(scenario.dealTradeIn.one)
         |                      ^
      24 |     }
      25 |   )
      26 |

      at toEqual (api/src/services/dealTradeIns/dealTradeIns.test.ts:23:22)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest-preset.js:143:16)
```

The test code itself is as simple as:
```
    scenario(
      'returns a single dealTradeIn',
      async (scenario: StandardScenario) => {
        const result = await dealTradeIn({ id: scenario.dealTradeIn.one.id })

        expect(result).toEqual(scenario.dealTradeIn.one)
      }
    )
```

And the scenario is defined as:

```
>>    one: (scenario) => ({ 
        data: {
          lienAmount: 500,
          lienHolder: 'something',
          appraisedValue: 2040,
          vin: 'aasdfsdfsafsadf',
          year: 2000,
          make: 'String',
          model: 'String',
          createdAt: '2022-09-19T20:08:50.373Z',
          updatedAt: '2022-09-19T20:08:50.373Z',
          customerDeal: {
            create: {
              type: RetailDealTypes.Cash,
              customerJourney: {
                create: { stageId: scenario.stage.incomingInventory.id },
              },
              vehicle: {
                create: {
                  vin: 'String',
                  stockNumber: 'String222941',
                  make: 'String',
                  model: 'String',
                  year: 7438674,
                  stage: {
                    create: {
                      name: 'String',
                      pipelineSlug: 'Deals',
                    },
                  },
                },
              },
              stage: {
                create: {
                  name: 'String',
                  pipelineSlug: 'Deals',
                },
              },
            },
          },
        },
      }),
```

So the question is, where the heck is this `Date {}` string coming from and why is it ignoring the string already defined?

### How do we reproduce the bug?

See above

### What's your environment? (If it applies)

```shell
Debian unstable, redwood 3.1, node 18.7
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment] 2022-09-20 02:47
@rmzg-ll have you tried updating the snapshots? (With `yarn rw test -u`.) I'm thinking this may be because jest [changed the default snapshot format](https://jestjs.io/blog/2022/08/25/jest-29). Also I'm assuming you're seeing this after having upgraded from v2 to v3 right? We bumped Jest two major versions.

**Comment by rmzg-ll** [comment] 2022-09-22 17:54
Yes, I tried repeatedly to run `test -u` and `-clearCache` where appropriate.

**Comment by cannikin** [comment] 2022-09-23 17:51
Hmm, what do you get if you take a `typeof result.createdAt` versus `typeof scenario.one.createdAt`? It looks from the error message that the scenario is a string but the result (from Prisma) is an actual Date object? I'm not sure how it would know to format it like `2022-09-19T20:03:33.677Z` instead of the default `Fri Sep 23 2022 10:50:48 GMT-0700 (Pacific Daylight Time)` when you to a `toString()` on a date.

I don't imagine that Prisma would change the format of dates it's returning. I wonder if we upgraded something (Jest?) that changes how that date comparison happens?

**Comment by Tobbe** [comment] 2022-09-23 21:03
We have this PR that seems related https://github.com/redwoodjs/redwood/pull/6394

Prisma actually does let you pass a string in, and will return a Date back out.

**Comment by esteban-url** [comment] 2022-09-24 19:54
I saw something similar today while testing #6394. but i don't think the PR will fix it. as I can reproduce it on my test project synced to my frameworks local branch.

I thinks this is a symptom of something deeper, and has to do with the deep equality check. So, @rmzg-ll maybe one of your relationships isn't working, or you are not including it in the returned object, so that causes the `Date {}` "decoy"(?)

I'm sorry I can't give any details or possible solutions as I haven't looked too deep into it, but maybe this helps! 

I've also been able to reproduce it on a green field project. These are the steps I just took:

1. created a new project (no typescript)
    
    ```sh
    yarn create redwood-app _ttt 
    ```

2. added a model to `schema.prisma`

    ```prisma
    datasource db {
      provider = "sqlite"
      url      = env("DATABASE_URL")
    }
    
    generator client {
      provider      = "prisma-client-js"
      binaryTargets = "native"
    }
    model Notification {
      id            Int      @id @default(autoincrement())
      date          DateTime
      title         String
      body          String
      bool          Boolean
      intNumber     Int
      bigIntNumber  BigInt
      decimalNumber Decimal
      createdAt     DateTime @default(now())
    }
    
    ```

3. created a migration
4. generated the sdl for the `Notification` model
5. fixed the dates tests, by adding a `new Date(...)` declaration

    ```js
    expect(result.date).toEqual(new Date('2022-09-24T19:27:38Z'))
    ```

6. ran api tests with `yarn rw test api` and got this (notice the decimal error, i think this is relevant):

    ```sh
    FAIL   api  api/src/services/notifications/notifications.test.js
      ● notifications › returns a single notification
    
        expect(received).toEqual(expected) // deep equality
    
        - Expected  - 2
        + Received  + 2
    
        @@ -1,11 +1,11 @@
          Object {
            "bigIntNumber": 2417473n,
            "body": "String",
            "bool": true,
        -   "createdAt": Date {}, // <<< SAME ERROR as @rmzg-ll 
        -   "date": Date {},  // <<< SAME ERROR as @rmzg-ll 
        +   "createdAt": 2022-09-24T19:33:28.600Z,
        +   "date": 2022-09-24T19:27:39.000Z,
            "decimalNumber": Decimal {
              "constructor": [Function Decimal],
              "d": Array [
                3947353,
                7212319,
    
          23 |     const result = await notification({ id: scenario.notification.one.id })
          24 |
        > 25 |     expect(result).toEqual(scenario.notification.one)
             |                    ^
          26 |   })
          27 |
          28 |   scenario('creates a notification', async () => {
    
          at toEqual (api/src/services/notifications/notifications.test.js:25:20)
          at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest-preset.js:143:16)
    
      ● notifications › creates a notification
    
        expect(received).toEqual(expected) // deep equality
    
        Expected: 9798105.65164411
        Received: "9798105.651644111"
    
          45 |     expect(result.intNumber).toEqual(4050962)
          46 |     expect(result.bigIntNumber).toEqual(9753538n)
        > 47 |     expect(result.decimalNumber).toEqual(9798105.65164411)
             |                                  ^
          48 |   })
          49 |
          50 |   scenario('updates a notification', async (scenario) => {
    
          at toEqual (api/src/services/notifications/notifications.test.js:47:34)
          at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest-preset.js:143:16)
    ```
Then I followed this extra step to "fix" it: 

7. comment out the Decimal field from the schema.
8. create a migration
9. regenerate the sdl
10. fix the date assertions 

the tests now pass! 🤯

```sh
Test Suites: 3 passed, 3 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        1.643 s
Ran all test suites.
```

**Comment by Tobbe** [comment] 2022-09-26 06:38
I think I know what's going on. I'll start working on a fix in a couple of days. 

As a workaround, could you change `lienAmount   Decimal` to `lienAmount   Float` in your `schema.prisma` file?

**Comment by arimendelow** [comment] 2022-09-26 17:23
I have the exact same issue with testing models that have dateTime. Do we have a workaround for that yet?

**Comment by Tobbe** [comment] 2022-10-01 15:31
@esteban-url Thanks a lot for your clear and detailed reproduction steps. Made it super easy to work on a fix for this issue.

@rmzg-ll I hope I fixed this issue in #6491 

@arimendelow DateTime values should have been fixed in #6394. If you upgrade to canary it should hopefully work for you (be aware that canary builds are unstable though, so be careful 🙂) And don't forget to regenerate the services+tests after upgrading.

**Comment by arimendelow** [comment] 2022-10-01 15:53
Sounds good! Will there be an upgrade guide? If we've put a lot of work into these services and tests we don't want to just regenerate them.

Thanks for all your hard work! :)

**Comment by Tobbe** [comment] 2022-10-02 13:12
@arimendelow The fix is all in the updated generator. So if you don't want to regenerate everything, which is totally understandable, you'll have to manually fix things. And if so, there's no need to upgrade. You can do it with your current code.

You'll need to change your api/src/services/model/model.test.js files like this:

```dif
-    expect(result.date).toEqual('2022-10-03T12:59:56Z')
+    expect(result.date).toEqual(new Date('2022-10-03T12:59:56Z'))
```

**Closed** 2022-10-03 22:25 UTC
Labels: bug/needs-info
