### ISSUE TITLE
Use the add plugin to add the Prisma JSON type instead of hacking codegen

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#6096] opened 2022-08-01 15:55 UTC
See https://github.com/redwoodjs/redwood/pull/5796#issuecomment-1176380719

See [graphql-code-generator.com/plugins/add](https://www.graphql-code-generator.com/plugins/add)

From Discord:

![image](https://user-images.githubusercontent.com/1051633/182190488-f932d4dc-8d73-4ae7-9b9d-ed7c6d5f0d42.png)

Things to check:

- [x] `web/types/graphql.d.ts` imports the `Prisma` namespace
- [ ] `api/types/graphql.d.ts` imports `Prisma` namespace and maps the types. 
- [ ]  In `api/types/graphql.d.ts` - no other red squiggles

**Comment by adriatic** [comment] 2022-08-03 14:57
@dac09 @dthyresson 

### Three comments:

1. I am assuming that this issue will be fixed "officially" hacking codegen. Is this true?
In the meantime I would appreciate to know at what point should I use `https://www.graphql-code-generator.com/plugins/other/add` workaround. Can I do it **after** my app fails with `The type ArticlesQuery does not exist in types/graphql`?

2. Your advice below is not helping - the problem remains the same

    > You just have have to run yarn rw g types or have your dev server running. See more info on generating types here: https://redwoodjs.com/docs/typescript#auto-generated-types

3. Your other observation below is not correct. I presented the proof in my original report

    > I don't believe the Prisma error actually has any consequences on Redwood applications, it's a bug in the generated types but actually doesn't break anything within your application.

If the core team prefers me not reporting problems with RW, that is certainly fair - I would be grateful it I am told that directly, without leaving any doubts 😄

**Comment by dthyresson** [comment] 2022-08-03 15:02
@adriatic Nick. We’ve triaged and assigned this issue. In fact, it is next on my list to work on.

**Comment by adriatic** [comment] 2022-08-03 15:17
Sorry for creating a storm in a teapot - I wrote the [above comments](https://github.com/redwoodjs/redwood/issues/6096#issuecomment-1204061491) as a reaction to @dac09's statement

> I don't believe the Prisma error actually has any consequences on Redwood applications, it's a bug in the generated types but actually doesn't break anything within your application.

which lead me to conclude that this is such minor issue that it could wait. Seemingly I am not patient enough - sorry @dthyresson

**Comment by dac09** [comment] 2022-08-03 15:35
@adriatic I suggest you please double check the error you're seeing. We understand there's a red underline under Prisma - 100% clear - but that red underline does **not** cause the import problem. You'll just have to take my word for this - because I've triple checked our CI and test projects. 

> Your advice below is not helping - the problem remains the same

Sorry to hear - I'm not sure what else to suggest. Perhaps its a case of needing to restart your VS Code.

Would very much appreciate if you didn't individually tag us on every post you write too, thank you.

**Comment by adriatic** [comment] 2022-08-03 17:44
I understand that I did not provide the reproducible problem, and I understand that my trustworthiness is below the level needed to take my gut feelings as a proof (you should really not do that, regardless of who's statement is being questioned.

My pesky habit to tag people directly is a consequence of my fear that an issue reported by me would not be seriously considered. Thank for not advising me not to post anything, though 😄

**Comment by adriatic** [comment] 2022-08-04 16:26
I understand, thank you

**Closed** 2022-08-04 19:25 UTC
Labels: bug/confirmed
