### ISSUE TITLE
Update Prisma2 preview024

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#279] opened 2020-03-17 18:14 UTC
https://github.com/prisma/prisma2/releases

Sorry/not-sorry @cannikin 😢

**Comment by thedavidprice** [comment] 2020-03-20 17:10
Probably need to make sure this work is complete before merging #289

**Comment by thedavidprice** [comment] 2020-03-20 18:57
## Prisma Client Generate Error
@cannikin @peterp @nikolasburk Could I get your eyes on this one for suggestions about what might be causing this?

My local tests are giving errors on the initial `yarn rw dev` command.

**Here’s my rwjs/redwood branch running the 3 prisma packages at preview024:**
https://github.com/redwoodjs/redwood/tree/dsp-prisma-upgrade-preview024

**And here’s my local App test repo:**
https://github.com/thedavidprice/rwjs-prisma-preview024.git

_Note:_ I have also added the three Prisma packages to the root `package.json` of my app to confirm things are running on the latest.

### To Setup Locally
- in rwjs/redwood, you’ll need to `yarn link` the packages (I did all of ‘em to isolate things)
- in App, you can use this beast to link:
```terminal
yarn link @redwoodjs/api & yarn link @redwoodjs/cli & yarn link @redwoodjs/core & yarn link @redwoodjs/dev-server & yarn link @redwoodjs/eslint-config & yarn link @redwoodjs/eslint-plugin-redwood & yarn link @redwoodjs/internal & yarn link @redwoodjs/router & yarn link @redwoodjs/web
```

### Error
Running `yarn rw dev` results in the following cli error (note: browser load fine and console is clean):
```terminal
11:42:32 api | /Users/price/Repos/redwoodjs-redwood/packages/api/node_modules/@prisma/client/index.js:3
11:42:32 api |     throw new Error(
11:42:32 api |     ^
11:42:32 api |
11:42:32 api | Error: @prisma/client did not initialize yet. Please run "prisma2 generate" and try to import it again.
11:42:32 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
11:42:32 api |     at new PrismaClient (/Users/price/Repos/redwoodjs-redwood/packages/api/node_modules/@prisma/client/index.js:3:11)
11:42:32 api |     at Object.<anonymous> (/Users/price/Repos/redwoodjs-redwood/packages/api/src/dbInstance.ts:3:19)
11:42:32 api |     at Module._compile (internal/modules/cjs/loader.js:1157:30)
11:42:32 api |     at Module._compile (/Users/price/Repos/redwoodjs-redwood/node_modules/pirates/lib/index.js:99:24)
11:42:32 api |     at Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
11:42:32 api |     at Object.newLoader [as .js] (/Users/price/Repos/redwoodjs-redwood/node_modules/pirates/lib/index.js:104:7)
11:42:32 api |     at Module.load (internal/modules/cjs/loader.js:1001:32)
11:42:32 api |     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
11:42:32 api |     at Module.require (internal/modules/cjs/loader.js:1043:19)
11:42:32 api |     at require (internal/modules/cjs/helpers.js:77:18)
error Command failed with exit code 1.
```

**Comment by weaversam8** [comment] 2020-03-20 23:09
@danielrw7 has also been experiencing this issue in a project we've been working on. He's running on WSL, and has tried to install `preview024` manually. 

I manually installed `preview024`. You can see prisma/prisma-client-js#582, a dupe I created before I realized I wasn't running a current version. Specifically, you can see [this comment](https://github.com/prisma/prisma-client-js/issues/582#issuecomment-600302408) to see how I installed `preview024`. (I also added it to the `devDependencies`.) I'm able to run `yarn rw dev` on Windows (Windows 10, not running inside WSL) just fine, in the same project where @danielrw7 is having this issue.

**Comment by weaversam8** [comment] 2020-03-21 00:05
Dug into this a little bit more.

Running `prisma2 generate` (which is run by `rw db generate` IIRC) will read the schema and generate the client code (specific to your schema) and save it as the module `@prisma/client`. This is saved in the root `node_modules` directory of the project. 

If you were to install `@prisma/client` from NPM, you'd get the version of the code that prints a simple error, seen in [this snapshot](https://github.com/prisma/prisma-client-js/blob/1640e91e53dd590db9d84dafd1c9430911376879/packages/photon/index.js) of the [prisma/prisma-client-js](https://github.com/prisma/prisma-client-js/) repo. This is stub code designed to be overwritten.

What seems to be happening is that when `api` imports `@prisma/client`, it's importing the version installed in the `node_modules` folder of the `@redwoodjs/api` package, instead of the `@prisma/client` version installed in the root of the repository.

**Comment by peterp** [comment] 2020-03-21 11:26
@thedavidprice This happens when running `yarn link @redwoodjs/api`, and @weaversam8 gives a good account of the error: 

The client is generated in `redwood.git/node_modules/@prisma/client`, when it should be generated in `my-redwood-app/node_modules/@prisma/client`

We really need to get the local development/ copy command working instead of linking; or we need to come up with a workflow that allow us to publish to a "fake npm repository."

**Comment by peterp** [comment] 2020-03-21 12:22
@weaversam8 last suggestion would be the most appropriate:
> Update the output path for the generator step. I'm not sure what path we'd update it to... should it be.

We could change the `prisma.schema` files output field to be the appropriate `node_module` directory. I do not know if this output path is relative to the location of the `prisma.schema` file so we would have to test it out a bit.

https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#generators-optional

**Comment by weaversam8** [comment] 2020-03-21 15:47
@peterp @thedavidprice I don't think the issue is unique to the linked version when testing.

You wrote:
> The client is generated in `redwood.git/node_modules/@prisma/client`, when it should be generated in `my-redwood-app/node_modules/@prisma/client`

In our app, the client is generated in `node_modules/@prisma/client` in the root of the app. This is the default output location for the `prisma-client-js` generator provider. I believe the issue is that `@redwoodjs/api` also declares `@prisma/client` as a dependency, so the stub version is being installed and used in the TS compilation step, instead of the `@prisma/client` version installed in the root of the application.

**Comment by weaversam8** [comment] 2020-03-21 16:44
@peterp - I just published [weaversam8/redwood-279-poc](https://github.com/weaversam8/redwood-279-poc), which can serve as a minimum replication case if you want to test different solutions. It doesn't use any linking and still manages to reproduce the error.

**Comment by weaversam8** [comment] 2020-03-21 17:14
## Temporary workaround

I found a temporary workaround for this issue, if anyone is running up against this in their development, like I was. Deleting `{project_root}/node_modules/@redwood/api/node_modules/@prisma/client` will force `@redwoodjs/api`'s [`require("@prisma/client");`](https://github.com/redwoodjs/redwood/blob/4779f50660fd7a273bf5ae57fa02cd712ca2867f/packages/api/src/dbInstance.ts#L1) to resolve to the generated `@prisma/client` which is located in the `node_modules` in the root of the repository.

**Comment by peterp** [comment] 2020-03-22 08:23
@weaversam8 Thanks for the repo, and thanks for chiming in here, it's appreciated. 

I missed the context that you were trying to update Prisma yourself.

I think we should generally advise against updating Prisma since we've got a bunch of internal tooling that's pinned to a particular version. Prisma is a fast-moving target and introduces breaking changes reasonably regularly, and once they're stable, that may change.

We're merging a way to instantiate the `dbInstance` in #298. With that, you would be able to generate the Prisma client into a specific place and subsequently import it from that place.

**Comment by peterp** [comment] 2020-03-22 12:09
This is all merged. 

@weaversam8 I've tested the new way that we're automatically importing the Prisma client and it removes the ambiguity from before.

**Closed by peterp** 2020-03-22 12:09 UTC
Labels: kind/improvement, topic: prisma

**Comment by thedavidprice** [comment] 2020-03-23 22:39
Thanks for the help on this, gents.

@peterp what I'm still unclear on is, in the future, how do we locally test new versions of Prisma2 before upgrading?

Is this what needs to be done per @weaversam8 above?
>I found a temporary workaround for this issue, if anyone is running up against this in their development, like I was. Deleting {project_root}/node_modules/@redwoodjs/api/node_modules/@prisma/client will force @redwoodjs/api's require("@prisma/client"); to resolve to the generated @prisma/client which is located in the node_modules in the root of the repository.

If so, this should probably be documented 'cause a lot of Prisma2 updates are coming down the pipe...
