### ISSUE TITLE
[Bug]: useAuth (dbAuth) : the "loading" state is not updated during the call to signUp()

### ISSUE THREAD

**Issue by titib** [redwoodjs/redwood#6750] opened 2022-10-27 09:32 UTC
### What's not working?

I'm using dbAuth.
The loading state is not updated during the call to signUp().
Notice that It's not the case for the call to logIn(). With logIn(), everything works as expected: the loading state is updated.

```
const { isAuthenticated, loading, signUp } = useAuth();

...

signUp();

...

// "loading" does not change its state. It's always false
{ loading && <p>Loading...</p>}
```

### How do we reproduce the bug?

Start a new project
Setup dbAuth
Generate one page
In the page, add a sign up button that calls signUp() and display the "loading" state

### What's your environment? (If it applies)

```shell
Redwood 3.2.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment] 2022-11-08 21:13
If I'm reading the code correctly this is an issue with all auth providers, not just dbAuth.
I've got a draft PR here: https://github.com/redwoodjs/redwood/pull/6832

It's just dry coded. I'll need to discuss this one with the team. It could be that it's already working as intended. 
"Loading..." is often used when the authenticated state of the user is about to change. While signing up that might not be the case. The user might not be immediately logged in after signing up and in that case Loading... might not be what we want. Happy to hear any feedback/ideas.

**Comment by titib** [comment] 2022-11-08 21:55
I'm developing a mobile app (CapacitorJs + RedwoodJs). The redwood web part is encapsulated into Capacitor and talks to the redwood api part. 
On a slow network or bad infrastructure, it can take more than 2 seconds to sign up. From the user's perspective, there is no indicator showing that the app is still signing up.

**Comment by Tobbe** [comment] 2022-11-09 06:23
I brought this up with the team, and there was an overwhelming consensus that `loading` is only for loading the authenticated state of the user. 

For many apps signup is a multi step process. Therefore we suggest you handle "loading" for signup on your own. So just set a state or context `isSignignUp` variable to `true` before you start the signup process and toggle it to `false` when the user has finished signup. So I'm going to close this issue.

That said, your comment about using capacitor got me really excited! How is that working for you? Was it difficult to set up? Anything else that's been problematic? A blog post or something describing the process would be awesome! 😉

**Closed by Tobbe** 2022-11-09 06:23 UTC
Labels: bug/needs-info

**Comment by titib** [comment] 2022-11-09 08:36
Thank you for your fast answer. I'll handle the intermediate state myself.

Concerning Capacitor, I've spent a lot of time to integrate both Capacitor and Redwood (especially with the  "livereload" feature). For the moment, I target Android only. I don't have a Mac to test it on iOS. Writing an article about it is on my todo list. I hope to have some time to work on it in the following weeks.
Once everything is set up correctly, it is just a classic redwood app with calls to Capacitor's plugins.
The unknown difficulty I see is the social logins. I don't know how Capacitor handles redirections and callbacks. I don't think I can re-use redwood's work on authentication with third parties. That's why I use only dbAuth for the moment.
