### ISSUE TITLE
[Bug?]: Storybook does not work

### ISSUE THREAD

**Issue by nandumoura** [redwoodjs/redwood#10253] opened 2024-03-17 20:13 UTC
### What's not working?

When running the `yarn rw sb` command, the storybook installation breaks when the CLI installation starts

the folowwing error
```bash
➜   yarn rw sb
Initializing the Mock Service Worker at "/home/archn/Projects/Redwood/my-redwood-project-test-storybook/web/public"...

Service Worker successfully created!
/home/archn/Projects/Redwood/my-redwood-project-test-storybook/web/public/mockServiceWorker.js

Continue by creating a mocking definition module in your application:

https://mswjs.io/docs/getting-started/mocks

@storybook/cli v7.6.17

info => Serving static files from /home/archn/Projects/Redwood/my-redwood-project-test-storybook/web/public at /
info => Starting manager..
WARN No story files found for the specified pattern: src/**/*.stories.@(js|jsx|ts|tsx|mdx)
✘ [ERROR] Could not resolve "@storybook/addon-actions/manager"

    ../node_modules/@storybook/addon-essentials/dist/actions/manager.js:1:14:
      1 │ export * from '@storybook/addon-actions/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-actions" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-actions/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-backgrounds/manager"

    ../node_modules/@storybook/addon-essentials/dist/backgrounds/manager.js:1:14:
      1 │ export * from '@storybook/addon-backgrounds/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-backgrounds" here because it's
  not listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-backgrounds/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-controls/manager"

    ../node_modules/@storybook/addon-essentials/dist/controls/manager.js:1:14:
      1 │ export * from '@storybook/addon-controls/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-controls" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-controls/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-highlight"

    ../node_modules/@storybook/addon-a11y/dist/manager.js:8:26:
      8 │ import { HIGHLIGHT } from '@storybook/addon-highlight';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-highlight" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-highlight" as external to exclude it from the bundle,
  which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-measure/manager"

    ../node_modules/@storybook/addon-essentials/dist/measure/manager.js:1:14:
      1 │ export * from '@storybook/addon-measure/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-measure" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-measure/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-outline/manager"

    ../node_modules/@storybook/addon-essentials/dist/outline/manager.js:1:14:
      1 │ export * from '@storybook/addon-outline/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-outline" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-outline/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-toolbars/manager"

    ../node_modules/@storybook/addon-essentials/dist/toolbars/manager.js:1:14:
      1 │ export * from '@storybook/addon-toolbars/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-toolbars" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-toolbars/manager" as external to exclude it from the
  bundle, which will remove this error.

✘ [ERROR] Could not resolve "@storybook/addon-viewport/manager"

    ../node_modules/@storybook/addon-essentials/dist/viewport/manager.js:1:14:
      1 │ export * from '@storybook/addon-viewport/manager';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@storybook/addon-viewport" here because it's not
  listed as a dependency of this package:

    ../../../../.pnp.cjs:36:31:
      36 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "@storybook/addon-viewport/manager" as external to exclude it from the
  bundle, which will remove this error.

Error: Build failed with 8 errors:
../node_modules/@storybook/addon-a11y/dist/manager.js:8:26: ERROR: Could not resolve "@storybook/addon-highlight"
../node_modules/@storybook/addon-essentials/dist/actions/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-actions/manager"
../node_modules/@storybook/addon-essentials/dist/backgrounds/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-backgrounds/manager"
../node_modules/@storybook/addon-essentials/dist/controls/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-controls/manager"
../node_modules/@storybook/addon-essentials/dist/measure/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-measure/manager"
...
    at failureErrorWithLog (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:1649:15)
    at /home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:1056:7)
    at /home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

Command failed with exit code 1: yarn storybook dev --config-dir "/home/archn/Projects/Redwood/my-redwood-project-test-storybook/node_modules/@redwoodjs/testing/config/storybook" --webpack-stats-json --port 7910 --no-version-updates
```

### How do we reproduce the bug?

`yarn rw sb` or `yarn redwood storybook`

### What's your environment? (If it applies)

```shell
System:
    OS: Linux 6.7 undefined
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /tmp/xfs-4de4cd27/node
    Yarn: 4.1.1 - /tmp/xfs-4de4cd27/yarn
  Databases:
    SQLite: 3.42.0 - /home/linuxbrew/.linuxbrew/bin/sqlite3
  npmPackages:
    @redwoodjs/cli-storybook: 7.1.3 => 7.1.3
    @redwoodjs/core: 7.1.3 => 7.1.3
    @redwoodjs/project-config: 7.1.3 => 7.1.3
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment] 2024-03-19 07:31
Hey @nandumoura :wave:

I am having a little trouble reproducing this locally. I followed the followin steps:
1. `yarn create redwood-app debug-storybook`
2. `cd debug-storybook`
3. `yarn`
4. `yarn rw info` - just to confirm similar conditions as you listed
5. `yarn rw storybook`

Storybook was able to successfully download and start for me. 

One thing I found potentially interesting is that `Yarn: 4.1.1 - /tmp/xfs-4de4cd27/yarn` was listed in your `yarn rw info` output. I might have expected yarn to be at version `4.1.0` since that is what is requested in the package json file (`"packageManager": "yarn@4.1.0"`)

**Comment by nandumoura** [comment] 2024-03-19 20:10
which yarn
/home/archn/.nvm/versions/node/v20.11.1/bin/yarn
I try another versions of node too like v20.1.0

 yarn config
├─ cacheFolder
│  ├─ Description: Folder where the cache files must be written
│  ├─ Source: <internal>
│  └─ Value: '/home/archn/.yarn/berry/cache'
│
├─ cacheMigrationMode
│  ├─ Description: Defines the conditions under which Yarn upgrades should cause the cache archives to be regenerated.
│  ├─ Source: <default>
│  └─ Value: 'always'
│
├─ changesetBaseRefs
│  ├─ Description: The base git refs that the current HEAD is compared against when detecting changes. Supports git branches, tags, and commits.
│  ├─ Source: <default>
│  └─ Value: [ 'master', 'origin/master', ... 4 more items ]
│
├─ changesetIgnorePatterns
│  ├─ Description: Array of glob patterns; files matching them will be ignored when fetching the changed files
│  ├─ Source: <default>
│  └─ Value: []
│
├─ checksumBehavior
│  ├─ Description: Enumeration defining what to do when a checksum doesn't match expectations
│  ├─ Source: <default>
│  └─ Value: 'throw'
│
├─ cloneConcurrency
│  ├─ Description: Maximal number of concurrent clones
│  ├─ Source: <default>
│  └─ Value: 2
│
├─ compressionLevel
│  ├─ Description: Zip files compression level, from 0 to 9 or mixed (a variant of 9, which stores some files uncompressed, when compression doesn't yield good results)
│  ├─ Source: /home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarnrc.yml
│  └─ Value: 0
│
├─ constraintsPath
│  ├─ Description: The path of the constraints file.
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/constraints.pro'
│
├─ defaultLanguageName
│  ├─ Description: Default language mode that should be used when a package doesn't offer any insight
│  ├─ Source: <default>
│  └─ Value: 'node'
│
├─ defaultProtocol
│  ├─ Description: Default resolution protocol used when resolving pure semver and tag ranges
│  ├─ Source: <default>
│  └─ Value: 'npm:'
│
├─ defaultSemverRangePrefix
│  ├─ Description: The default save prefix: '^', '~' or ''
│  ├─ Source: <default>
│  └─ Value: '^'
│
├─ deferredVersionFolder
│  ├─ Description: Folder where are stored the versioning files
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarn/versions'
│
├─ enableColors
│  ├─ Description: If true, the CLI is allowed to use colors in its output
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableConstraintsChecks
│  ├─ Description: If true, constraints will run during installs
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableGlobalCache
│  ├─ Description: If true, the system-wide cache folder will be used regardless of `cache-folder`
│  ├─ Source: /home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarnrc.yml
│  └─ Value: true
│
├─ enableHardenedMode
│  ├─ Description: If true, automatically enable --check-resolutions --refresh-lockfile on installs
│  ├─ Source: <default>
│  └─ Value: null
│
├─ enableHyperlinks
│  ├─ Description: If true, the CLI is allowed to use hyperlinks in its output
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableImmutableCache
│  ├─ Description: If true, the cache is reputed immutable and actions that would modify it will throw
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableImmutableInstalls
│  ├─ Description: If true (the default on CI), prevents the install command from modifying the lockfile
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableInlineBuilds
│  ├─ Description: If true, the CLI will print the build output on the command line
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableInlineHunks
│  ├─ Description: If true, the installs will print unmatched patch hunks
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableMessageNames
│  ├─ Description: If true, the CLI will prefix most messages with codes suitable for search engines
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableMirror
│  ├─ Description: If true, the downloaded packages will be retrieved and stored in both the local and global folders
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableNetwork
│  ├─ Description: If false, Yarn will refuse to use the network if required to
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableOfflineMode
│  ├─ Description: If true, Yarn will attempt to retrieve files and metadata from the global cache rather than the network
│  ├─ Source: <default>
│  └─ Value: false
│
├─ enableProgressBars
│  ├─ Description: If true, the CLI is allowed to show a progress bar for long-running events
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableScripts
│  ├─ Description: If true, packages are allowed to have install scripts by default
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableStrictSettings
│  ├─ Description: If true, unknown settings will cause Yarn to abort
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableStrictSsl
│  ├─ Description: If false, SSL certificate errors will be ignored
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableTelemetry
│  ├─ Description: If true, telemetry will be periodically sent, following the rules in https://yarnpkg.com/advanced/telemetry
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableTimers
│  ├─ Description: If true, the CLI is allowed to print the time spent executing commands
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableTips
│  ├─ Description: If true, installs will print a helpful message every day of the week
│  ├─ Source: <default>
│  └─ Value: true
│
├─ enableTransparentWorkspaces
│  ├─ Description: If false, Yarn won't automatically resolve workspace dependencies unless they use the `workspace:` protocol
│  ├─ Source: <default>
│  └─ Value: true
│
├─ globalFolder
│  ├─ Description: Folder where all system-global files are stored
│  ├─ Source: <default>
│  └─ Value: '/home/archn/.yarn/berry'
│
├─ httpProxy
│  ├─ Description: URL of the http proxy that must be used for outgoing http requests
│  ├─ Source: <default>
│  └─ Value: null
│
├─ httpRetry
│  ├─ Description: Retry times on http failure
│  ├─ Source: <default>
│  └─ Value: 3
│
├─ httpTimeout
│  ├─ Description: Timeout of each http request in milliseconds
│  ├─ Source: <default>
│  └─ Value: 60000
│
├─ httpsCaFilePath
│  ├─ Description: A path to a file containing one or multiple Certificate Authority signing certificates
│  ├─ Source: <default>
│  └─ Value: null
│
├─ httpsCertFilePath
│  ├─ Description: Path to file containing certificate chain in PEM format
│  ├─ Source: <default>
│  └─ Value: null
│
├─ httpsKeyFilePath
│  ├─ Description: Path to file containing private key in PEM format
│  ├─ Source: <default>
│  └─ Value: null
│
├─ httpsProxy
│  ├─ Description: URL of the http proxy that must be used for outgoing https requests
│  ├─ Source: <default>
│  └─ Value: null
│
├─ ignorePath
│  ├─ Description: If true, the local executable will be ignored when using the global one
│  ├─ Source: <default>
│  └─ Value: false
│
├─ immutablePatterns
│  ├─ Description: Array of glob patterns; files matching them won't be allowed to change during immutable installs
│  ├─ Source: <default>
│  └─ Value: []
│
├─ initEditorConfig
│  ├─ Description: Extra rules to define in the generator editorconfig
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ initFields
│  ├─ Description: Additional fields to set when creating packages via the init command
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ initScope
│  ├─ Description: Scope used when creating packages via the init command
│  ├─ Source: <default>
│  └─ Value: null
│
├─ injectEnvironmentFiles
│  ├─ Description: List of all the environment files that Yarn should inject inside the process when it starts
│  ├─ Source: <default>
│  └─ Value: [ '.env.yarn?' ]
│
├─ installStatePath
│  ├─ Description: Path of the file where the install state will be persisted
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarn/install-state.gz'
│
├─ lastUpdateCheck
│  ├─ Description: Last timestamp we checked whether new Yarn versions were available
│  ├─ Source: <default>
│  └─ Value: null
│
├─ logFilters
│  ├─ Description: Overrides for log levels
│  ├─ Source: <default>
│  └─ Value: []
│
├─ networkConcurrency
│  ├─ Description: Maximal number of concurrent requests
│  ├─ Source: <default>
│  └─ Value: 50
│
├─ networkSettings
│  ├─ Description: Network settings per hostname (glob patterns are supported)
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ nmHoistingLimits
│  ├─ Description: Prevents packages to be hoisted past specific levels
│  ├─ Source: <default>
│  └─ Value: 'none'
│
├─ nmMode
│  ├─ Description: Defines in which measure Yarn must use hardlinks and symlinks when generated `node_modules` directories.
│  ├─ Source: /home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarnrc.yml
│  └─ Value: 'hardlinks-local'
│
├─ nmSelfReferences
│  ├─ Description: Defines whether the linker should generate self-referencing symlinks for workspaces.
│  ├─ Source: <default>
│  └─ Value: true
│
├─ nodeLinker
│  ├─ Description: The linker used for installing Node packages, one of: "pnp", "pnpm", or "node-modules"
│  ├─ Source: /home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarnrc.yml
│  └─ Value: 'node-modules'
│
├─ npmAlwaysAuth
│  ├─ Description: URL of the selected npm registry (note: npm enterprise isn't supported)
│  ├─ Source: <default>
│  └─ Value: false
│
├─ npmAuditExcludePackages
│  ├─ Description: Array of glob patterns of packages to exclude from npm audit
│  ├─ Source: <default>
│  └─ Value: []
│
├─ npmAuditIgnoreAdvisories
│  ├─ Description: Array of glob patterns of advisory IDs to exclude from npm audit
│  ├─ Source: <default>
│  └─ Value: []
│
├─ npmAuditRegistry
│  ├─ Description: Registry to query for audit reports
│  ├─ Source: <default>
│  └─ Value: null
│
├─ npmAuthIdent
│  ├─ Description: Authentication identity for the npm registry (_auth in npm and yarn v1)
│  ├─ Source: <default>
│  └─ Value: null
│
├─ npmAuthToken
│  ├─ Description: Authentication token for the npm registry (_authToken in npm and yarn v1)
│  ├─ Source: <default>
│  └─ Value: null
│
├─ npmPublishAccess
│  ├─ Description: Default access of the published packages
│  ├─ Source: <default>
│  └─ Value: null
│
├─ npmPublishRegistry
│  ├─ Description: Registry to push packages to
│  ├─ Source: <default>
│  └─ Value: null
│
├─ npmRegistries
│  ├─ Description: Settings per registry
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ npmRegistryServer
│  ├─ Description: URL of the selected npm registry (note: npm enterprise isn't supported)
│  ├─ Source: <default>
│  └─ Value: 'https://registry.yarnpkg.com'
│
├─ npmScopes
│  ├─ Description: Settings per package scope
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ packageExtensions
│  ├─ Description: Map of package corrections to apply on the dependency tree
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ patchFolder
│  ├─ Description: Folder where the patch files must be written
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarn/patches'
│
├─ pnpEnableEsmLoader
│  ├─ Description: If true, Yarn will generate an ESM loader (`.pnp.loader.mjs`). If this is not explicitly set Yarn tries to automatically detect whether ESM support is required.
│  ├─ Source: <default>
│  └─ Value: false
│
├─ pnpEnableInlining
│  ├─ Description: If true, the PnP data will be inlined along with the generated loader
│  ├─ Source: <default>
│  └─ Value: true
│
├─ pnpFallbackMode
│  ├─ Description: If true, the generated PnP loader will follow the top-level fallback rule
│  ├─ Source: <default>
│  └─ Value: 'dependencies-only'
│
├─ pnpIgnorePatterns
│  ├─ Description: Array of glob patterns; files matching them will use the classic resolution
│  ├─ Source: <default>
│  └─ Value: []
│
├─ pnpMode
│  ├─ Description: If 'strict', generates standard PnP maps. If 'loose', merges them with the n_m resolution.
│  ├─ Source: <default>
│  └─ Value: 'strict'
│
├─ pnpShebang
│  ├─ Description: String to prepend to the generated PnP script
│  ├─ Source: <default>
│  └─ Value: '#!/usr/bin/env node'
│
├─ pnpUnpluggedFolder
│  ├─ Description: Folder where the unplugged packages must be stored
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarn/unplugged'
│
├─ preferDeferredVersions
│  ├─ Description: If true, running `yarn version` will assume the `--deferred` flag unless `--immediate` is set
│  ├─ Source: <default>
│  └─ Value: false
│
├─ preferInteractive
│  ├─ Description: If true, the CLI will automatically use the interactive mode when called from a TTY
│  ├─ Source: <default>
│  └─ Value: false
│
├─ preferReuse
│  ├─ Description: If true, `yarn add` will attempt to reuse the most common dependency range in other workspaces.
│  ├─ Source: <default>
│  └─ Value: false
│
├─ preferTruncatedLines
│  ├─ Description: If true, the CLI will truncate lines that would go beyond the size of the terminal
│  ├─ Source: <default>
│  └─ Value: false
│
├─ progressBarStyle
│  ├─ Description: Which style of progress bar should be used (only when progress bars are enabled)
│  ├─ Source: <default>
│  └─ Value: undefined
│
├─ rcFilename
│  ├─ Description: Name of the files where the configuration can be found
│  ├─ Source: <default>
│  └─ Value: '.yarnrc.yml'
│
├─ supportedArchitectures
│  ├─ Description: Architectures that Yarn will fetch and inject into the resolver
│  ├─ Source: <default>
│  ├─ os: [ 'current' ]
│  ├─ cpu: [ 'current' ]
│  └─ libc: [ 'current' ]
│
├─ taskPoolConcurrency
│  ├─ Description: Maximal amount of concurrent heavy task processing
│  ├─ Source: <default>
│  └─ Value: 8
│
├─ taskPoolMode
│  ├─ Description: Execution strategy for heavy tasks
│  ├─ Source: <default>
│  └─ Value: 'workers'
│
├─ telemetryInterval
│  ├─ Description: Minimal amount of time between two telemetry uploads, in days
│  ├─ Source: <default>
│  └─ Value: 7
│
├─ telemetryUserId
│  ├─ Description: If you desire to tell us which project you are, you can set this field. Completely optional and opt-in.
│  ├─ Source: <default>
│  └─ Value: null
│
├─ tsEnableAutoTypes
│  ├─ Description: Whether Yarn should auto-install @types/ dependencies on 'yarn add'
│  ├─ Source: <default>
│  └─ Value: null
│
├─ unsafeHttpWhitelist
│  ├─ Description: List of the hostnames for which http queries are allowed (glob patterns are supported)
│  ├─ Source: <default>
│  └─ Value: []
│
├─ virtualFolder
│  ├─ Description: Folder where the virtual packages (cf doc) will be mapped on the disk (must be named __virtual__)
│  ├─ Source: <default>
│  └─ Value: '/home/archn/Projects/Redwood/my-redwood-project-test-storybook/.yarn/__virtual__'
│
├─ winLinkType
│  ├─ Description: Whether Yarn should use Windows Junctions or symlinks when creating links on Windows.
│  ├─ Source: <default>
│  └─ Value: 'junctions'
│
└─ yarnPath
   ├─ Description: Path to the local executable that must be used over the global one
   ├─ Source: /home/archn/.yarnrc.yml
   └─ Value: '/home/archn/.yarn/releases/yarn-4.1.1.cjs'

**Comment by jcianca** [comment] 2024-04-16 18:56
So I resetup my environment with nvm to try some different versions of node / yarn. I'm still getting hung up on storybook. This time with a new error, not sure if it's related:

`yarn rw storybook
Installing plugin "@redwoodjs/cli-storybook"...
yarn add v1.22.22
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed with exit code 1: yarn add -D @redwoodjs/cli-storybook@7.4.1
    at makeError (/Users/cianca/Documents/sbtest/sbtest9/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/cianca/Documents/sbtest/sbtest9/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installRedwoodModule (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/lib/packages.js:79:5)
    at async installPluginPackage (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/lib/plugin.js:228:5)
    at async loadPluginPackage (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/lib/plugin.js:176:21)
    at async loadCommandsFromCacheOrPackage (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/plugin.js:219:18)
    at async loadPlugins (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/plugin.js:155:22)
    at async runYargs (/Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/index.js:150:3)
    at async /Users/cianca/Documents/sbtest/sbtest9/node_modules/@redwoodjs/cli/dist/index.js:105:7 {
  shortMessage: 'Command failed with exit code 1: yarn add -D @redwoodjs/cli-storybook@7.4.1',
  command: 'yarn add -D @redwoodjs/cli-storybook@7.4.1',
  escapedCommand: 'yarn add -D "@redwoodjs/cli-storybook@7.4.1"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
rw <command>

Commands:
  rw build [side..]          Build for production
  rw check                   Get structural diagnostics for a Redwood project
                             (experimental)               [aliases: diagnostics]
  rw console                 Launch an interactive Redwood shell (experimental)
                                                                    [aliases: c]
  rw deploy <target>         Deploy your Redwood project
  rw destroy <type>          Rollback changes made by the generate command
                                                                    [aliases: d]
  rw dev [side..]            Start development servers for api, and web
  rw exec [name]             Run scripts generated with yarn generate script
  rw experimental <command>  Run or setup experimental features   [aliases: exp]
  rw generate <type>         Generate boilerplate code and type definitions
                                                                    [aliases: g]
  rw info                    Print your system environment information
  rw lint [path..]           Lint your files
  rw prerender               Prerender pages of your Redwood app at build time
                                                               [aliases: render]
  rw prisma [commands..]     Run Prisma CLI with experimental features
  rw record <command>        Setup RedwoodRecord for your project. Caches a JSON
                             version of your data model and adds
                             api/src/models/index.js with some config.
  rw serve [side]            Start a server for serving both the api and web
                             sides
  rw setup <command>         Initialize project config and install packages
  rw studio                  Run the Redwood development studio
  rw test [filter..]         Run Jest tests. Defaults to watch mode
  rw ts-to-js                [DEPRECATED]
                             Convert a TypeScript project to JavaScript
  rw type-check [sides..]    Run a TypeScript compiler check on your project
                                                              [aliases: tsc, tc]
  rw upgrade                 Upgrade all @redwoodjs packages via interactive CLI

Options:
      --version         Show version number                            [boolean]
      --cwd             Working directory to use (where `redwood.toml` is
                        located)
      --load-env-files  Load additional .env files. Values defined in files
                        specified later override earlier ones.           [array]
      --telemetry       Whether to send anonymous usage telemetry to RedwoodJS
                                                                       [boolean]
  -h, --help            Show help                                      [boolean]

Examples:
  yarn rw exec migrateUsers                 Run a script, also loading env vars
  --load-env-files stripe nakama            from '.env.stripe' and '.env.nakama'
  yarn rw g page home /                     Create a page component named 'Home'
                                            at path '/'

Unknown argument: storybook`

And trying to override the warning just to see what happens I still get "Unknown arguments: ignore-workspace-root-check, ignoreWorkspaceRootCheck, storybook"

**Comment by jcianca** [comment] 2024-04-16 21:59
So I finally got storybook working:

I discovered I had a (hidden) file ".pnp.cjs" in a parent folder. For me I was working in /Users/cianca/Documents/sbtest
and the .pnp.cjs file was in /Users/cianca. I deleted this (and some other yarn junk from that same folder) and storybook worked.

Hope this helps anyone who made a similar mistake.

**Comment by imcodingideas** [comment] 2024-05-19 02:34
Can you please let us know if you still are running into issues?

I'm aware that chakra ui doesn't work with server components.

**Comment by dac09** [comment] 2024-06-07 08:02
Hello, it looks like there's some solutions in this thread, and I'll close the issue for now. 

If you are still facing issues, feel free to comment/reopen with additional details 

Thank you community for chiming in ✌️

**Closed by dac09** 2024-06-07 08:02 UTC
Labels: bug/needs-info, topic/storybook
