### ISSUE TITLE
Cannot launch Storybook if GraphQL is not generated due to no SDL's yet

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#4530] opened 2022-02-19 21:56 UTC
I was trying to do a design-driven dev (cc @thedavidprice) using Storybook to help guide what my backend and data and with a new RW app that does not yet have any SDLs 

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1051633/154820395-a4cab236-1e5c-4358-8ed6-cdf525e81108.png">

Then because the web side could not generate graphql

> Error: Could not generate GraphQL type definitions (web)

then Storybook cannot launch.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/1051633/154820315-7729df44-03ce-42d5-bee2-bc2c3057823b.png">

If I simply create a new model for the cell I intend to create and an SDL (even just the model and id/timestamps) then all is well.

Not necessarily a bug, but a good troubleshooting tip.

This also does not bode well for a we side without an api side.

**Comment by thedavidprice** [comment] 2022-02-22 00:33
@dthyresson Were you on a TS project? If so, recently @virtuoushub added a TS check to the Storybook config, which now causes the Storybook build to fail on TS build error. 

To me, the updated Storybook config is correct — we should fail if TS build fails. However, I know we've been discussing the behavior for type generation when no SDLs exists (ideally, it shouldn't even attempt to generate types), but resolving the issue at that level might not be a near-term solution. In that case, we could consider reverting the SB config as much as I'd prefer not to.

Reactions?

**Comment by virtuoushub** [comment] 2022-02-22 14:29
This is an interesting one, I am of the opinion that failing fast is beneficial to catch issues earlier and often; 

so this is behaving as designed.

---

That being said, as a workaround I might advocate briefly looking into type checking being optional. I looked into it, but because it happens at the webpack config stage, it was not clear to me how to pass an arg from the CLI down to that level.

**Comment by thedavidprice** [comment] 2022-02-22 20:28
@Tobbe I know you're looking at the intial GraphQL errors that happen on a fresh install when running `yarn rw dev` — anything you've learned that's related to this?

**Comment by Tobbe** [comment] 2022-02-23 15:07
No. I haven't gotten that far yet. Still awaiting answers from The Guild before I decide on next steps in my own investigations

**Comment by thedavidprice** [comment] 2022-03-14 21:59
There's no type check config in Storybook as of last week. This has effectively been resolved.

**Closed by thedavidprice** 2022-03-14 21:59 UTC
