### ISSUE TITLE
[Bug?]: Mailer doesn't respect test -> when

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/redwood#9932] opened 2024-01-30 14:04 UTC
### What's not working?

Setting the `when` variable is not respected. I'm not getting an email in the test server in redwood studio. It works fine with this part of the code removed.

I also think it's not to have this based on NODE_ENV, but that's why I want to overwrite this. But back when we started using redwood, it turned out, that NODE_ENV was forcefully overwritten in parts by redwood - not sure if this is still the case.

### How do we reproduce the bug?

Set this as you r config 

```
import { Mailer } from '@redwoodjs/mailer-core'
import { NodemailerMailHandler } from '@redwoodjs/mailer-handler-nodemailer'
import { ReactEmailRenderer } from '@redwoodjs/mailer-renderer-react-email'

import { logger } from 'src/lib/logger'

export const mailer = new Mailer({
  handling: {
    handlers: {
      nodemailer: new NodemailerMailHandler({
        transport: {
          host: process.env.SMTP_HOST,
          port: Number(process.env.SMTP_PORT),
          secure: false, // true for 465, false for other ports
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD,
          },
        },
      }),
    },
    default: 'nodemailer',
  },

  rendering: {
    renderers: {
      reactEmail: new ReactEmailRenderer(),
    },
    default: 'reactEmail',
  },
  test: {
    when: true, // <--- the problematic part
  },

  logger,
})

```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by razzeee** [comment] 2024-01-30 14:13
Looking at the code, I'm not sure why it doesn't work, but at least the author is aware of the potential NODE_ENV problems https://github.com/redwoodjs/redwood/blob/main/packages/mailer/core/src/mailer.ts#L335

**Comment by Josh-Walker-GM** [comment] 2024-01-30 14:40
Do you have a recommendation of a better practice we could adopt other than relying on `NODE_ENV`? 

I'm not sure if this is the expected behaviour or not. By default when you have test mode enabled the mailer will use an in-memory handler (from the `@redwoodjs/mailer-handler-in-memory` if you have it as a dev dependency). The default behaviour where it is sent to redwood studio is for 'development' mode.

**Comment by razzeee** [comment] 2024-01-30 14:47
I think I confused `test` with `development` :/
Still looking to confirm, that that actually is what I want.

Regarding `NODE_ENV` I'm not sure, here's our setup, that I've created, after figuring out that `NODE_ENV` get's rewritten.

We have three stages - each developers local system, a test system and a production system.

So I've introduced `ENVIRONMENT` that is `production`, `test` or `development`. Not sure if we actually check for `test` somewhere yet, but it's good to have I guess.

I've also found the reference to this in my gitlog on why I felt that we needed to not use `NODE_ENV` https://github.com/redwoodjs/redwood/pull/1755#issuecomment-1445898103

**Comment by Josh-Walker-GM** [comment] 2024-01-30 14:57
Thanks for the link to the previous discussion. I'll see if I can bring it up with some of the team but I remember we didn't yet settle on a better way to detect modes other than `NODE_ENV`. I know we sometimes forcefully set the value of `NODE_ENV` but FWIW I'm not sure that's a best practice either.

Yeah sorry if the docs aren't as clear as they should be. We have three modes:
 - test
 - development
 - production

We check for test first, then dev, and then fallback to production mode. By default test mode is enabled when `NODE_ENV === 'test'` and development mode is enabled when `NODE_ENV !== 'production'`. By default in test mode we send mail to an in-memory handler which comes from the dev dependency `@redwoodjs/mailer-handler-in-memory`. In development mode we send mail to studio using the `@redwoodjs/mailer-handler-studio` package which is also added as a dev dependency.

Are you looking to configure the mailer to send your test mode email to studio too?

**Comment by Josh-Walker-GM** [comment] 2024-01-30 15:27
Sorry so is there still a bug here with the `when` prop?

**Comment by razzeee** [comment] 2024-01-30 16:51
> Sorry so is there still a bug here with the `when` prop?

No, I think that part is fine. I'm still trying to figure out the correct config, to get the testsystem to not use the in memory one. I think I'll need to find the correct combination of `test` and `development` `when`

**Comment by Josh-Walker-GM** [comment] 2024-01-30 19:51
There is also the `handler` option you can pass alongside the `when`. This lets you override the default handler and can be the key of any handler you've defined in your config. So for example if you wanted to you could do something like:
```ts
test: {
  when: process.env.ENVIRONMENT === 'test',
  handler: 'nodemailer', // or some other handler you define in the normal config above 
}
```

**Comment by Josh-Walker-GM** [comment] 2024-01-30 21:23
Okay let me get back to you on the required config because what I thought would work didn't when I quickly tested just now.

**Comment by Josh-Walker-GM** [comment] 2024-01-31 00:10
I've included the full file so sorry for the long inline code snippet but this configuration does appear to work with my testing. Unfortunately right now you have to explicitly define a studio handler which then you tell the test mode to use.

```ts
import { Mailer } from '@redwoodjs/mailer-core'
import { NodemailerMailHandler } from '@redwoodjs/mailer-handler-nodemailer'
import { StudioMailHandler } from '@redwoodjs/mailer-handler-studio'
import { ReactEmailRenderer } from '@redwoodjs/mailer-renderer-react-email'

import { logger } from 'src/lib/logger'

export const mailer = new Mailer({
  handling: {
    handlers: {
      nodemailer: new NodemailerMailHandler({
        transport: {
          host: 'localhost',
          port: 4319,
          secure: false,
        },
      }),
      studio: new StudioMailHandler(), // <-- define a studio handler
    },
    default: 'nodemailer',
  },

  rendering: {
    renderers: {
      reactEmail: new ReactEmailRenderer(),
    },
    default: 'reactEmail',
  },

  test: {
    when: true,
    handler: 'studio', // <-- tell test mode to use the studio handler
  },

  logger,
})

```
Right now this might not work if you've customised studio to run on a different port than the default. If you have then you can actually just use a nodemailer handler and point it to the correct port - this is all the studio handler package is doing under the hood.

**Comment by razzeee** [comment] 2024-01-31 15:58
Thank you, that would be nice in the docs, but for us, I arrived at 
```
 test: {
    when: false,
  },
  development: {
    when: process.env.ENVIRONMENT === 'local',
  },
```
For now, which seems to solve this part. Unfortunatly I've hit the next roadblock, due to react-email not really working with outlook.

**Comment by Josh-Walker-GM** [comment] 2024-01-31 17:52
Okay noted on the documentation. Do you think we should close this issue or is there more to workout here?

**Comment by razzeee** [comment] 2024-01-31 17:58
I think it's fine to close - I think we also captured most context, so it should be easy to search for this in the future.

**Closed** 2024-01-31 17:57 UTC
Labels: bug/needs-info, topic/mailer
