### ISSUE TITLE
Update prisma to 3.13 because of OpenSSL 3

### ISSUE THREAD

**Issue by yk-sgr** [redwoodjs/redwood#5362] opened 2022-04-30 14:06 UTC
https://github.com/prisma/prisma/issues/11356

Prisma 3.12 does not work with the new OpenSSL version which is for example defautlt on the new Ubuntu 22.04. With Prisma 3.13 they introduced a fix.

**Comment by davidrhoderick** [comment] 2022-05-01 11:16
Confirmed this is an issue with Pop!_OS 22.04.  I was going to try Redwood.js out now that it's v1 (last time I tried it was 0.2x) and was stuck at running `yarn redwood dev` because of this issue.

**Comment by jtoar** [comment] 2022-05-01 12:24
Thanks @yk-sgr and @davidrhoderick; we've got a PR for it now and I'll merge it as soon as checks pass: https://github.com/redwoodjs/redwood/pull/5375

**Comment by yk-sgr** [comment] 2022-05-01 20:52
Thanks, i't working now.

**Comment by jnhooper** [comment] 2022-05-02 03:59
sorry this is probably a very basic question, but how do i get the latest package? i [upgraded](https://community.redwoodjs.com/t/how-to-upgrade-redwoodjs-app-and-packages/122) and am currently on `v1.2.0` but when i install i still get prisma client 3.12 I've tried clearing yarns cache, removing node_modeuls and yarn.lock. It looks like this got merged into main, but a new version hasn't be released since then so i'm just confused with how to force yarn to get the latest package?

**Comment by jtoar** [comment] 2022-05-02 04:44
@jnhooper no worries! Every time a PR is merged to main, a "canary" version is released. You can upgrade to that via:

```
yarn rw upgrade --tag canary
```

**Comment by jnhooper** [comment] 2022-05-02 06:42
!! Amazing thank you so much!

**Comment by jtoar** [comment] 2022-05-03 19:28
We just released https://github.com/redwoodjs/redwood/releases/tag/v1.3.0!

**Closed by jtoar** 2022-05-03 19:28 UTC
