### ISSUE TITLE
[Bug?]:  cant make redwoodjs project when using node 16 works correctly node 14

### ISSUE THREAD

**Issue by johnneijzen** [redwoodjs/redwood#7021] opened 2022-12-05 08:34 UTC
### What's not working?

I cant setup Redwoodjs when using node v16.18.1 (npm v8.19.2) but works perfectly with node 14

[redwoodjs error.txt](https://github.com/redwoodjs/redwood/files/10152176/redwoodjs.error.txt)

### How do we reproduce the bug?

using nvm install 16
then nvm use 16
corepack enable (https://yarnpkg.com/getting-started/install)
then run yarn create redwood-app my-redwood-project

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by johnneijzen** [comment] 2022-12-05 08:38
Environment if using node 14:
![image](https://user-images.githubusercontent.com/1343960/205591318-7f6243c2-0fd8-49a9-9e26-afc6b0003c8f.png)

Environment if using node 16 folder wont be created but if i use folder create in node 14 this environment:
![image](https://user-images.githubusercontent.com/1343960/205591587-7cb6c430-f138-4523-962e-830f17a81384.png)

**Comment by simoncrypta** [comment] 2022-12-09 17:43
Hey @johnneijzen what do you get when you run `yarn create redwood-app my-redwood-project` ? I tried it without any issue. I see that you use node V16.18.1, I got the V16.16.0 (the LTS version) maybe that's the cause of the issue, we recommend using the LTS version for stability.

**Comment by simoncrypta** [comment] 2022-12-22 02:37
Since we don't have more details about this bug, I will close this one in favour of #7225. 
Let me know if the problem came from a different source and I will reopen this issue.

**Closed by simoncrypta** 2022-12-22 02:37 UTC
Labels: bug/needs-info
