### ISSUE TITLE
Node v14 clashes with Chokidar 

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#2008] opened 2021-03-15 17:00 UTC
I just posted the following on Discord

>yarn install v1.22.5
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
**warning @redwoodjs/core > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.**

RedwoodJS was recently upgraded to require Node v14. Does anyone worry about this warning above?

So far nobody responded and in the meantime I found that I cannot run the command `yarn rw dev`:

![image](https://user-images.githubusercontent.com/2712405/111190426-74b78800-858d-11eb-9f9d-332414114d6e.png)

I do not believe that this is a Windows artifact, so I am puzzled why is it that nobody else found this already

**Comment by Josh-Walker-GM** [comment] 2022-11-28 13:57
I think this may have resolved itself in the time since this issue opened? 

I attempted to reproduce with the following steps:

1. Used node v14.21.1 (the v14 lts)
2. Installed a fresh redwood typescript app via create redwood
3. Ran `yarn rw dev` from within the new project

There was no error running the dev server. I also did not see the `warning @redwoodjs/core > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.` error during installation.

Running `yarn why chokidar` from within the generated project only returns one package which uses chokidar2 which is `watchpack-chokidar2`. If you ask `yarn why chokidar` from within the framework you can see that `@redwoodjs/api-server` is the only redwood package to explicitly request it and its version 3. Again only `watchpack-chokidar2` asks for version 2.

Ping @jtoar

**Comment by Josh-Walker-GM** [comment] 2023-10-07 02:47
I'm going to close this one given we have now moved beyond supporting node v14.

**Closed by Josh-Walker-GM** 2023-10-07 02:47 UTC
Labels: help wanted, bug/needs-info, topic/windows
