### ISSUE TITLE
Update Docs for Storybook

### ISSUE THREAD

**Issue by kataqatsi** [redwoodjs/redwood#3339] opened 2021-09-03 08:17 UTC
All of these files/directories don't exist

>Configuring Storybook
There's two files for configuring Storybook: storybook.config.js and storybook.preview.js. You can think of the two as being analogous to Redwood's api and web sides—storybook.config.js configures Storybook's server while storybook.preview.js configures the way stories render.

>Configuring the Server with storybook.config.js
You can configure Storybook's server by adding a storybook.config.js file to your web/config directory. Redwood merges this with it's base configuration.

I just wanted to add [@storybook/addon-essentials](https://storybook.js.org/docs/react/essentials/introduction)
Any way I can do this?

**Comment by thedavidprice** [comment] 2021-09-08 22:18
Looping in @jtoar

**Comment by callingmedic911** [comment] 2021-09-11 14:42
@kataqatsi Hello! These two files storybook.config.js and storybook.preview.js are not there on a clean install of the redwood app. You can create these files in /web/config and then (re)start the storybook server using the command: `yarn rw storybook`. Hopefully, this should resolve your issue. :)

@thedavidprice I hope I'm not intruding in between - this issue is in the "help wanted" column :). I just had a quick glance at [Storybook docs](https://redwoodjs.com/docs/storybook) and I think we should add the command `yarn rw storybook` in the introductory section. We have it covered in CLI docs but this command is the only thing most people need. :)

**Comment by thedavidprice** [comment] 2021-09-17 00:30
@callingmedic911 if you would like to make those updates and changes you suggested, please do! Appreciate your help here.

**Comment by jtoar** [comment] 2021-09-17 05:27
@callingmedic911 thanks for that detailed breakdown of the problem + next steps! For better or worse I found a typo I wanted to fix and just started fixing the whole doc so if you don't mind I'll apply your suggestions in a PR momentarily that I'd be happy to have you review.

**Comment by kataqatsi** [comment] 2021-09-18 01:42
Thanks! Excited to use the addon-essentials in my rw project :smiley:

**Comment by jtoar** [comment] 2021-09-18 02:15
@kataqatsi Anytime, thanks for opening the issue!

**Comment by kataqatsi** [comment] 2021-09-18 07:55
@thedavidprice, @jtoar hi, I actually hadn't tried running this before thanking you. The newly updated docs for adding @storybook/addon-essentials didn't work. Looks like it's due to one of the addons for storybook having a webpack4/webpack5 dependency issue in a yarn-based monorepo using workspaces. See here: https://github.com/storybookjs/storybook/issues/15336

I'll leave this hacky quick fix here for anyone wanting to use @storybook/addon-essentials for their rw app
From the docs:
> ```
> cd redwood-project/web
> mkdir config
> touch config/storybook.config.js config/storybook.preview.js
> ```
> in web/config/storybook.config.js
> ```
> // web/config/storybook.config.js
> 
> module.exports = {
>   /**
>    * This line adds all of Storybook's essential addons.
>    * 
>    * @see {@link https://storybook.js.org/addons/tag/essentials}
>    */
>   addons: ['@storybook/addon-essentials']
> }

then also running:
```
cd redwood-project
yarn add @storybook/addon-essentials -W
```
adding the hacky/quick fix into redwood-project/node_modules/@redwoodjs/testing/config/storybook/main.js:
```
typescript: { reactDocgen: false },
```
before this line: https://github.com/redwoodjs/redwood/blob/b3dd5d6cf5625395400c6312d502462aed2ccdfa/packages/testing/config/storybook/main.js#L24
this still gave an error until i added this:
```
cd redwood-project
yarn workspace web add babel-loader
```

and a poorly made pr i'm cool with getting rejected for a real fix:
https://github.com/redwoodjs/redwood/pull/3396

**Comment by jtoar** [comment] 2021-09-18 08:26
@kataqatsi Thanks for investigating and providing a quick fix!

My bad on the docs. I wasn't writing them as "how to setup storybook addons" which is what I should've done / would've written a cookbook for. I was writing them only to show that if you wanted to add an addon, you'd do it in the `storybook.config.js` file. I'm happy to add a little more using `@storybook/add-ons` as an example.

Just from a superficial reading of that issue you linked to, it kind of looks like a real fix has to come from Storybook's side. I'll investigate more over the course of the week

**Comment by thedavidprice** [comment] 2021-09-18 20:07
@kataqatsi Ok, having looked at PR #3396, I'm not understanding if the project fix you show above is working on it's own. Or, does it require the patches to the Redwood framework — assuming "no" as those seem redundant.

Once confirmed the workaround is, well, working, let's close out #3396 

@jtoar @callingmedic911 I do think we'll need to document the workaround in the Redwood Storybook docs until an upstream fix comes through. I comment on and am following storybookjs/storybook#15336

Sound like a plan?

**Comment by thedavidprice** [comment] 2021-09-20 22:51
@jtoar @kataqatsi Well, I went down the rabbit hole on this one (see https://github.com/storybookjs/storybook/issues/15336#issuecomment-923408113) and found a way to fix with Webpack config in `@redwoodjs/testing`. However, when I started working on the fix on our latest `main` branch, I discovered the original problem has been resolved!

So yay/boo.

I'm closing #3396 as it's no longer needed.

@kataqatsi if you find out this Issue persists once v0.37 is released (later this week), please re-open and update us accordingly.

**Closed** 2021-09-20 22:52 UTC
Labels: topic/storybook, v1/for-consideration

**Comment by kataqatsi** [comment] 2021-09-22 18:39
thanks rw team for the quick replies!
