### ISSUE TITLE
Jest DX not the best since v0.36

### ISSUE THREAD

**Issue by morrislaptop** [redwoodjs/redwood#4017] opened 2021-12-29 11:24 UTC
This is more of a discussion at this point, but thought I'd post just in case...

In 0.36, [this plugin](https://marketplace.visualstudio.com/items?itemName=CoachRichbart.better-jest) worked. IMO this is a much better workflow than the *magic* jest watch. I get an error `SyntaxError: Cannot use import statement outside a module` so I assume the plugin is skipping some jest / babel configuration somewhere..

If I fallback to `yarn rw test` and I'm using libraries like axios, node-fetch etc... it runs fine the first time, but then on the second test I get an error like `Cannot read property '_origin` - it seems like these libraries think they are in the browser for some reason?

This wasn't the `it just works` feeling I've had from prior releases. Keep up the good work!

**Comment by morrislaptop** [comment] 2021-12-30 11:41
Confirmed import error started happening since 0.39

**Comment by morrislaptop** [comment] 2021-12-30 11:52
`Cannot read property '_origin'` seems to be an issue since before 0.36

**Comment by dac09** [comment] 2021-12-30 18:56
@morrislaptop - this is a fair point, but I just wanted to confirm that the issue is that you can't seem to use jest with that extension? 

Could you please also confirm if you were using scenarios before the upgrade and it all worked with the plugin?

**Comment by morrislaptop** [comment] 2021-12-30 19:58
> @morrislaptop - this is a fair point, but I just wanted to confirm that the issue is that you can't seem to use jest with that extension?

Yep that's the issue.

> Could you please also confirm if you were using scenarios before the upgrade and it all worked with the plugin?

Was not using scenarios

**Comment by dac09** [comment] 2022-01-10 17:54
Hey @morrislaptop - I have some good news for you! I'm working on a fix for this, but in the mean time you can get the Better Jest plugin working by adding this file to the root of your project.

**./jest.config.js**
```js
// This the monorepo jest config
// Each side has their configuration setup e.g. in `web/jest.config.js`

// Note that jest configs aren't merged!

module.exports = {
  rootDir: '.',
  projects: ['<rootDir>/{*,!(node_modules)/**/}/jest.config.js'],
}
```

**Comment by morrislaptop** [comment] 2022-01-10 18:18
@dac09 great, thanks! 

Any ideas on the libraries like axios getting confused on the context when running the tests on both sides? Should I make a separate issue for that?

**Comment by dac09** [comment] 2022-01-11 15:14
I'm not sure the axios issue is related to jest config, but sure happy for you to raise another issue, would be super helpful if you had a reproduction.

Just FYI - One of the things we've noticed is that jest runner seems to have issues when not using the `--runInBand` flag (which `rw test` automatically does for you). It manifests as:
a) "TextDecoder" not found, on the web side
b) Plugins[2][0] or something simialr is not valid - on the api side

This is a separate issue, but maybe related to what you're seeing on axios!

**Closed** 2022-02-02 23:17 UTC
Labels: topic/testing, v1/for-consideration, topic/fully-integrated-dx
