### ISSUE TITLE
Support for pnpm, ability to choose package manager

### ISSUE THREAD

**Issue by valerii15298** [redwoodjs/redwood#3970] opened 2021-12-21 22:36 UTC
First of all thank you for such a great tool🔥.

As I understand Redwood picks up best technologies so you do not need to make a choice. So why don't use pnpm instead of yarn? As I know I has lot of advantages over both npm and yarn. And if not, then why don't put it optionally, to be able choose package manager? For example there will be default package manager but if you want you can choose different. I really appreciate pnpm and would be nice to have such ability.
This is more like feature request and a question. So, put a like on this message if you also want Redwood to have such feature.

**Comment by ajcwebdev** [comment] 2021-12-21 22:54
Definitely interest in making this happen, we actually have an open issue here already: https://github.com/redwoodjs/redwood/issues/2907

**Comment by thedavidprice** [comment] 2021-12-22 00:23
Completely agree @valerii15298 There is a lot of work to be done under the hood, but our goal is to (eventually) get to the place where this is possible.

As Anthony mentioned, this is a duplicate of #2907 Closing this one in favor of continuing conversation over there.

**Closed by thedavidprice** 2021-12-22 00:23 UTC
Labels: triage/processing
